### ISSUE TITLE
 iX[2.0.4] in React production build showToast error.

### ISSUE THREAD

**Issue by mhmmdkndr** [siemens/ix#1006]
### What happened?

Hello iX Team, 

We are using iX[2.0.4] in React. We encounter an error in the Toast component as in the picture below. All of the packages we build with "npm run build" have a similar situation, including the code on the ix webpage (https://ix.siemens.io/docs/controls/toast).
Someone can suggest any solution? Thanks in advance.
![image](https://github.com/siemens/ix/assets/26063727/b616a205-b4f3-4db5-8db0-93e7487a7d98)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/run?file=src%2Ftoast.tsx
```

**Comment by jul-lam** [comment]
When I run `npm run build` inside the react example from the documentation in Stackblitz, no error is thrown. However, a warning is displayed, which is not a problem in this case. The issue might be with the setup of the project you used to build the code. Can you please provide more details about it?

**Comment by robert-wettstaedt** [comment]
@jul-lam [here is a working example.](https://codesandbox.io/p/devbox/siemens-ix-issues-1006-crx2qq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr6gu7ze00073b6e9s06qvin%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr6gu7ze00023b6ekmx5is4f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr6gu7ze00053b6eomzsu44s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr6gu7ze00063b6ex73lkcm8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr6gu7ze00023b6ekmx5is4f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6gu7ze00013b6estxwja9g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clr6gu7ze00023b6ekmx5is4f%2522%252C%2522activeTabId%2522%253A%2522clr6gu7ze00013b6estxwja9g%2522%257D%252C%2522clr6gu7ze00063b6ex73lkcm8%2522%253A%257B%2522id%2522%253A%2522clr6gu7ze00063b6ex73lkcm8%2522%252C%2522activeTabId%2522%253A%2522clr6gur4s00463b6e99zwq0b4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr6gur4s00463b6e99zwq0b4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr6gu7ze00053b6eomzsu44s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr6gu7ze00033b6en189z4ty%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clr6gu7ze00043b6ev51nh763%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr6gl3ab000eedi3di5t0xid%2522%257D%255D%252C%2522id%2522%253A%2522clr6gu7ze00053b6eomzsu44s%2522%252C%2522activeTabId%2522%253A%2522clr6gu7ze00043b6ev51nh763%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) It's just a project generated by `create-react-app` with `@siemens/ix-react@2.0.4`. The app has been built and is served from the `build` folder. Check the browser console when you click the button.

**Comment by jul-lam** [comment]
Thank you for providing the example! We will investigate the issue.

**Comment by mohitmutha** [comment]
We are facing the same issue. We are using vite for creating the project. 
![image](https://github.com/siemens/ix/assets/5111605/1d5bf298-3a57-4ba8-a300-08ebdabf8075)

**Comment by mohitmutha** [comment]
Found a workaround. Not sure if this is the intended way to use the component. 

When I add a `IxToastContainer` element to somewhere in the skeleton of the application the toast starts working. My guess is that when the element is created dynamically the class behaviour is getting lost and hence the issue. 

Strangely this happens only in the transpiled build after running `yarn build`. When running in dev mode it works fine. 

Please add a fix or modify the documentation.

**Comment by robert-wettstaedt** [comment]
@mohitmutha that seems to be right! 

However, it is important to note, that you cannot wrap it around your application as in:

```jsx
<IxToastContainer>
  <Application />
</IxToastContainer>
```

Instead it needs to be its own enclosed tag sitting next to your application:

```jsx
<>
  <IxToastContainer />
  <Application />
</>
```

The reason is that the component does not render its children. [For some reason the line to do that is commented out.](https://github.com/siemens/ix/blob/b38f3c0889673dfbb1a857378e3b1203e233af2a/packages/core/src/components/toast/toast-container.tsx#L114)

**Comment by danielleroux** [comment]
We will do some refactorings regarding `appending` dynamic component, this refactorings will solve the issue. It is planned for the next releases.

[IX-822]

**Comment by dogukan-duduoglu** [comment]
Anyone having problems with icons not showing after building with the workaround?

**Comment by robert-wettstaedt** [comment]
> Anyone having problems with icons not showing after building with the workaround?

@dogukan-duduoglu  No I did not experience this
