### ISSUE TITLE
Can't disable select toggling in Group

### ISSUE THREAD

**Issue by ahmedibrahim92** [siemens/ix#1010]
### What happened?

I'm using IX Group and I set the select attribute true. I need to keep it selected and I don't need to toggle between select/unselect by clicking.
Actually, the select attribute is always true but I see the toggle is active and I can't prevent default event as well.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/stackblitz-starters-5hsj6v
```

**Comment by matthiashader** [comment]
Internal ref [IX-902]

**Comment by flxlst09** [comment]
Hello @ahmedibrahim92 we are currently reviewing any possible adaptions for the ix-group. In it's intended usage, ix-group:

- organizes related information or elements into a group
- can be used for master detail navigation
- selecting an element within a group, navigates to detailed information

Based on various feedback we understand that the group component is also used for other use cases. It would be nice to learn more about how you intend to use the ix-group and why the supressing of the selected state on-click is of importance to you.

Again thanks for helping us build and improve iX for everyone and we are sorry we could not provide you with an immediate solution.
