### ISSUE TITLE
IX Select is active (colored) when hover on it however it is read only.

### ISSUE THREAD

**Issue by ahmedibrahim92** [siemens/ix#1011]
### What happened?

I disabled (set readonly= true) the select component and then I hovered on it, I see it is color border is becoming colored like it is active however it is disabled so the hover should be disabled as well.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/stackblitz-starters-6camug
```

**Comment by nuke-ellington** [comment]
Hello @ahmedibrahim92, this is the intended behaviour. If you don't want to see any mouse states you would have to set the component to `disabled`. Note that `read-only` and `disabled` are two distinct states.
