### ISSUE TITLE
Toast message runtime error

### ISSUE THREAD

**Issue by rumeysanurarslan** [siemens/ix#1020]
We're having an issue with the toast component. In case of success or failure of an operation, we are sending a toast message to the user. 
However, when the project is started for the first time, or when a toast message is displayed for the first time on a page, we receive the following error.
![toast-message-error1](https://github.com/siemens/ix/assets/32144869/c39e5413-f646-4e4d-b4f3-055e9a4c121d)
![toast-message-error2](https://github.com/siemens/ix/assets/32144869/5ecf0db6-ec25-4eaa-9af4-7e2965a888b6)

**Comment by danielleroux** [comment]
![image](https://github.com/siemens/ix/assets/2144313/6edb4fa5-3ef9-4304-bb43-9f0dd8835cd0)
Please use the issue create template next time.

Missing information (see required fields form issue template)

**Comment by rumeysanurarslan** [comment]
I created a new issue with bug template.
