### ISSUE TITLE
Toast message runtime error 

### ISSUE THREAD

**Issue by rumeysanurarslan** [siemens/ix#1021]
### What happened?

We're having an issue with the toast component. In case of success or failure of an operation, we are sending a toast message to the user.
However, when the project is started for the first time, or when a toast message is displayed for the first time on a page, we receive the following error. 

![toast-message-error1](https://github.com/siemens/ix/assets/32144869/a2fe61b2-9abd-4e6c-88b2-236d0004155b)
![toast-message-error2](https://github.com/siemens/ix/assets/32144869/24309996-4c2d-4ff4-b958-1a4c4730e309)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
You can find the issue below link:
https://stackblitz.com/edit/6amjxf?file=src%2Ftoast.tsx
```

**Comment by ridvandmrc** [comment]
createElement and querySelector element works async, it that PR it made sync.
