### ISSUE TITLE
ix-select cannot be selected after clearing the input field

### ISSUE THREAD

**Issue by wanghaoyu0210** [siemens/ix#1023]
### What happened?

1. Use official document : https://ix.siemens.io/docs/controls/select.
2. Focus on input field of the selector.
3. Clear the input field, such as item1.
4. Select item1 again.
5. Item1 cannot be selected at this time
<img width="261" alt="2023-12-22 16_01_10-Select _ Siemens Industrial Experience" src="https://github.com/siemens/ix/assets/35959373/42dead88-3690-4cdb-b612-90721b36da45">

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
https://ix.siemens.io/webcomponent-examples/dist/preview-examples/select.html?theme=theme-brand-dark
```

**Comment by chencc1988** [comment]
I'm guessing you probably mean that the item can be deleted by backspace, but it doesn't change back to what it was when you click on it again.

![Animation](https://github.com/siemens/ix/assets/10339536/6ad6a1d6-b531-4edb-9fd6-cbf7d7f0c92e)

**Comment by matthiashader** [comment]
Internal ref [IX-865]
