### ISSUE TITLE
Console Error in <ix-basic-navigation> component

### ISSUE THREAD

**Issue by praveenn16** [siemens/ix#1034]
### What happened?

Hi Team,

Getting error in console when I use breakpoints in

<ix-basic-navigation> component

eg-

<ix-basic-navigation

id="navigation"

breakpoints="{['sm', 'lg']}">
![navigationIssue](https://github.com/siemens/ix/assets/156085957/c24a8f0c-ca91-4ace-bd54-5f2f6b796c5d)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
<ix-basic-navigation
id="navigation"
breakpoints="{['sm', 'lg']}"></ix-basic-navigation>
```

**Comment by danielleroux** [comment]
Your angular template is not valid.

```
<ix-basic-navigation [breakpoints]="['sm', 'lg']">
```
