### ISSUE TITLE
ix-icon showing its icon name in the tooltip

### ISSUE THREAD

**Issue by praveenn16** [siemens/ix#1037]
### What happened?

ix-icon showing its icon name in the tooltip. Please give us option for disabling the title and also a provision for giving our custom title

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
<ix-icon name="star" size="16"></ix-icon>
```

**Comment by danielleroux** [comment]
Fixed with https://github.com/siemens/ix-icons/issues/48
