### ISSUE TITLE
Radio button alignment issue

### ISSUE THREAD

**Issue by praveenn16** [siemens/ix#1045]
### What happened?

Radio button's checkbox position is not centered.

Attaching screenshot from -  https://ix.siemens.io/docs/controls/radiobutton

![radioButtonIssue1](https://github.com/siemens/ix/assets/156085957/76834fe6-4b9e-4b59-b7a9-791eb56e203e)

![radioButtonIssue](https://github.com/siemens/ix/assets/156085957/694d0263-9216-4269-bfae-69c3c8b64609)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
<input checked id="checkbox_1_1" name="group_1" type="radio" />
    <label for="checkbox_1_1"> Checked </label>
```

**Comment by nuke-ellington** [comment]
[IX-736]
