### ISSUE TITLE
Category-Filter: after selection of first filter remaining categories are not suggested

### ISSUE THREAD

**Issue by lugd0n** [siemens/ix#1047]
### What happened?

When a category filter is set, the autosuggestion does not show the remaining categories. For getting the remaining categories displayed, the user needs to click out of the filter and select the filter again.

**Excpected Behavior**
After selecting a category-filter the remaining categories are suggested

**Vendor and Product are suggested.**
![grafik](https://github.com/siemens/ix/assets/101355091/60ef5afc-71f0-4ca7-83e2-8dd4a9e0e4b3)

**Vendor with filter criteria is selected. Product is no longer suggested.**
![grafik](https://github.com/siemens/ix/assets/101355091/270b7252-dc78-466c-bddc-bb229907aa89)

**After clicking out of the filter and clicking in Product is suggested again.**
![grafik](https://github.com/siemens/ix/assets/101355091/f7f67a24-cd53-4f48-9284-f1d9515938bb)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.0

### Code to produce this issue.

```shell
/* Taken from the IX-Docu: https://ix.siemens.io/docs/controls/category-filter */

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <ix-category-filter
      placeholder="Filter by"
      [repeatCategories]="repeatCategories"
      [categories]="categories"
      [filterState]="filterState"
    ></ix-category-filter>
  `,
})
export default class CategoryFilter {
  repeatCategories = false;
  filterState = {
    tokens: ['Custom filter text'],
    categories: [
      {
        id: 'ID_1',
        value: 'IBM',
        operator: 'Not equal',
      },
    ],
  };
  categories = {
    ID_1: {
      label: 'Vendor',
      options: ['Apple', 'MS', 'Siemens'],
    },
    ID_2: {
      label: 'Product',
      options: ['iPhone X', 'Windows', 'APS'],
    },
  };
}
```

**Comment by matthiashader** [comment]
Internal ref [IX-868]
