### ISSUE TITLE
Logout menu item hide option for IxMenuAvatar

### ISSUE THREAD

**Issue by slymnozdmrc** [siemens/ix#1050]
### Suggestion / feature request

IxMenuAvatar by default includes a logout dropdown item, and there is currently no option provided to hide it. In our project , we do not require an option like logout. We would like to provide different feature as IxMenuAvatarItem under IxMenuAvatar and dont want to show Logout to our users. Could you please add an option as a prop to hide the logout menu item?

Need to hide below Logout item
![image](https://github.com/siemens/ix/assets/14888275/46b58e96-dd10-4cc5-9b8b-8c7d716a7713)

Current Provided Options:
![menuavataritem](https://github.com/siemens/ix/assets/14888275/71e433a6-8bd1-4feb-b252-a1a1f73c2fee)

What type of frontend frameware are you seeing the problem on?
React

Which version of iX do you use?
v2.0.4

BR

**Comment by danielleroux** [comment]
Duplicated https://github.com/siemens/ix/issues/843
