### ISSUE TITLE
ix-workflow component having a glitch while loading

### ISSUE THREAD

**Issue by Renjith-K-AMS** [siemens/ix#1053]
### What happened?

Hi Team,

ix workflow component while using it vertically, while reloading the page or component as a modal in the app
initially the vertical lines are show as horizontal lines for a millisecond and then it loads properly

This is totally annoying in a user experience perspective

Thanks,
Renjith K

Workflow issue in your test app 
https://github.com/siemens/ix/assets/157672088/31328466-4a2a-4d73-819d-c6532089c98d

Workflow issue reproduced in our application
https://github.com/siemens/ix/assets/157672088/fd4f728c-9493-4dca-9fb7-9e7b45c16ec2

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
html template
==================================================== 
         <ix-workflow-steps
            id="workflow-component"
            data-test-id="workflow-component"
            class="workflow-steps"
            [selectedIndex]="selectedItem"
            vertical>
            <ix-workflow-step
              id="step-{{ stepIndex }}"
              (click)="commStreamStepClick(item, stepIndex)"
              *ngFor="let item of stepItems; index as stepIndex"
              [status]="item.status"
              class="step-item"
              >{{ item.name }}</ix-workflow-step
            >
          </ix-workflow-steps>

===================================================================


component.ts snippet

    this.stepItems = [
      { name: CommunicationStream.BasicData, status: '' },
      { name: CommunicationStream.Protocols, status: '' },
      { name: CommunicationStream.AdvancedSettings, status: '' },
    ];
```

**Comment by Renjith-K-AMS** [comment]
Hi Team any update

**Comment by matthiashader** [comment]
The bug is noted internally, we will take a closer look at it during the next planning.

Internal ref [IX-871]
