### ISSUE TITLE
ix-icon component does not expose the 'size' prop as input

### ISSUE THREAD

**Issue by Robin-wbe** [siemens/ix#1057]
### What happened?

Hi iX-Team,

when using the `ix-icon` component I noticed, that the `size` prop cannot be set unless the `CUSTOM_ELEMENTS_SCHEMA` is added to the schemas list in the component's description.

I guess this can be resolved by adding `size` to the inputs declaration of the [ix-icon component](https://github.com/siemens/ix/blob/main/packages/angular/src/ix-icon.ts) in the angular package. Should I create a pull request?

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/stackblitz-starters-6om6iu?file=src%2Fmain.ts
```

**Comment by matthiashader** [comment]
Internal ref [IX-887]

**Comment by danielleroux** [comment]
@Robin-wbe sorry we just talked about this issue and we missed your suggestion regarding open a pull request on your self. Sorry for that!
