### ISSUE TITLE
Remove margin from ix-message-bar

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#1059]
### Prerequisites

- [x] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

ix-message-bar component has margins on two sides. We don't need that and it breaks the layout.
![image](https://github.com/siemens/ix/assets/144789952/c7b039fb-e69e-45c0-8ba4-96d9d6b6e7eb)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.3

### Code to produce this issue.

```shell
<ix-message-bar>Message text</ix-message-bar>
```

**Comment by matthiashader** [comment]
Internal ref [IX-874]

**Comment by Aiderlei** [comment]
We are facing same issues, another option would be to allow to overwrite the internally used sass variables, e.g. as css variables. Since ix does not ship the sass files in angular we were not able to overwrite them.

**Comment by TDaniel-evo** [comment]
Is there any update on this? 
Is this PR related? https://github.com/siemens/ix/pull/1064

**Comment by TDaniel-evo** [comment]
Instead of removing the right and left margins, additional top margin has been added. Is this the expected solution?
![image](https://github.com/siemens/ix/assets/144789952/d73960fc-bf7b-4209-8bef-c58b1643fd73)

**Comment by danielleroux** [comment]
The PR moved the margin property from a shadowRoot selector to the host element https://github.com/siemens/ix/pull/1064/files#diff-8185c60fb032d26864d303d4b1dc083986381a7e6e3036249e3500d485451ef6

This makes is possible to overwrite the default margin:

```css
margin: 0px;
```
