### ISSUE TITLE
Parent element style leaks into ix-tooltip

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#1061]
### Prerequisites

- [X] I have not leaked any internal company information.
- [ ] I have not posted internal links or code snippets.

### What happened?

CSS style set on parent element leaks into ix-tooltip
![image](https://github.com/siemens/ix/assets/144789952/489715d4-3ff2-4225-9c4d-50922fbf55ac)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.3

### Code to produce this issue.

```shell
<div style={background-color: red}>
  <div id="1"></div>
  <ix-tooltip for="[id=1]">Example</ix-tooltip> <-- gets red background color
</div>
```

**Comment by ridvandmrc** [comment]
I think this is an expected behavior if you want to manage background you can have a look
https://stackblitz.com/~/edit/xnfrdi-qu2sx2

**Comment by TDaniel-evo** [comment]
I think you copied a wrong stackblitz link, this one doesn't have any ix-tooltip. Anyway, I thought that outer css should not leak into ix component's shadow root. It's a bit strange to me that when I use the ix-tooltip in a html table, the table's style applies to the ix tooltip and I have to "reset" the tooltip style to the original.

![image](https://github.com/siemens/ix/assets/144789952/b78e01f3-1283-47e1-96bb-fdc2de1693bf)


or maybe the ` .table>:not(caption)>*>*` selector is the problem

**Comment by matthiashader** [comment]
Could you give a little more information, I have tried to recreate it:
https://stackblitz.com/edit/p7ij6z?file=src%2Fapp%2Ftooltip.html,src%2Fstyles.css

**Comment by TDaniel-evo** [comment]
The documentation suggests that I should use "table" class in a table: https://ix.siemens.io/docs/controls/html-grid
If you add the "table" class to the table in the example you can see that the tooltip inside the table is losing it because this selector: `.table > :not(caption) > * > *` applies to the tooltip as well.
![image](https://github.com/siemens/ix/assets/144789952/4e934460-01dc-417a-90d5-3f1c259c8742)

**Comment by matthiashader** [comment]
Thank you very much, we will discuss this issue

Internal ref [IX-901]
