### ISSUE TITLE
Toast icons are not showing up after build stage

### ISSUE THREAD

**Issue by dogukan-duduoglu** [siemens/ix#1066]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

Neither the toast icon or the close(x) button show up after being build using vite. There are no problems on a local environment. There are no errors or warnings being thrown. This is how html elemnt and the the element itself looks like after build:
![image](https://github.com/siemens/ix/assets/158148112/a3a026e5-d355-4b43-a55d-a99254ece3d6)

![image](https://github.com/siemens/ix/assets/158148112/7b06f73b-99a4-4688-801b-b2800f89e912)

As a side note, I am using this workaround https://github.com/siemens/ix/issues/1006#issuecomment-1905253236 because toasts were not working at all before. As a result of this, this warning gets thrown:
![image](https://github.com/siemens/ix/assets/158148112/943042a2-1c8c-4e65-b3da-9a2eb96c81d3)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
showToast({
    autoCloseDelay: 10000,
    message: message,
    type: notification_type
})
```

**Comment by matthiashader** [comment]
Internal ref [IX-878]
