### ISSUE TITLE
IxGroup expander icon becomes hidden on specific conditions

### ISSUE THREAD

**Issue by adam-elias** [siemens/ix#1068]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

After the bug appears the icon gets the hidden class:
![image](https://github.com/siemens/ix/assets/71386774/031f4fd5-bba8-4ad0-a528-90b60aaef4b3)
![image](https://github.com/siemens/ix/assets/71386774/efe61cc2-5b3b-467f-9f43-bb46b15e444c)

Reproduction steps:
* open stackblitz example code
* wait until page loads up
* optionally expand the group or not
* click the reload button
* the expander button disappears

The expander icon is again visible if you click on the group. Otherwise the group seems to be in working order.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/ne22aj-evdeyj
```

**Comment by matthiashader** [comment]
Internatl ref [IX-889]

**Comment by danielleroux** [comment]
Fixed with next release https://github.com/siemens/ix/pull/1257 by PR https://github.com/siemens/ix/pull/1260
