### ISSUE TITLE
Select items inherit colour

### ISSUE THREAD

**Issue by JulianEvi** [siemens/ix#1073]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

Hi,

I noticed that the items in the select component inherit the colour from the surrounding container.
![image](https://github.com/siemens/ix/assets/147377383/872578b4-b47f-437e-a65c-0c9cdd8e9a61)

This requires manually applying the colour for each dropdown, if it is contained in a container that has a different colour.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
-
```

**Comment by matthiashader** [comment]
Internal ref [IX-894]
