### ISSUE TITLE
Slider: Tooltip not disappearing on outside click or hidden when moving the slider

### ISSUE THREAD

**Issue by JulianEvi** [siemens/ix#1083]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

Hi,

I observed two issues with the tooltip for displaying the currently selected value on the Slider component.

1. Sometimes the tooltip is still displayed after clicking multiple times outside of the component:
Here I already clicked multiple times on the empty part of the page below the sliders and the tooltip is still visible. Moving the slider fixes this behaviour.
![image](https://github.com/siemens/ix/assets/147377383/587ecc17-2199-4b49-b1b0-67e68150f509)

2. The tooltip completely disappears (also not visible while dragging the slider) and returns after clicking outside of the component and moving the slider again:
Here I moved the top slider without clicking on the empty part of the page and the tooltip was not visible while dragging the slider and in its final state.
![image](https://github.com/siemens/ix/assets/147377383/a1367b9a-66ce-4e88-a559-1698d12ae454)

I used the IX documentation page of the Slider in the examples. The issues appear a bit randomly, so I cannot provide concrete instructions on how to reproduce them.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
-
```

**Comment by matthiashader** [comment]
Thank you for providing your insights. Could you please confirm whether this issue persists in the latest version (v2.1.0)? I attempted to replicate the scenario using 2.1.0, and as of my testing, the issue no longer seems to be present.
Stackblitz: https://stackblitz.com/edit/5ykh7k?file=package.json%3AL18,package-lock.json

**Comment by matthiashader** [comment]
We will close this issue. If it still persists, don't hesitate to open a new issue!
