### ISSUE TITLE
Not getting the tooltip on the labels in the ix-menu-items

### ISSUE THREAD

**Issue by vipinmahajan02** [siemens/ix#1085]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

It is expected behavior that we should get the tooltip by default on the ix-menu items .But we are not getting the tooltip on the labels . And unable to find any property to add tooltip to it . 

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
<ix-menu-item icon="star" 
      (click)="navigateTo()"
     >
     Home
    </ix-menu-item>
```

**Comment by ridvandmrc** [comment]
you can try this.

`<ix-tooltip for=".target"> Navigate to Home </ix-tooltip>
<ix-menu-item class="target" icon="star"> Home </ix-menu-item>`

**Comment by vipinmahajan02** [comment]
@ridvandmrc I tried that but its look and feel is somewhat different from what the default tooltip on ix-menu-item have.

**Comment by matthiashader** [comment]
Internal ref [IX-896]

**Comment by vipinmahajan02** [comment]
Is there any update or fix regarding this issue ?

**Comment by matthiashader** [comment]
Hi @vipinmahajan02 - sorry for the late reply, this ticket is in our current scope and should be completed in the next 1 - 2 sprint accordingly

**Comment by matthiashader** [comment]
We will close this issue, #1327 still remains.
