### ISSUE TITLE
Title option for the drawer component

### ISSUE THREAD

**Issue by marcossiemens** [siemens/ix#1097]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### Suggestion / feature request

I'd like to have a title option for the drawer component. At the same line as the close button.

**Comment by matthiashader** [comment]
Thank you for your contribution, with version 2.1.0 we have added a new component called ix-pane which should fulfill your requirements. If you have any further questions, please do not hesitate to ask.
