### ISSUE TITLE
settings page title does not update (e.g. on language changes)

### ISSUE THREAD

**Issue by larshudalla** [siemens/ix#110]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When changing the language in the cui-settings-page the title does not update automatically
- cui version: 6.1.0
- npm version: 6.14.17
![cui_bug_language](https://user-images.githubusercontent.com/117283609/199496582-b0fd6f60-a586-4d96-b8a5-aa002990ee89.png)

## Expected behavior
The title of the cui-settings-page is updated according to changes in the input

**Comment by danielleroux** [comment]
@larshudalla Can not reproduce in ix release 1.1.0. Looks like you using a older version from ix (core-ui 6.1.0)

**Comment by nuke-ellington** [comment]
Closing stale issue that appears to concern Core UI not iX.
