### ISSUE TITLE
Ix-toggle is broken when change font-size

### ISSUE THREAD

**Issue by ridvandmrc** [siemens/ix#1111]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

When I change font-size with 14px for mobile view, ix-toggle is broken.

Actually problem is that rem unit has not been using for width and height.

please use rem unit instead of px. because it is relative unit .

![image](https://github.com/siemens/ix/assets/15720132/e7187b52-5695-4eed-b6a3-3b8a08386c31)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.1

### Code to produce this issue.

```shell
https://stackblitz.com/~/edit/xnfrdi-vsraje
```

**Comment by ridvandmrc** [comment]
it looks like:
![image](https://github.com/siemens/ix/assets/15720132/87cbcaff-8b52-455e-989a-7c8f7fec01c4)

**Comment by matthiashader** [comment]
Thanks for your insights - I have created a ticket for it, we will track it internally!
Internal ref [IX-953]
