### ISSUE TITLE
IxTooltip react component not working !

### ISSUE THREAD

**Issue by brkzr** [siemens/ix#1114]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

we updated our ix version from 2.0.4 to 2.1.0. After that, we started getting errors in tooltip components. 

![image](https://github.com/siemens/ix/assets/2824264/beb33dbb-3070-4373-bc8c-6c30034907ce)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/vitejs-vite-wuok6c?file=src%2FApp.tsx
```

**Comment by danielleroux** [comment]
Already found the problem, we are working on it. There will we patch during this day or on monday.

**Comment by danielleroux** [comment]
A fix for this issue is now available in v2.1.1-beta.0.
We kindly ask you to install this version in your dev environment to check if it resolves the problem for you and give us some feedback about this.

**Comment by muratayik** [comment]
Thanks for the fix. v2.1.1-beta.0 version works in our dev environment. Do you have a date for non-beta version publish?

**Comment by nuke-ellington** [comment]
@muratayik 2.1.1 is already available. We will release another patch (_v2.1.2_) later this week, though. Please keep an eye out for that.
