### ISSUE TITLE
IxTooltips no longer working

### ISSUE THREAD

**Issue by hoeflerjo** [siemens/ix#1120]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

Since Updating to the newest Ix Version all my tooltips broke. They now just show the content directly where the Tooltip component is placed in the JSX. So it is permanently visible and the Info bubble doesn't appear when hovering over it.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/github-qkkcjp?file=src%2FApp.tsx
```

**Comment by danielleroux** [comment]
Duplicated (https://github.com/siemens/ix/issues/1114) will close this one, hotfix is on the way.
