### ISSUE TITLE
(Dropdown) Datepicker date cannot be set after initialization

### ISSUE THREAD

**Issue by paul-schweng** [siemens/ix#1122]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

When using the (Dropdown) Datepicker you cannot set the [from] and [to] properties of the component after it has been initialized.
A change is detected when changing that property, but it seems that internally this value is not updated as the component emits an event which has the last selected date as the value.

Even when you set [from]=null you can see that the button of the Dropdown Datepicker still shows the selected date.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
<ix-date-dropdown [range]="false" [from]="selectedDate" (dateRangeChange)="onDateChange($event.detail.from)"></ix-date-dropdown>

<button (click)="setDatePicker()">Change Date</button>

selectedDate: string = null;
setDatePicker(){
  this.selectedDate = "2024/01/01";
}
```

**Comment by matthiashader** [comment]
Thanks for your input. We will have a look into it! Internal ref [IX-957]

**Comment by slymnozdmrc** [comment]
Hi,
When do you plan to release the version containing this fix? Could you provide a specific date for it? We have a release scheduled for April 15th and would like to know if we should wait accordingly or explore alternative options.
Thanks.

**Comment by network-interface-controller** [comment]
@matthiashader This issue hinders us from using the date filter, too. Since our customers request it, when can we expect a fix?

**Comment by matthiashader** [comment]
Hello @network-interface-controller , @slymnozdmrc - sorry for keeping you waiting, according to our release plan the next release should be the end of next week!

**Comment by slymnozdmrc** [comment]
Hello @matthiashader , Is there a change in the release plan? Accourding to your previous comment new release should have been completed last week. Could you give date for next relase please?

**Comment by matthiashader** [comment]
@slymnozdmrc sorry for these delays, i know it's a bit frustrating / annoying - we noticed some bugs before release that we are fixing now - but i can assure you that we will release this week for sure!

**Comment by slymnozdmrc** [comment]
Hi @matthiashader , Is there any update regarding the release date?
