### ISSUE TITLE
Dropdown doesn't work with virtual scroll, split button issue

### ISSUE THREAD

**Issue by petrakristova** [siemens/ix#1136]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

1. When using dropdown with virtual scroll, the positioning stops working properly. If you open dropdown inside virtual scroll viewport and scroll down, it stays in the viewport and jumps around. This happens for both id trigger and element trigger.
2. When dropdown for e.g. item 1 is open, you scroll down and select action in dropdown, it's bound with wrong data and action for e.g. item 100 is executed (you can try yourself in attached example where bound item is shown in dialog). Happens also for both id trigger and element trigger.
3. If id of specific element is used as dropdown trigger, it becomes very slow with all the query selectors if used inside real complex application (performance hit is really caused by that, if I remove dropdowns with id triggers, it works smoothly). Use case for this is the same as provided simplified example. When HTMLElement is used as dropdown trigger, performance is better but then the following problem comes in:
4. If HTMLElement used as dropdown trigger, sometimes it stops working inside virtual scroll viewport. Sometimes when you scroll down, no dropdown can be open, it just doesn't do anything when clicking the trigger. If you wait a bit (tens of seconds), it starts to work again.
5. There is a situation when split button stops to be reopenable. When there is some element with id "undefined" on the page (like dialog in the attached example), dropdown trigger for split button is mismatched with that element, `data-ix-dropdown-trigger` is added to that element (in our case `mat-dialog-container` ) and once that element disappears (dialog is closed), it's not possible to reopen dropdown from split button anymore. I know this is an edge case and there was also issue on our side but the mismatching of elements is probably something that should be handled. I didn't find a way how to set `id` for button which expands dropdown or it's missing in the documentation.
![image](https://github.com/siemens/ix/assets/64610674/ad54ec75-7b0a-48f1-9098-a9eb53d36530)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/stackblitz-starters-dkx6p4
```

**Comment by petrakristova** [comment]
Maybe one thought regarding virtual scroll since it can get pretty tricky to handle. I also tried behavior of [angular material menu](https://material.angular.io/components/menu/overview) and there when you open a dropdown inside virtual scrolling viewport, scrolling gets blocked. Once the dropdown is closed again, scrolling gets enabled. Could be possible solution for that.

**Comment by matthiashader** [comment]
Thanks for your insights. We will have a look into this strange behavior in an upcoming sprint.
Internal ref [IX-991]

**Comment by matthiashader** [comment]
Hello @petrakristova - i was able to fix to fix the most of your issues. But some of them are not recreatable for me, even in the stackblitz. So far we have decided to close the dropdown when the original icon button is detached from the DOM, this prevents the dropdown from jumping around and also prevents the dropdown from performing the wrong action. However, could you explain in more detail how the performance is affected (especially with a example) and maybe provide a short video when the element trigger is not working?
