### ISSUE TITLE
generic shadow

### ISSUE THREAD

**Issue by danielleroux** [siemens/ix#114]
## I'm submitting a...

<pre><code>
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Library does not provide generic shadows like in coreui.

**Comment by danielleroux** [comment]
@silviowolf Do we can provide basic shadows like bootstrap do? (https://getbootstrap.com/docs/5.2/utilities/shadows/)

**Comment by danielleroux** [comment]
@silviowolf sounds good! 

Maybe we should add this also for the borders? 

/cc @nuke-ellington

**Comment by silviowolf** [comment]
@danielleroux, let's discuss the border thing in the next JF.
Regarding the shadows, I'll send you a spec with all values.

**Comment by danielleroux** [comment]
# JourFix 17.11.2022

- only add shadow levels as mixin/helper class
-

**Comment by silviowolf** [comment]
border and shadow variables will be introduced with version 1.4.0

**Comment by silviowolf** [comment]
- design for presentation in documentation is in work
