### ISSUE TITLE
Tooltip for selector is not properly working on Navigation Menu

### ISSUE THREAD

**Issue by umar-shabbir** [siemens/ix#1140]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

The CSS selector for showing tooltip is not properly working. I am trying to show tooltip on the menu items only when the navigation menu is collapsed. 
When menu is expanded, there is a `.expanded` class on `IxMenu`. This class cannot be used to activate the tooltip using `for` prop of the `IxTooltip`. If it works, applying `:not` should work for showing tooltips only for collapsed menu items.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.1.1

### Code to produce this issue.

[Github](https://github.com/umar-shabbir/ix-issue-1140)

**Comment by matthiashader** [comment]
Hello @umar-shabbir - sorry for the late answer, currently there is a ongoin ticket in our sprint that will solve this issue! Secondly as you pointed out it is not possible to actually target a shadow element, but we are currently also working on a solution regarding the default usage of ix-tooltips and plain HTML-tooltips.

**Comment by matthiashader** [comment]
We will close this issue. If it still persists, don't hesitate to open a new issue!
