### ISSUE TITLE
Event list item does not support transparent itemColor

### ISSUE THREAD

**Issue by SerenaDominic** [siemens/ix#1148]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

ix design system supports event list without any itemColor, ie. transparent itemColor. In the implementation, there is no way to achieve this. We could get around it by providing` itemColor =  unset`, but then the **selection border is not applied to the left hand side** of the event list item, where itemColor is expected.

![image](https://github.com/siemens/ix/assets/28972606/c721e7b4-8d5e-4eb0-8d6d-ee4e245170e6)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/nztnbv-2w98qk?file=src%2Fapp%2Fevent-list-example.html
```

**Comment by matthiashader** [comment]
Thanks for your insights, currently this suggestion is already in our backlog. As this is a duplicate i will close this ticket - if you have any further question dont hesitate to ask
