### ISSUE TITLE
Modal Dialog fires dismiss on close

### ISSUE THREAD

**Issue by ThomasPoenicke** [siemens/ix#1149]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

When closing a Modal Dialog using IxActiveModal.close(reason) method, a dismiss event is fired additionally.
This leads into unexpected behavior as the dismiss event is also subscribed.

The stackblitz example shows, that closing a modal dialog (by x, cancel, ok) leads into 2 events, where the second event is always 'dismiss'.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/k5zpnl-dgfcmz
```

**Comment by matthiashader** [comment]
Thanks for your report we will have a look into it! Internal ref [IX-985]
