### ISSUE TITLE
Chip is larger with outline property

### ISSUE THREAD

**Issue by davidrigo** [siemens/ix#1161]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

The chip becomes larger if the outline property is true.
Expectation: the outline property should not reflect to the size of the chip

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
<ix-chip outline> Outline </ix-chip>
<ix-chip> Without outline </ix-chip>
```

**Comment by davidrigo** [comment]
Hello @matthiashader 
I have created an example: https://stackblitz.com/edit/nvtbs5-oub67n?file=src%2Fapp%2Fchip.ts
If you click on the Open chip, it becomes larger (outline property is true), and if you click on again, it becomes smaller (outline property is false).

**Comment by matthiashader** [comment]
Hello @davidrigo - thanks for clarification, i thought you are meaning the height, but you are right this is not wanted behavior, i will create a bug ticket for this!
