### ISSUE TITLE
IxBlind label is not  shortened via ellipsis or wrapped

### ISSUE THREAD

**Issue by muratayik** [siemens/ix#1165]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

**What happened?**

When I use a long string for label, the string is not shortened via ellipsis or wrapped. I can not see the remaining part of label.

![image](https://github.com/siemens/ix/assets/10512262/b7141cbf-0a7f-4542-b358-1f26ed6aaf7b)

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.1.1

### Code to produce this issue.

```shell
<IxBlind icon="warning"  variant="warning" label="A long asset name that does not fit to blind header">
</IxBlind>
```

**Comment by ridvandmrc** [comment]
Hi @muratayik ,
Maybe you can use this workaround solution,

```html
    <ix-blind icon="warning"  variant="warning">
      <p style=" color:black; font-size:14px; font-weight:bold; overflow:hidden; max-width:80%; text-overflow:ellipsis; white-space:nowrap" slot="custom-header">  A long asset name that does not fit to blind header </p>
    </ix-blind>
```

And the result will be like:
![image](https://github.com/siemens/ix/assets/15720132/bc6eb378-f832-410e-a8a3-74ffc38e6ae3)
