### ISSUE TITLE
Programmatically reset ix-date-picker selection

### ISSUE THREAD

**Issue by karakuz** [siemens/ix#1166]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Add ability to reset date selections on ix-date-picker programmatically

For instance if user selected 23rd of March previously and when we need to reset form inputs programmatically, we need to reset date picker to default version as well(without having previous date as marked - 23rd of March in this case)

![image](https://github.com/siemens/ix/assets/31669352/e71d1087-4a7a-433a-b9e9-a0cc0eb9cfcd)

**Comment by matthiashader** [comment]
Thanks for your input! Currently you can reset the date if you set 'from' to null or ''. I have prepared a small example here: 
https://stackblitz.com/edit/s92ja4?file=src%2Fdatepicker-range.tsx - If you have any further questions, don't hesitate to ask.

**Comment by karakuz** [comment]
got it, thanks for code 👍
