### ISSUE TITLE
ix-select dropdown is not closing when click on dropdown icon

### ISSUE THREAD

**Issue by JagadishNM** [siemens/ix#1174]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

ix-select dropdown is not closing when click on dropdown icon

[stack blitz link](https://stackblitz.com/edit/xnfrdi-4cqhsc?file=package.json)

![image](https://github.com/siemens/ix/assets/91608364/95d7cd09-edc9-454c-adc7-8d6b87742390)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

V2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/xnfrdi-4cqhsc?file=package.json
```

**Comment by matthiashader** [comment]
Hello @JagadishNM - thanks for your insights! Please try updating you iX version to at least 2.1.0, as this problem has been resolved there. https://stackblitz.com/edit/xnfrdi-4cqhsc?file=package.json
