### ISSUE TITLE
Event list sometimes stops responding to mouse hover and clicks when adding elements after a modal is closed

### ISSUE THREAD

**Issue by raphaelgodart** [siemens/ix#1179]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

In one of our Angular projects, we're using the Event list component as follows. An 'Add' button opens a modal in which a name must be provided. After closing the modal, an event list item using the provided name is added to the event list.

In some instances, after performing the above procedure and after the modal is closed, the event list is not responding to mouse hover and mouse clicks anymore.

Unfortunately, this bug does not happen everytime. Sometimes, it happens only after adding multiple items. Sometimes it doesn't occur at all. The attached video illustrates the problem. When adding items 1 and 2 there is no problem. As seen in the video, the event list is still responding to mouse hover an clicks. After adding item 3 however, the event list does not respond to mouse hover and clicks anymore.

As also seen in the video, after opening a modal again and dismissing by pessing 'Cancel', the event list responds to mouse hover and clicks again. The bug was reproduced in Google Chrome. This is the video:

https://github.com/siemens/ix/assets/164166687/bb4df8d8-3df3-44ac-80d7-a9a589a4f0ac

This Stackblitz has the reproduction project which was used in the video:

https://stackblitz.com/edit/siemens-ix-event-list-bug-repro

This bug seems related to the modal. When adding items to the list without using a modal (e.g. by providing a hardcoded name), this bug does not occur.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.2

### Code to produce this issue.

```shell
https://stackblitz.com/edit/siemens-ix-event-list-bug-repro
```

**Comment by benvla** [comment]
I have found an interesting work-around for this issue. Removing the '[Animate state change transitions](https://ix.siemens.io/docs/controls/event-list#props)' seems to solve the issue.

In the provided example, change

``` typescript
<ix-event-list class="m-2">
```
into
``` typescript
<ix-event-list class="m-2" animated="false">
```
