### ISSUE TITLE
Navigation menu tooltip issue

### ISSUE THREAD

**Issue by praveenn16** [siemens/ix#1180]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Hi Team, 

Unable to see any tooltip on hover on navigation menu.

Expectation - Able to see menu name inside tooltip when navigation bar is collapsed
![titleIssue](https://github.com/siemens/ix/assets/156085957/866aa2ef-53ae-432f-b3ce-68cd57238c05)

Kindly help to suggest on the same.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.1.2

### Code to produce this issue.

```shell
<ix-menu>
  <ix-menu-item home-tab tab-icon="home"> Home </ix-menu-item>
  <ix-menu-item tab-icon="globe"> Normal Tab </ix-menu-item>
  <ix-menu-item tab-icon="star" disabled> Disabled Tab </ix-menu-item>
</ix-menu>
```

**Comment by matthiashader** [comment]
Hello @praveenn16 - thanks for your insights. This issue has already been reported and currently we are working on it. As this is a duplicate i will close this issue.
