### ISSUE TITLE
Card list ShowAll button cannot be hidden

### ISSUE THREAD

**Issue by tillmos** [siemens/ix#1181]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

The card list elements Show all button cannot be hidden.
![image](https://github.com/siemens/ix/assets/80476903/4c44e925-f265-4e2f-a8d1-e1ff49809076)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.1.0

### Code to produce this issue.

```shell
<ix-card-list class="assistance-card-list" label="Lorem ipsum" list-style="scroll">
    <ix-push-card
      class="second-row-card"
      variant="alarm"
      collapse="true"></ix-push-card>
    <ix-push-card>
 </ix-card-list>
```

**Comment by ridvandmrc** [comment]
Hi @tillmos 
you can use this solution as a workaround.
```html 
<ix-card-list class="assistance-card-list" label="Lorem ipsum" list-style="scroll" i18nShowAll="" [showAllCount]="'null'">
  <ix-push-card
    class="second-row-card"
    variant="alarm"
    collapse="true">
</ix-push-card><ix-push-card
class="second-row-card"
variant="alarm"
collapse="true">
</ix-push-card>
</ix-card-list>
```

here is the result,
![image](https://github.com/siemens/ix/assets/15720132/1192172f-367b-4fb2-ae81-2bd567ccc0ed)

**Comment by matthiashader** [comment]
Hello @tillmos - thanks for your insights! We are currently working on a solution for this kind of issue!

**Comment by danielleroux** [comment]
Can be configured with the latest release.
