### ISSUE TITLE
Documentation landing page incorrect responsive layout

### ISSUE THREAD

**Issue by goncalosard** [siemens/ix#1187]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Hello everyone!

While checking the documentation on my laptop, since the changes on the landing page, the first block with the new position of buttons is broken.
![image](https://github.com/siemens/ix/assets/63813420/c2eb6b88-715b-446a-96d1-7a24114461e5)

To fix it,  you can add "min-height: 840px;" on the industrial_experience div.

Many thanks.

**Comment by nuke-ellington** [comment]
This should be addressed via #1144
