### ISSUE TITLE
Cannot hide push cards drawer

### ISSUE THREAD

**Issue by tillmos** [siemens/ix#1188]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

There is no possibility to remove the Push cards opening drawer, if there is no content in it.
![image](https://github.com/siemens/ix/assets/80476903/01fc2677-e7f0-44c2-946f-7e3062e54561)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.1.0

### Code to produce this issue.

```shell
<ix-push-card
      class="second-row-card"
      icon="alarm-bell"
      notification="2"
      heading=""
      subheading=""
      variant="alarm"
      collapse="true"
      ></ix-push-card>
```

**Comment by matthiashader** [comment]
Hello @tillmos - thanks for your insights! Currently we already have a ticket in the sprint that will resolve this issue!

**Comment by aniketkumar7** [comment]
We could use the *ngIf directive to conditionally render the ix-push-card component based on whether there's content to display. 



<ix-push-card

**Comment by danielleroux** [comment]
There will be no prop directly to configure the card, but you can build the your custom card based on the example in the documentation: https://ix.siemens.io/docs/controls/card (on the bottom of the dev tab)
