### ISSUE TITLE
Submenu items icons can be removable

### ISSUE THREAD

**Issue by gdilarainann** [siemens/ix#1193]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

As you can see below, submenu items have icons. These icons cannot be removed. (Log settings, back up and restore..). We want to remove these for our project.

![image](https://github.com/siemens/ix/assets/166024765/7abbb75a-56de-4fe7-8204-1b089133b95e)

**Comment by danielleroux** [comment]
Already fixed with https://github.com/siemens/ix/pull/1110. Will be part of next release.
