### ISSUE TITLE
Ix-workFlow steps having fixed width

### ISSUE THREAD

**Issue by MaheshKumarZ004p31p** [siemens/ix#1194]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Hi Team,

In Ix-workFlow steps, In below UI, we need to provide the width till the end of that white card. But we can't able to increase/alter the width of ix-workflow steps. So what will be the recommended solution for this? 

 

Do we need to decrease the white card width or is there a way to increase the width of the workflow step?

![image](https://github.com/siemens/ix/assets/165240935/3d4451b3-2af4-44bb-a42d-443519b0b93d)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
<ix-workflow-steps vertical>
    <ix-workflow-step status="done">Sample text 1</ix-workflow-step>
    <ix-workflow-step status="success">Sample text 2</ix-workflow-step>
    <ix-workflow-step status="open">Sample text 3</ix-workflow-step>
    <ix-workflow-step status="warning">Sample text 4</ix-workflow-step>
  </ix-workflow-steps>
```

**Comment by matthiashader** [comment]
Hello @MaheshKumarZ004p31p - thanks for your insights, currently we are working on a quite similar issue in the sprint - there we will also take your needs into account.
