### ISSUE TITLE
Show submenu on hover

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#1204]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Currently the submenu in the menu is only visible if you click it. If the submenu is used in a collapsed state to create for the main region more space it is not really visible that there is an submenu available, customers have to know that they click the reflective item.

Example:
![image](https://github.com/siemens/ix/assets/109066516/ca70137b-9637-4059-906a-8a2bb47a1d56)

![image](https://github.com/siemens/ix/assets/109066516/b743c6b3-d5bb-40dc-9565-840888182397)

**Comment by HemendraSinghRathore** [comment]
+1 I am facing same issue.

**Comment by neunteufelflorian** [comment]
+1

**Comment by danielleroux** [comment]
Part of the 2.2.1 release https://github.com/siemens/ix/pull/1242
