### ISSUE TITLE
 IxGroupItem should have pointer cursor

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#1207]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I think cursor should be adjusted for group items to match it's purpose (as a link to sub item, esp. when using button element inside). The only exception is when group item is set as inactive (by supressSelection prop).

Current wrong behavior:

![group-item-cursor-wrong](https://github.com/siemens/ix/assets/99844553/08443896-5ad7-4602-9070-b6a545e42a03)

Correct behavior:

![group-item-cursor-correct](https://github.com/siemens/ix/assets/99844553/e115fa37-3ec7-41c7-8e62-57f5ac4a3585)

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.1.2

### Code to produce this issue.

```shell
<IxGroup header="Group header" subHeader="Group subheader">
	<IxGroupItem text="Group item 1" />
	<IxGroupItem text="Group item 2" />
	<IxGroupItem text="Group item 3" />
</IxGroup>
```

**Comment by danielleroux** [comment]
Will be part of the next release https://github.com/siemens/ix/pull/1257 (after PR is merged)
