### ISSUE TITLE
ix-select does not disable

### ISSUE THREAD

**Issue by marcossiemens** [siemens/ix#1215]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Using Angular, I'm trying to disable ix-select by putting `<ix-select [disabled]="true">`, and it simply doesn't work. I can still type in it and select options.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
<ix-select [disabled]="true"><\ix-select>
```

**Comment by matthiashader** [comment]
Hello @marcossiemens thanks for your insights! Could you provide a little bit more detail, or prepare a stackblitz with your issue. I have tried recreating it, but it seems just fine: https://stackblitz.com/edit/wpumxs?file=src%2Fapp%2Fselect.ts,package.json

**Comment by nuke-ellington** [comment]
Closed due to inactivity. Please reopen in case issue persists.
