### ISSUE TITLE
How to showToast above a Modal

### ISSUE THREAD

**Issue by Hallo2World** [siemens/ix#1253]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

showToast  API  support to showToast above a Modal

**Comment by matthiashader** [comment]
Duplicate #798
