### ISSUE TITLE
Button inside shadow-root is not disabled

### ISSUE THREAD

**Issue by petrakristova** [siemens/ix#1259]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

If `ix-button` or `ix-icon-button` is disabled, `button` element inside `shadow-root` is enabled. I would expect it also to be disabled.

![image](https://github.com/siemens/ix/assets/64610674/a7dde374-6649-4c66-b53b-245cbfcb225f)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.2.1

### Code to produce this issue.

```shell
<ix-button disabled class="m-1">Disabled button</ix-button>
<ix-icon-button icon="info" variant="Primary" disabled class="m-1"></ix-icon-button>
```

**Comment by danielleroux** [comment]
@petrakristova why do you expect this?

**Comment by petrakristova** [comment]
Because if assistive reader or test framework gets the button, it gives you false reading of the disabled state.
