### ISSUE TITLE
Category Filter | There is no way user can edit selected value for the category

### ISSUE THREAD

**Issue by Jayesh26** [siemens/ix#1267]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Once user has selected value for category then there is no way to edit the value by removing just value.
User need to remove the complete category and then only he/she can choose new value. 

There is  little inconvenience as when user has multiple categories added in category filter and wants to change value of the first category then he have to remove all the category and add again with required value 

![image](https://github.com/siemens/ix/assets/3745459/a9955dbb-d7d3-45fc-a799-f226eda6dfe6)

**Comment by matthiashader** [comment]
Hello @Jayesh26 - thanks for your insights!
Currently we are not planning such a feature.
