### ISSUE TITLE
Modal message position

### ISSUE THREAD

**Issue by dorareviczki** [siemens/ix#1272]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

On the IAI Portfolio project we would like to place the modal message component in the middle of the screen, however this is currently not possible as we cannot change its position due to the shadow root and we couldn't find a solution for this in the documentation.

**Comment by nuke-ellington** [comment]
Duplicate already tracked via #1071

**Comment by nuke-ellington** [comment]
@dorareviczki on a second note: there already is an option `centered` in [`ModalConfig`](https://ix.siemens.io/docs/controls/modal#modal-config) that will center the modal vertically.
