### ISSUE TITLE
ix-menu-item bottom property does not work

### ISSUE THREAD

**Issue by philippsteinberg** [siemens/ix#128]
## I'm submitting a...

<pre><code>
[ x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I want to add menu items that are shown add the bottom.  
For this I found a promising bottom property in the documentation. https://ix.siemens.io/docs/controls/navigation/vertical-tabs#props-1  
Unfortunately the menu items with that property are hidden and not shown on the bottom

## Expected behavior
When I create a ix-menu-item with the property bottom="true" it should be shown at the bottom of the menu

## Minimal reproduction of the problem with instructions
The bottom menu entry is not shown
```
  <ix-basic-navigation>
    <ix-menu>
      <ix-menu-item home="true">Home</ix-menu-item>
      <ix-menu-item>Item 1</ix-menu-item>
      <ix-menu-item>Item 2</ix-menu-item>
      <ix-menu-item bottom="true"></ix-menu-item>
      <ix-menu-about>
        <ix-menu-about-item label="Tab 1">Content 1</ix-menu-about-item>
      </ix-menu-about>
    </ix-menu>
  </ix-basic-navigation>
```
![grafik](https://user-images.githubusercontent.com/117842757/200874426-31a63680-bc52-4c03-9f50-4375664cafd8.png)

**Comment by danielleroux** [comment]
@philippsteinberg Looks like this is a feature which were refactored, but not cleaned up afterwards. But we will investigate.

A possible workaround will be to use the `slot` attribute. e.g. ` <ix-menu-item slot="bottom" tabIcon="rocket">Test 4</ix-menu-item>`

```html
        <ix-basic-navigation>
          <ix-menu>
            <ix-menu-item tabIcon="rocket">Test</ix-menu-item>
            <ix-menu-item tabIcon="rocket">Test 2</ix-menu-item>
            <ix-menu-item tabIcon="rocket">Test 3</ix-menu-item>

            <ix-menu-item slot="bottom" tabIcon="rocket">
              Test 4
            </ix-menu-item>

            <ix-menu-about></ix-menu-about>
            <ix-menu-settings>
              <ix-menu-settings-item label="Test">Test</ix-menu-settings-item>
            </ix-menu-settings>
          </ix-menu>
        </ix-basic-navigation>
```
