### ISSUE TITLE
Traffic Light Component

### ISSUE THREAD

**Issue by mtcetin9** [siemens/ix#1284]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

We have a traffic light design that we use to indicate health status of signals on some of our pages. This is our own design, and its used in different formats such as vertical or horizontal, with a single column or with multiple columns across our pages. I've shared images of traffic light design that we've created below. 
We need a dynamic traffic light component which allows us to arrange some features of it like 
- Adding header to each rows & columns
- Adding icons or tooltips for the items  
- Adjusting traffic light component vertically or horizontally

Could you please create a component like this for us?
We would be very grateful if you could consider our request.

Best regards,

Ps. You can reach [meryem.aruntas@siemens.com](mailto:meryem.aruntas@siemens.com) for the detail information about our request.

<img width="1233" alt="Traffic_Lights" src="https://github.com/siemens/ix/assets/151855087/f47125e5-6a9e-4837-945a-ec9b5bcf9042">

**Comment by silviowolf** [comment]
Clarifying via pm
