### ISSUE TITLE
Unable to test iX component using React Testing Library and Jest

### ISSUE THREAD

**Issue by umar-shabbir** [siemens/ix#1288]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

UI testing of iX components is not working with React Testing Library and Jest.
For example, testing text displayed by `IxContentHeader` did not work and produces following error:
`TestingLibraryElementError: Unable to find an element with the text: `

After following instructions in code to produce this issue, you can see that:

- Test case on text displayed with `IxContentHeader` is failed
- Test case on text displayed with `IxTypography `is passed

![image](https://github.com/siemens/ix/assets/48724934/46092de7-7060-4e69-a313-09b68b413c84)

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.2.1

### Code to produce this issue.

1. Clone [https://github.com/umar-shabbir/ix-issue-1288](https://github.com/umar-shabbir/ix-issue-1288)
2. Run `npm install`
3. Run `npm test`

**Comment by danielleroux** [comment]
We are using the same test setup maybe this helps you to get your tests running: https://github.com/siemens/ix/blob/main/packages/react/src/tests/toast/toast.spec.tsx

or

```ts
import { render, waitFor } from '@testing-library/react';
import React from 'react';
import { describe, it } from 'vitest';
import { deepQuerySelector } from 'shadow-dom-testing-library';
import { IxContentHeader } from '../..';

describe(`content-header`, async () => {
  it(`basic`, async () => {
    const page = render(
      <>
        <IxContentHeader
          headerTitle="Content Header"
          headerSubtitle="My Subtitle"
        >
          Custom Content
        </IxContentHeader>
      </>
    );

    await waitFor(() =>
      expect(deepQuerySelector(page.container, '.subtitle')).toBeInTheDocument()
    );
    expect(deepQuerySelector(page.container, '.subtitle')?.innerText).toEqual(
      'My Subtitle'
    );
  });
});

```

Please check your [testing environment](https://github.com/testing-library/dom-testing-library/issues/413), the react components are no pure react components the use web components to render the content. You have to [pierce through this layer](https://www.npmjs.com/package/shadow-dom-testing-library) IMO it is not necessary to test the internals of the ix components this should not be a part of your unit test.

**Comment by matthiashader** [comment]
We will close this issue. If it still persists, don't hesitate to open a new issue!
