### ISSUE TITLE
Slider Component is throwing error while using in React app

### ISSUE THREAD

**Issue by umadevipalla5** [siemens/ix#1289]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach')

![image](https://github.com/siemens/ix/assets/170500406/d28e9197-b085-4db2-8b6d-f30ce0131c0a)

[example ](https://stackblitz.com/run?file=src%2Fslider.tsx)

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.2.0

### Code to produce this issue.

```shell
https://stackblitz.com/run?file=src%2Fslider.tsx

In Siemens IX offical documentation stackbliz example for react having this issue
```

**Comment by danielleroux** [comment]
Duplicated issue #1249. Fix part of next release.
