### ISSUE TITLE
<ix-tile> enable custom size

### ISSUE THREAD

**Issue by intuiquest** [siemens/ix#1301]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

iX Tiles have a fixed width, making them inconvenient to use in a responsive grid (display: grid). It would be beneficial if the component provided an option such as size="custom" for this use case. Currently, I have to override the following properties:

```
ix-tile {
  min-width: unset;
  max-width: unset;
  width: unset;
}

```

**Comment by matthiashader** [comment]
Hello @intuiquest ! 
Thanks for your inights, tiles are designed to have a fixed width, so either choose your approach with just overriding the width, or use the more flexible ix-card-component (which i would suggest).

**Comment by matthiashader** [comment]
We will close this issue. If it still persists, don't hesitate to open a new issue!
