### ISSUE TITLE
`iconColor` property in `IxIconButton` does not work

### ISSUE THREAD

**Issue by mohitmutha** [siemens/ix#1315]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Adding the `iconButton` property has no effect

Sample code
https://stackblitz.com/edit/d4xfdr?file=src%2Fbutton-with-icon.tsx

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.x

### Code to produce this issue.

```shell
https://stackblitz.com/edit/d4xfdr?file=src%2Fbutton-with-icon.tsx


<IxIconButton
          variant="secondary"
          iconColor={'blue'}
          icon="info"
        ></IxIconButton>
```
```

**Comment by nuke-ellington** [comment]
Hello @mohitmutha, thank you for reaching out.

The icon property only accepts [iX color names](https://ix.siemens.io/docs/theming/colors).

Please note that you should omit the "`--theme`" prefix.
So for example if you wanted to use "`--theme-color-ghost`" just type `iconColor="color-ghost"`.
