### ISSUE TITLE
Icon on Content header

### ISSUE THREAD

**Issue by hoeflerjo** [siemens/ix#1321]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Add the possibility to change the icon for the back button on the content header for more customization of the content header.
![image](https://github.com/siemens/ix/assets/69482876/d46f74d3-2309-4796-934c-bfea95ad73e5)

**Comment by matthiashader** [comment]
Hello @hoeflerjo ! Thanks for your insights! 
The component you refer is the 'back-button', another icon wouldn't make much sense in there.
