### ISSUE TITLE
<ix-icon> color property is not working

### ISSUE THREAD

**Issue by csanadEvo** [siemens/ix#1323]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

The **color** property of the ix-icon component (and **iconColor** / **color** property of the ix-icon-button component) is not working. :(

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0

### Code to produce this issue.

```shell
<ix-icon name="info" color="'#fff'"></ix-icon>
<ix-icon-button icon="cycle" iconColor="#fff" ghost></ix-icon-button>
```

**Comment by danielleroux** [comment]
Only predefined colours are working https://github.com/siemens/ix/issues/1315#issuecomment-2160996505
