### ISSUE TITLE
Third-level navigation to the navigation menu component

### ISSUE THREAD

**Issue by mtcetin** [siemens/ix#1340]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Is it possible to add a third-level navigation to the navigation menu component? As shown in the picture below, we need to display a subcategories under Submenu item(s) 1/2/3/4.

You can reach [meryem.aruntas@siemens.com](mailto:meryem.aruntas@siemens.com) for the detail information about our request.

![navigation_menu](https://github.com/siemens/ix/assets/32229860/5e4b6441-c012-497a-be1a-020caaba9aca)

**Comment by danielleroux** [comment]
thank you for your question. There are no plans for third level here as it will get unhandy, e.g. indicating the selected state in the expanded menu. You might consider using other navigational components such as tabs or a tree outside the menu.
