### ISSUE TITLE
Hard to see active tab

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#1341]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

We have implemented the Tabs provided by iX but I as UX designer get very often the feedback that it is really hard to see which tab is currently active/selected.

See:
![image](https://github.com/siemens/ix/assets/109066516/fcdb0677-43a5-4534-b7b6-e72d829015dc)

Proposal from my side: 
Add color-ghost--selected background color if tab is selected; I have introduced this color as selected color whenever the user selects something. I did user tests with your suggested colors (eg.: component-1--active) but the difference is too less and its not visible/recognizable.
Example:
![image](https://github.com/siemens/ix/assets/109066516/1261e192-2c6e-4a2b-9076-cc26cacb6166)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.2.0

### Code to produce this issue.

```shell
<ix-tabs [selected]="selectedTab">
        <ix-tab-item (click)="changeTab(0)">Tab 1</ix-tab-item>
        <ix-tab-item (click)="changeTab(1)">Tab 2</ix-tab-item>
        <ix-tab-item (click)="changeTab(2)">Tab 3</ix-tab-item>
      </ix-tabs>
```

**Comment by nuke-ellington** [comment]
Duplicate #1245
