### ISSUE TITLE
IX Ag grid( ag-grid-community) version upgradation

### ISSUE THREAD

**Issue by nitingondule-xdt** [siemens/ix#1345]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Currently I am integrating the AG Grid (https://ix.siemens.io/docs/controls/grid) component with my application, I discovered that there is a dependency on an older version of the program (ag-grid-community).

I'm using the most recent versions of ag-grid-react and ag-grid-community, and I'm having some issues with the ix-aggrid version while using this.

**Exception while installing packages:**
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: frontend@1.0.0
npm error Found: ag-grid-community@31.3.2
npm error node_modules/ag-grid-community
npm error   ag-grid-community@"^31.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer ag-grid-community@"^28 || ^29 || ^30" from @siemens/ix-aggrid@2.1.3
npm error node_modules/@siemens/ix-aggrid
npm error   @siemens/ix-aggrid@"^2.1.3" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

**Comment by danielleroux** [comment]
duplicated of #1131
