### ISSUE TITLE
Camel case events

### ISSUE THREAD

**Issue by kennycallado** [siemens/ix#1358]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

Would it be possible to enhance the components for better integration with [htmx](https://htmx.org) by triggering events in kebab-case? This would allow events to be captured with `hx-on:value-change="console.log('Hello, world!')"`.

Since version 2.0, `hx-on="valueChange: console.log('¡Hola, mundo!')"` has been deprecated, as per the [hx-on](https://htmx.org/attributes/hx-on) documentation.

Thanks for your such a great library.

**Comment by danielleroux** [comment]
Hi @kennycallado 

we can not do that this will have a major impact of the library and all other users but i checked the htmx documentation how did you come to the conclusion that the event syntax will be deprecated?
