### ISSUE TITLE
Remove trace reference from IxSlider

### ISSUE THREAD

**Issue by hawacodes** [siemens/ix#1361]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Hi IXTeam,
Is it possible to remove trace reference(vertical line) from the Slider? 
This is what we have:
![image](https://github.com/siemens/ix/assets/46366950/1d6f10ed-fafe-4536-af8f-a841a821604c)
This is what we want:
![image](https://github.com/siemens/ix/assets/46366950/b9694a17-8bc5-4b98-bf22-1d617f3756d4)

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.3.0

### Code to produce this issue.

```shell
<IxSlider
     min={0}
     max={50}
     trace
>
  <span slot='label-start'>0</span>
  <span slot='label-end'>50</span>
</IxSlider>
```

**Comment by nuke-ellington** [comment]
Tracked by [IX-1440]
