### ISSUE TITLE
About and legal overlay | "activeTabLabel" 

### ISSUE THREAD

**Issue by praveenn16** [siemens/ix#1388]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

"activeTabLabel" seems not working as expected.

Attribute: active-tab-label

Wanted Tab 2 to be selected by default in the below given Code Snippet. 

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.4.0

### Code to produce this issue.

```shell
<ix-application>
<ix-application-header>
<div class="placeholder-logo" slot="logo"></div>
</ix-application-header>
<ix-menu #menu>
<ix-menu-about [activeTabLabel]="'Tab 2'" >
<ix-menu-about-item label="Tab 1">Content 1</ix-menu-about-item>
<ix-menu-about-item label="Tab 2">Content 2</ix-menu-about-item>
</ix-menu-about>
</ix-menu>
</ix-application>
```

**Comment by nuke-ellington** [comment]
Duplicate #1182
