### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#1392]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### Suggestion / feature request

We need an icon for starting the update process of an application or firmware. Currently we are using the refresh/replace icon, but this is confusing our customers.

**Comment by silviowolf** [comment]
@katjaKoppensteiner I will contact you to discuss the details.

**Comment by silviowolf** [comment]
[ix-1515]

**Comment by silviowolf** [comment]
![image](https://github.com/user-attachments/assets/64d212f8-8fda-4aee-ae04-f46e5c1cbdae)

Icon has been added to icon repository branch https://github.com/siemens/ix-icons/tree/add-and-update-icons, will be available with next icon repository release.
