### ISSUE TITLE
In ix-about property "show" does not work

### ISSUE THREAD

**Issue by olenaMokhnatska** [siemens/ix#1393]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

![about](https://github.com/user-attachments/assets/5f5b6d41-a45b-4b52-81c0-f9053df3f15f)
<ix-menu-about _ngcontent-ng-c3389718412="" ng-reflect-show="true" slot="ix-menu-about" class="show hydrated">
Also that show does not work for the first time, need to open manually and then it's possible from dev tools toggle it 

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.0

### Code to produce this issue.

```shell
<ix-menu-about [show]="true"> </ix-menu-about>
```

**Comment by nuke-ellington** [comment]
Hello @olenaMokhnatska, `show` is marked as `internal` and therefore not part of the public API of the `ix-menu-about` component.
