### ISSUE TITLE
Category filter for clear icon

### ISSUE THREAD

**Issue by pavan6014** [siemens/ix#1400]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Select the category don't select any value, click on clear icon button, not clearing the category item from search.

![image](https://github.com/user-attachments/assets/4830a354-9fec-405e-9669-f00207bf9c2b)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
1) Lets take category example from https://ix.siemens.io/webcomponent-examples/dist/preview-examples/category-filter.html?theme=theme-brand-dark, 
2) Category filter that have categories like 'vendor' and 'product' 
3) Select the one of the category, don’t select the value
4) click on clear icon button, not clearing the category item from search.

5) Kindly refer https://community.siemens.com/t/category-filter-for-clear-icon/1709
```

**Comment by nuke-ellington** [comment]
Duplicate issue #1268
