### ISSUE TITLE
Angular 17 does not have module file by default and the iX documentation mentions about the adding info in the module file

### ISSUE THREAD

**Issue by renukeshSiemens** [siemens/ix#1404]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

The iX Documentation asks user to add the component in the module file but the thing is angular 17 onwards there will be no module file by default so user is lost on the very first step on onboarding 

Expected ==> it would be good have a documentation talks about how to workaround this 
https://ix.siemens.io/docs/installation/angular

**Comment by nuke-ellington** [comment]
Hello @renukeshSiemens, we are currently working on the support vor Angular standalone components (v17 and up). Please follow this PR #1325 for the status. It will be released as part of iX 3.0.0 later this year.

**Comment by renukeshSiemens** [comment]
@nuke-ellington  Thanks for your response 

Can we please update the internal documentation for the "**Current supported version of the iX framework** "  so that the end user will pick up the correct version for working on new project
