### ISSUE TITLE
select dropdown on disabled and readonly is breaking style changes

### ISSUE THREAD

**Issue by vamshisai98** [siemens/ix#1405]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?
![select](https://github.com/user-attachments/assets/27f90690-5ea6-42e1-8947-ad73dfe53599)

When using ix-select dropdown with disabled or read-only state, Styles are breaking

### What type of frontend framework are you seeing the problem on?

Angular V17.x

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
<ix-select [value]="value" [disabled]="true">
      <ix-select-item *ngFor="let item of categoryItems" [label]="item.label" [value]="item.value"></ix-select-item>
    </ix-select>
```

### Expected behaviour

ix-select should display the way when disabled or readonly attributes are selected

**Comment by matthiashader** [comment]
Hello @vamshisai98! 
Actually no style are breaking, this is the indented styling. 
According to UX brand have defined this behavior, recommendations are also: enter placeholder / text value
