### ISSUE TITLE
AG-Grid: Floating filters will not appear unless the filter property is set to true in the column definition.

### ISSUE THREAD

**Issue by vamshisai98** [siemens/ix#1406]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

![Filter](https://github.com/user-attachments/assets/71e3afc1-2947-4f2a-b1d7-7c7465298c5f)

Floating filters are only available in columns when the main filter option is enabled, resulting in both the main and floating filters being present in the column.

when floating filter is true and filter is false, The filter components disappear. (refer below ss)

![FF2](https://github.com/user-attachments/assets/f2c2fefa-1124-402b-a528-7b36327e928f)

### What type of frontend framework are you seeing the problem on?

Angular v17.x

### Which version of iX do you use?

v.2.4.1

### Code to produce this issue.

```shell
<ag-grid-angular style="height: 20rem;" class="ag-theme-alpine" [columnDefs]="searchResultCol"
    [rowData]="searchResultRow" rowSelection="multiple"  suppressCellFocus checkboxSelection></ag-grid-angular>



  public searchResultCol: ColDef[] = [
    
    {
      field: 'type',
      headerName: 'Type',
      resizable: true,
      checkboxSelection: true,
      flex: 1,
      filter: false,
      floatingFilter:true
    },
    {
      field: 'status',
      headerName: 'Status',
      resizable: true,
      sortable: true,
      flex: 1,
    },
    { field: 'hwVersion', headerName: 'HW version', flex: 1},
    
  ];
  public searchResultRow : any = [
    {
      type: 'Equipment',
      status: 'Normal',
      hwVersion: '2.0',
      checked: false,
    },
    {
      type: 'Positioner',
      status: 'Maintenance',
      hwVersion: '1.0',
      checked: true,
    },
    {
      type: 'Pressure sensor',
      status: 'Unknown',
      hwVersion: 'N/A',
      checked: false,
    },
  ];
```
### Expected behaviour

Floating filters should also be accessible or visible in columns where the main filter option is set to false and floating filter is set true true

**Comment by matthiashader** [comment]
Hello @vamshisai98! If you just want to block the interaction with the header (this includes the filtering icon), you can just suppress the menu interaction like:
`suppressMenu: true,`
or 
`menuTabs: []`
inside the ColDef.
Here is also a small example: https://stackblitz.com/edit/ifgm2w?file=src%2Fapp%2Faggrid.html,src%2Fapp%2Faggrid.ts

**Comment by vamshisai98** [comment]
Thank you this worked
