### ISSUE TITLE
ix-select can not be focused in code

### ISSUE THREAD

**Issue by AnnaGrahl** [siemens/ix#1414]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I want to implement, that the focus get to the ix select when the modal opens. But the input field is in the shadow dom. For this I am not able to set the focus so the user can instantly start typing.

![image](https://github.com/user-attachments/assets/a787714b-381f-4a6a-969d-69ce89b0c805)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

2.4.1

### Code to produce this issue.

```shell
![image](https://github.com/user-attachments/assets/a787714b-381f-4a6a-969d-69ce89b0c805)
```

**Comment by network-interface-controller** [comment]
@danielleroux Any update on that topic? What's the current status? As described above, the ability to set an auto-focus would help us to increase the usability of our product.

**Comment by danielleroux** [comment]
> @danielleroux Any update on that topic? What's the current status? As described above, the ability to set an auto-focus would help us to increase the usability of our product.

Its currently under development #1318
