### ISSUE TITLE
Boolean in Figma "hide on collapse" is working the wrong way

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#1415]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I am using the Figma library and yesterday I recognized that the Pane Options are working a littlebit confusing

<img width="543" alt="image" src="https://github.com/user-attachments/assets/2d52e073-8358-4c51-bf83-58f2e547ca83">

I have to set the "Hide on collapse" to off to get the X instead of << but it should be the other way round i guess since it is completely hidden if I close the pane.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/ee3a1f13-e716-4bb3-9563-055c7c04d4d8">

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

Figma lib

### Code to produce this issue.

```shell
It seems like it is working correctly in the ix-angular library within code.
```

**Comment by silviowolf** [comment]
Hi @katjaKoppensteiner, thanks for submitting the issue. 
You are right. Has been fixed. Update should be available.
