### ISSUE TITLE
<ix-dropdown> does not work with ID as trigger when using Shadow DOM

### ISSUE THREAD

**Issue by GauravJKshirsagar** [siemens/ix#1417]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

<ix-dropdown> does not work with ID as trigger when using Shadow DOM with ViewEncapsulation.ShadowDom enabled in Angular. As a result, we have to rely only on Angular # template reference variables, which are static and cannot be set dynamically.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
https://stackblitz.com/edit/rluddp-bopive?file=src%2Fapp%2Fdropdown-icon.ts
```

**Comment by danielleroux** [comment]
Exactly that's the idea of the shadowDOM. What's happens in the shadowDOM stays in the shadowDOM.
