### ISSUE TITLE
<IxSelect> itemSelectionChange is triggered two times after adding item

### ISSUE THREAD

**Issue by AnnaGrahl** [siemens/ix#1424]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

The event itemSelectionChange is triggered two times after adding an item to an editable select. The second time it is triggered, the value is an object and not the value string.
![image](https://github.com/user-attachments/assets/e59bc497-75eb-4cbe-87dd-01c944272234)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/k4whud?file=src%2Fapp%2Fselect-editable.ts

import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <ix-select 
    editable [value]="value"
    (itemSelectionChange)="OnSelectionChange($event)"
    >
      <ix-select-item label="Item 1" value="1"></ix-select-item>
      <ix-select-item label="Item 2" value="2"></ix-select-item>
      <ix-select-item label="Item 3" value="3"></ix-select-item>
      <ix-select-item label="Item 4" value="4"></ix-select-item>
    </ix-select>
  `,
})
export default class SelectEditable {
  value = '1';

  OnSelectionChange(event: Event) {
    const value = (event as CustomEvent)?.detail;
    console.log(value);
  }
}
```

**Comment by matthiashader** [comment]
Hello @AnnaGrahl - this issue is resolved in the latest version (2.5.0), if this issue persists don't hesitate to open a new ticket! (https://stackblitz.com/edit/owvupc?file=src%2Fselect-editable.ts)
