### ISSUE TITLE
Using customized icon in menu items

### ISSUE THREAD

**Issue by gdilarainann** [siemens/ix#1435]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Hello, I need to use customized icon in menu. Using a static path did not resolve the issue. The component sends a GET request to retrieve the icon. I aim to serve the icon from the project's path

https://engage.cloud.microsoft/main/org/siemens.com/threads/eyJfdHlwZSI6IlRocmVhZCIsImlkIjoiMjg5ODUwMjM5MTMwMDA5NiJ9?trk_copy_link=V2

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
https://github.com/gdilarainann/ix-menu.git
```

**Comment by danielleroux** [comment]
You placed the image in the source folder it must be part of the asset folder or import it how your bundler required it.
e.g https://vitejs.dev/guide/assets.html

I close this issue because its no issue of the library.
