### ISSUE TITLE
ix-menu-category not expanding

### ISSUE THREAD

**Issue by umeWaheed** [siemens/ix#1436]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I'm using ix-menu-category for a nested menu

The following has been observed:

- The menu expands if I set active=true on any of the sub menu-items
- The menu expands if I directly hit url of any sub menu-item
- The menu does not expand if I use any internal link within the application to navigate to sub menu-item page

### What type of frontend framework are you seeing the problem on?

React, Others

### Which version of iX do you use?

v2.0.0

### Code to produce this issue.

```shell
import {
  IxApplication,
  IxMenu,
  IxMenuCategory,
  IxMenuItem,
} from '@siemens/ix-react';
import React from 'react';

export default () => {
  return (
    <IxApplication>
      <IxMenu>
        <IxMenuItem home icon="home">
          Home
        </IxMenuItem>
        <IxMenuItem icon="globe">Normal Tab</IxMenuItem>
        <IxMenuCategory label="Top level Category" icon="rocket">
          <IxMenuItem icon="globe" onClick={() => {
                router.push('/path');
              }}
              {...{ active: location.split('/')[1] == 'path' }}>
              Nested Tab</IxMenuItem>
        </IxMenuCategory>
      </IxMenu>
    </IxApplication>
  );
};
```

**Comment by matthiashader** [comment]
Hello @umeWaheed ! Can you verify this behavior in the latest version(v2.4.1)?
I have tried recreating your usecase: https://stackblitz.com/edit/1zkw8s?file=src%2Fvertical-tabs.tsx 
As far i can tell it works without any problems.

**Comment by umeWaheed** [comment]
sure I'll try

**Comment by umeWaheed** [comment]
@matthiashader the issue is with the category not expanding when you navigate by clicking on **page-1** or **page-2** buttons as it does for **Default link to page-1**

**Comment by matthiashader** [comment]
Thanks for clarification - i think i got you now, you mean this behavior right:
![2024-08-2707-08-29-ezgif com-crop](https://github.com/user-attachments/assets/17e5e074-237c-4e60-8ebd-e4041a245605)

**Comment by umeWaheed** [comment]
@matthiashader yes. The category is only being set to active but not expanding. However, if you reload the same page, it expands.

**Comment by umeWaheed** [comment]
@matthiashader Moreover is there a way to set `ix-menu-category` expanded by default?

**Comment by matthiashader** [comment]
@umeWaheed yes, this is possible with the "startExpanded" property. (Note, acc. to documentation: "If set the menu will be expanded initially. This will only take effect at the breakpoint 'lg'.")

**Comment by umeWaheed** [comment]
> @umeWaheed yes, this is possible with the "startExpanded" property. (Note, acc. to documentation: "If set the menu will be expanded initially. This will only take effect at the breakpoint 'lg'.")

@matthiashader this property is available on `ix-menu`, I wanted to ask if this something similar is available for `ix-menu-category` component. I want the menu to be expanded like this by default

![image](https://github.com/user-attachments/assets/c093c2b9-4105-46d2-86b7-eea1ce782d9e)

**Comment by matthiashader** [comment]
@umeWaheed Thanks for clarification, i read out there. Yes you are right, currently this is not possible - i have talked to the UX colleagues and they have nothing against it, so i will pass this also as a requirement in to our backlog!
Internal ref: [IX-1650]
