### ISSUE TITLE
Not able to adjust the components height

### ISSUE THREAD

**Issue by vamshisai98** [siemens/ix#1443]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I am not able to adjust the height of components to align my components properly.
Similarly for below screenshots

![adjust-height](https://github.com/user-attachments/assets/b7582227-b6be-4913-b04e-ed5c51e4f164)
![message-bar](https://github.com/user-attachments/assets/7706f7b2-99cf-439b-9d6f-e2a0282da368)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
<ix-category-filter id="category-filter-search__ix-category-filter" [placeholder]="placeholder"
      [repeatCategories]="repeatCategories" [categories]="categories" [filterState]="filterState"
      (categoryChanged)="handleCategoryChange($event)" (filterChanged)="handleFilterChange($event)"
      (inputChanged)="handleInputChange($event)"></ix-category-filter>
  </div>
  <ix-select id="category-filter-search__ix-select" [value]="selectValue" [disabled]="disableDropDown"
    (valueChange)="handleValueChange($event)">
    <ix-select-item (itemClick)="handleSelectItemClick($event)" id="category-filter-search__ix-select-item" *ngFor="let item of categoryItems" [label]="item.label"
      [value]="item.value"></ix-select-item>
  </ix-select>
```

**Comment by danielleroux** [comment]
Duplicated, already tracked here https://github.com/siemens/ix/issues/1002
