### ISSUE TITLE
Auto select the dropdown value on change event from another component

### ISSUE THREAD

**Issue by vamshisai98** [siemens/ix#1445]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I want to update my ix-select value without selecting it by click, but would want it automatically selected once the ix-select data is poplulated based on API service call.
Although from the image in ix-select dropdown you can see the value is being highlighted. But the label is not updating.
![auto-select](https://github.com/user-attachments/assets/e88b503c-fb16-4a31-b07a-841ff96e36ee)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
<ix-category-filter id="category-filter-search__ix-category-filter" [placeholder]="placeholder"
      [repeatCategories]="repeatCategories" [categories]="categories" [filterState]="filterState"
      (categoryChanged)="handleCategoryChange($event)" (filterChanged)="handleFilterChange($event)"
      (inputChanged)="handleInputChange($event)"></ix-category-filter>
  </div>
  <ix-select id="category-filter-search__ix-select" [value]="selectValue" [disabled]="disableDropDown"
    (valueChange)="handleValueChange($event)">
    <ix-select-item (itemClick)="handleSelectItemClick($event)" id="category-filter-search__ix-select-item" *ngFor="let item of categoryItems" [label]="item.label"
      [value]="item.value"></ix-select-item>
  </ix-select>






//.ts file
 this.value = ''
 this.categoryItems:any = [{'label':'',value:''}]
      filterChange(){
      this.value= this.categoryItems[0].value;
      this.valueChange(this.value)
      }
      
        valueChange(event: { detail: string }) {
    console.log(event, 'SEL')
    this.selectValue = event.detail;
```

**Comment by matthiashader** [comment]
Hi @vamshisai98, thanks for reaching out - could you provide a working stackblitz examples? I have tried recreating it, but it seems to work without any problems: https://stackblitz.com/edit/qn9vg7?file=src%2Fapp%2Fselect.ts

**Comment by matthiashader** [comment]
Hello @vamshisai98 ! Tested in latest version, should be fixed - if this issue still occurs, just open a new issue.
