### ISSUE TITLE
In ix-pane component, ix-pane header title doesnt show the entire title content after exceeding a limit

### ISSUE THREAD

**Issue by vamshisai98** [siemens/ix#1447]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

ix-pane title/**header** is not shown completely after exceeding certain limit
![ix-pane](https://github.com/user-attachments/assets/adf0f35c-7c23-455f-a5c7-1dc720732ef3)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
<ix-pane class="search-result__ix-pane" [heading]="Capabiility Details of Industrial Edge - Cloud Connector" slot="right" [size]="paneSize" [hideOnCollapse]="true" [expanded]="expanded"
    id="search-result__ix-pane" (expandedChanged)="expandedChanged($event)">
/ix-pane>
```

**Comment by matthiashader** [comment]
Hi @vamshisai98, thanks for reaching out! Actually, this behavior is intentional. I’ve also consulted with our UX colleagues, and they advised that headings should generally be kept concise.

**Comment by flxlst09** [comment]
@vamshisai98 A possible solution that is also used in other applications is to keep the title short and use a separate field in the content below to show the name of the entity. Best, Felix

<img width="499" alt="image" src="https://github.com/user-attachments/assets/c7ac56da-c16f-41db-9c72-96a68e958632">
