### ISSUE TITLE
ix-basic-navigation :host width and height

### ISSUE THREAD

**Issue by sn0wcat** [siemens/ix#146]
<pre><code>
[X] Bug report
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## Current behavior
Currently the `ix-basic-navigation` doesn't render along the whole browser height.

## Expected behavior

![image](https://user-images.githubusercontent.com/1426617/202182660-bbf4a371-1fe1-4d99-87bd-1fb59018c732.png)

Actual Behavior:

![image](https://user-images.githubusercontent.com/1426617/202182821-ac2a156f-7d3e-408b-a4b1-9b00a791249b.png)

The navigation should use the full height by default.

## Minimal reproduction of the problem with instructions

Example in Angular
```html
<ix-basic-navigation>
  <ix-menu enableToggleTheme="true">
    <ix-icon name="rocket" slot="logo"></ix-icon>
    <ix-menu-item home-tab tab-icon="home"> Home </ix-menu-item>
    <ix-menu-about>
      <ix-menu-about-item label="Tab 1">Content 1</ix-menu-about-item>
      <ix-menu-about-item label="Tab 2">Content 2</ix-menu-about-item>
    </ix-menu-about>
    <ix-menu-settings>
      <ix-menu-settings-item label="Example Setting 1"></ix-menu-settings-item>
      <ix-menu-settings-item label="Example Setting 2"></ix-menu-settings-item>
    </ix-menu-settings>
    <ix-menu-avatar title="sn0wcat">
    </ix-menu-avatar>
  </ix-menu>
</ix-basic-navigation>
```

### Proposal

This can be fixed by adding the stylesheet to corresponding angular component:

```css
:host {
    display: block;
    width: 100%;
    height: 100vh;
  }
```

Proposal: Either change the default rendering behavior, or add the example CSS to the documentation.

**Comment by danielleroux** [comment]
The reason behinde this is that some application runnes for example in a MindSphere environment they have there own header.
The ix-basic-navigation or other layouting controls like map-navigation are not always the top element.

I prefer to apply the styling to the body element

```css
body {
    min-height: 100vh;
    margin: 0 auto;
}
```
[source](https://www.freecodecamp.org/news/html-page-width-height/)

**Comment by sn0wcat** [comment]
@danielleroux That is also fine (and I get the reasoning behind). As long as ix does't have layouting components, we should at least mention this in the documents.

**Comment by danielleroux** [comment]
@sn0wcat Also possible would be to add the body styling to the library css

**Comment by nuke-ellington** [comment]
Maybe I am missing the point here but IMO it should be enough that the component has `height` set to `100%`. It should be pretty obvious that one has to set the container to the desired height.

**Comment by goncalosard** [comment]
@danielleroux Verified this issue, component already had the "height: 100%", as @nuke-ellington said, component should have the height 100% and the user should set the container height.

I think we can close this issue.
