### ISSUE TITLE
Icon Button: icon-color attribute does not work

### ISSUE THREAD

**Issue by georg-adler** [siemens/ix#1461]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I'm using icon buttons in my app and would like to customize the icon color. For that i set the icon-color attribute like this:

`<ix-icon-button icon="info" variant="primary" icon-color="#01d65a"></ix-icon-button>`

The icon still has the default color.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
https://stackblitz.com/edit/rkgdsn?file=src%2Fapp%2Fbutton-with-icon.html
```

**Comment by nuke-ellington** [comment]
Hello @georg-adler, thank you for reaching out.

Please use one of the predefined [color names](https://ix.siemens.io/docs/theming/colors) from the library.

E.g.:

`icon-color="color-warning"`
