### ISSUE TITLE
IX Select: Search field can confuse users into thinking they have entered a valid value

### ISSUE THREAD

**Issue by rouven-s** [siemens/ix#1464]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

When initializing an IxSelect without default value, the search input field does not reset when unfocusing the component. Multiple customers of us therefore thought they could also add a new value by just typing it in the input field.

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
See country field here:
https://myneo.siemens.com/contact

Type e.g. "Germany - Bavaria", then tab/click out of the field. There is no way to visually differentiate the typed (invalid) value from a selected (valid) value
```

**Comment by matthiashader** [comment]
Hello @rouven-s,
Your issue has already been implemented and will be released within the next release: https://github.com/siemens/ix/pull/1456
