### ISSUE TITLE
Ix docs example code for radio buttons crashes

### ISSUE THREAD

**Issue by tobiask84** [siemens/ix#1473]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/ac8f31ca-073f-49e6-8b5f-86af2343e799">

**Comment by danielleroux** [comment]
Examples should work again 👍
