### ISSUE TITLE
Disable property for the components doesn't work properly

### ISSUE THREAD

**Issue by Yeldece** [siemens/ix#1500]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

I am a developer using the [NVDA](https://www.nvaccess.org/download/) screen reader on Windows. Due to my reliance on keyboard navigation, I frequently encounter a bug related to the "disable" attribute in IX components.
Specifically, the "disable" attribute only disables mouse click events. However, this presents a problem for keyboard users. For example, if you have an ixButton or an ixDatepicker, setting a minDate (e.g., today) on the ixDatepicker doesn't fully prevent the selection of an earlier date. Even though the component appears disabled for mouse interactions, keyboard users can still select a date from a year before the minDate.
To reproduce this issue, navigate through the page using only the keyboard, and attempt to click the second button. Check the console log to observe the behavior.

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

v2.5.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/ygj7zm-nx8zdp?file=src%2FApp.tsx
```

**Comment by matthiashader** [comment]
Hello @Yeldece - thanks for your insights.
This has to do with the fact that, in addition to the native button in the web component, the web component itself also has a click listener, which, although blocked via 'pointer-events: none' from being clicked through the UI, can still be clicked programmatically – I have adjusted the button component accordingly. Additionally, I also modified the datepicker component, which generally had an issue with keyboard navigation. (#1519 )
