### ISSUE TITLE
group context menu not showing

### ISSUE THREAD

**Issue by danielleroux** [siemens/ix#152]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Not possible to show context menu in latest release. (See https://ix.siemens.io/docs/controls/group#group-with-context-menu)

**Comment by danielleroux** [comment]
atm not fixable without breaking slot api. We should add an hint to the documentation how you can apply a workaround. (Look into fix/group-dropdown linked)

**Comment by fakhir** [comment]
All the groups on my page get re-rendered when I start using a context menu using the proposed workaround. Is this re-rendering a known problem?

**Comment by danielleroux** [comment]
Do you have code to reproduce this behavior?

**Comment by fakhir** [comment]
Please ignore the above comment. I discovered it was due to an incorrect nesting of my group component. I'm no longer facing this problem.
