### ISSUE TITLE
ix-toast is hidden behind ix-modal

### ISSUE THREAD

**Issue by 110Sw1t** [siemens/ix#1526]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Whenever we have ix-modal open we cannot see ix-toast from message service because its hidden behind the ix-modal

When errors occur after a modal is open, error/info toasts don't show because they are hidden by modal backdrop, or completely hidden if the modal width is set to full-screen

![image](https://github.com/user-attachments/assets/5aeee645-2780-4ac1-b93f-fdf330ce32d5)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.4.1

### Code to produce this issue.

```shell
Just click on button it will open both modal and toast message

Editor URL:
https://stackblitz.com/edit/gnjkyi-vjp7as?file=src%2Fmodal-by-template.ts

Application URL: 
https://gnjkyi-vjp7as.stackblitz.io
```

**Comment by danielleroux** [comment]
Already tracked via https://github.com/siemens/ix/issues/798. I close this one here.
