### ISSUE TITLE
Content Header on click of the title, it triggering the event

### ISSUE THREAD

**Issue by vamshisai98** [siemens/ix#1538]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

On click of the title of content header component. Event is getting triggered

  
  
  
![content-header](https://github.com/user-attachments/assets/723a252d-4fb6-49aa-9a21-ee941819dbae)

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.5.0

### Code to produce this issue.

```shell
<ix-content-header
        (click)="onClickRouteBack()"
        has-back-button="true"
        header-title="Results"
      >
      </ix-content-header>
      
onClickRouteBack() {
    this.router.navigate(['/']);
  }
```

**Comment by danielleroux** [comment]
@vamshisai98 that is a expected behaviour every component extends from [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement).

Use the dedicated event `backButtonClick` (for details look into documentation)
