### ISSUE TITLE
IxSlider does not work properly when setting step to a non round numbers

### ISSUE THREAD

**Issue by AmitSmall** [siemens/ix#1550]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

When the step is a non round number, the component is glitching.
I can't get decimal values when moving the slider, and it's especially noticeable when the range is not between round numbers.
The slider does follow my assigned steps, but the value and trace is stuck on the last round number.
I would expect the value and UI to support decimal numbers.
Attaching an example

### What type of frontend framework are you seeing the problem on?

React

### Which version of iX do you use?

2.5.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/axotbx-jgdusq?file=src%2Fslider.tsx%3AL15
```

**Comment by nuke-ellington** [comment]
Should be fixed via #1468 (next release)
