### ISSUE TITLE
Toast: missing properties in documentation

### ISSUE THREAD

**Issue by silviowolf** [siemens/ix#157]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Documentation of the toast properties seems to be missing.  
 https://ix.siemens.io/docs/controls/toast

**Comment by danielleroux** [comment]
In this case we need a better documentation for the toast-utils (https://github.com/siemens/ix/blob/main/packages/core/src/components/toast/toast-utils.ts)

This implementation is different for each framework

angular: https://github.com/siemens/ix/blob/main/packages/angular/src/toast/toast.service.ts
react: https://github.com/siemens/ix/blob/main/packages/react/src/toast/toast.ts

**Comment by danielleroux** [comment]
As discussed with ux/ui we use tabs under an "how to use" section:

![Image](https://user-images.githubusercontent.com/2144313/203761754-4a3160ed-bf61-4a20-b0bd-1265fc2ada6b.png)

/cc @goncalosard @nuke-ellington
