### ISSUE TITLE
Stackblitz button is broken

### ISSUE THREAD

**Issue by georg-adler** [siemens/ix#1575]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [X] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

When clicking the stackblitz button for any Angular or Vue example nothing happens.
The network tab shows a 404 error when trying to get the styles.

**Comment by danielleroux** [comment]
Should now work again!
