### ISSUE TITLE
Grid support/alternative

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#159]
## I'm submitting a...

<pre><code>
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior

We need to discuss how we want to handle the grid support going forward.
Ag-grid's enterprise features are a blocker for many teams and we might want to look for an replacement (or not).

@ChristianButter

**Comment by danielleroux** [comment]
We will not provide another grid implementation for now.
