### ISSUE TITLE
Datetimepicker background does not cover whole control

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#160]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior

The datetimepicker's background color should cover the whole control. Also the picker should have a max width and not stretch indefinetly.

**Comment by goncalosard** [comment]
@danielleroux @nuke-ellington This issue should be closed, background issue is already fixed and the max-width issue, i asked Silvio and he said it should not have max-width and the width should adapt to the content needs.

**Comment by danielleroux** [comment]
@goncalosard 👍
