### ISSUE TITLE
Select value can not be changed twice by setting binding data in angular 

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#161]
## I'm submitting a potential bug of the select control in Angular

<pre><code>
[ x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Select value can not be changed twice by setting binding data in angular. 

## Expected behavior
Select value should always the same to the binding data

## Minimal reproduction of the problem with instructions

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-testpage',
  template: `<ix-select [selectedIndices]="selectedIndices">
      <ix-select-item label="Item 1" value="1"></ix-select-item>
      <ix-select-item label="Item 2" value="2"></ix-select-item>
      <ix-select-item label="Item 3" value="3"></ix-select-item>
      <ix-select-item label="Item 4" value="4"></ix-select-item>
    </ix-select>
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem()"
      >Button</ix-button
    >`,
})
export class TestpageComponent implements OnInit {
  selectedIndices = '1';
  constructor() {}

  ngOnInit(): void {}

  changeSelectedItem() {
    this.selectedIndices = '4';
  }
}
```
### Reproduction steps
1.  Click the button to set  the selectedIndices  to "4", then the selected value changes to "Item 4" as expected
2.  Change the value to "Item 1" in the select control, then the select value changes to "Item 1"  as expected
3. Try to change the select value by clicking the button once again, you will find the selected value stays on "Item 1"

## What is the motivation / use case for changing the behavior?

Sometimes the value of the selector depends not only on the user's input, but sometimes it is necessary to change to a default option according to the actual situation, such as cross-checking. The value of the selector automatically toggles the correct option when the settings have conflictions, so that the user do not need to solve the confection by themselves.

**Comment by danielleroux** [comment]
@chencc1988 You have to handle a selection change in our component and keep the state synchronized. Otherwise the contorl (ix-select) can not compare a value change.

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-select',
  template: `
    <ix-select
      [selectedIndices]="selectedIndices"
      (itemSelectionChange)="change($event)"
    >
      <ix-select-item label="Item 1" value="1"></ix-select-item>
      <ix-select-item label="Item 2" value="2"></ix-select-item>
      <ix-select-item label="Item 3" value="3"></ix-select-item>
      <ix-select-item label="Item 4" value="4"></ix-select-item>
    </ix-select>
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem()"
      >Button</ix-button
    >
  `,
})
export class Select {
  selectedIndices = '1';

  change({ detail: [id] }: CustomEvent<string[]>) {
    this.selectedIndices = id;
  }

  changeSelectedItem() {
    this.selectedIndices = '4';
  }
}

```

**Comment by chencc1988** [comment]
Th

> @chencc1988 You have to handle a selection change in the component and keep the state synchronized. Otherwise the contorl (ix-select) can not compare a value change.
> 
> ```
> import { Component } from '@angular/core';
> 
> @Component({
>   selector: 'app-select',
>   template: `
>     <ix-select
>       [selectedIndices]="selectedIndices"
>       (itemSelectionChange)="change($event)"
>     >
>       <ix-select-item label="Item 1" value="1"></ix-select-item>
>       <ix-select-item label="Item 2" value="2"></ix-select-item>
>       <ix-select-item label="Item 3" value="3"></ix-select-item>
>       <ix-select-item label="Item 4" value="4"></ix-select-item>
>     </ix-select>
>     <ix-button class="m-1" variant="primary" (click)="changeSelectedItem()"
>       >Button</ix-button
>     >
>   `,
> })
> export class Select {
>   selectedIndices = '1';
> 
>   change({ detail: [id] }: CustomEvent<string[]>) {
>     this.selectedIndices = id;
>   }
> 
>   changeSelectedItem() {
>     this.selectedIndices = '4';
>   }
> }
> ```

Thanks, it works

**Comment by chencc1988** [comment]
@danielleroux 
Could you help me have a look at this case? I used the async pipe to bind the value. In fact the value is a state in redux store.  When I set the select value to one byte string,  it works. But if I set the value to multiple characters, it failed. I'm nearly crazy.   

```import { Component, OnInit } from '@angular/core';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-testpage',
  template: `<ix-select [selectedIndices]="selectedIndices$ | async">
      <ng-container *ngFor="let item of options">
        <ix-select-item
          [label]="item.label"
          [value]="item.value"
        ></ix-select-item>
      </ng-container>
    </ix-select>
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem1()"
      >Button</ix-button
    >
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem2()"
      >Button</ix-button
    >`,
})
export class TestpageComponent implements OnInit {
  subject$ = new Subject<string>();
  selectedIndices$ = this.subject$.asObservable();
  options = [
    { value: '1', label: 'Item1' }, //it works
    { value: '2', label: 'Item2' }, //it works
    // { value: '11', label: 'Item1' }, //it does not work
    // { value: '22', label: 'Item2' }, //it does not work
  ];
  constructor() {}

  ngOnInit(): void {}

  changeSelectedItem1() {
    this.subject$.next('1'); //it works
    // this.subject$.next('11'); //it does not work
  }

  changeSelectedItem2() {
    this.subject$.next('2'); //it works
    // this.subject$.next('22'); //it does not work
  }
}
```

**Comment by chencc1988** [comment]
@danielleroux

I think I know what is wrong in this case.
After I changed the Observable to Observable<Array<string>> it works. The select control seems not working properly when using async pipe with Observable<string>

This demo does not work
```
import { Component, OnInit } from '@angular/core';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-testpage',
  template: `<ix-select [selectedIndices]="selectedIndices$ | async">
      <ng-container *ngFor="let item of options">
        <ix-select-item
          [label]="item.label"
          [value]="item.value"
        ></ix-select-item>
      </ng-container>
    </ix-select>
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem1()"
      >Button</ix-button
    >
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem2()"
      >Button</ix-button
    >`,
})
export class TestpageComponent implements OnInit {
  subject$ = new Subject<string>();
  selectedIndices$ = this.subject$.asObservable();
  options = [
    { value: '11', label: 'Item1' },
    { value: '22', label: 'Item2' },
  ];
  constructor() {}

  ngOnInit(): void {}

  changeSelectedItem1() {
    this.subject$.next('11');
  }

  changeSelectedItem2() {
    this.subject$.next('22');
  }
}

```

This demo works
```
import { Component, OnInit } from '@angular/core';
import { Subject } from 'rxjs';

@Component({
  selector: 'app-testpage',
  template: `<ix-select [selectedIndices]="selectedIndices$ | async">
      <ng-container *ngFor="let item of options">
        <ix-select-item
          [label]="item.label"
          [value]="item.value"
        ></ix-select-item>
      </ng-container>
    </ix-select>
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem1()"
      >Button</ix-button
    >
    <ix-button class="m-1" variant="primary" (click)="changeSelectedItem2()"
      >Button</ix-button
    >`,
})
export class TestpageComponent implements OnInit {
  subject$ = new Subject<Array<string>>();
  selectedIndices$ = this.subject$.asObservable();
  options = [
    { value: '11', label: 'Item1' },
    { value: '22', label: 'Item2' },
  ];
  constructor() {}

  ngOnInit(): void {}

  changeSelectedItem1() {
    this.subject$.next(['11']);
  }

  changeSelectedItem2() {
    this.subject$.next(['22']);
  }
}

```

It might be better change the selectedIndices from type  ``string ｜ string[]`` to ``string[]`` in document.

**Comment by danielleroux** [comment]
@chencc1988 Thank for demo code, this helps alot! I think there is a problem during the change detection of the value. The array options works always because the ['11] next tick will always create a new reference.

**Comment by chencc1988** [comment]
I guess that it is not caused by change detection probably, because if you change the "11" and "22" to "1" and "2" in the failed demo, it becomes working. The change has been definitely detected. 
It seems that the string has been split to array and only the first character of the value is used for comparison with the options.

**Comment by danielleroux** [comment]
@chencc1988 #166 will fix it
