### ISSUE TITLE
Docking tabs support

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#162]
## I'm submitting a...

<pre><code>
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## What is the motivation / use case for changing the behavior?

From time to time we get requests for docking tabs (see e.g. flexlayout-react).
Do we want to offer support or not in the long run?

**Comment by danielleroux** [comment]
As discussed in our latest Jour fixe we will not implement the library such as `flexlayout-react` or a theme directly for it, but we try to make it easier in form of examples etc to integrate 3rd party libs.

With help of #114 and our custom css properties it should be possible to theme the flexlayout-react.
