### ISSUE TITLE
Feature request: application header for basic navigation

### ISSUE THREAD

**Issue by marcburkhardtsiemens** [siemens/ix#165]
## I'm submitting a...

<pre><code>
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The current "Basic Navigation" supports only a very simple header. We want to have
a header with changeable logo, app name, user settings, logon/off, notifications, help drop-down, general settings.

## Expected behavior
From left to right

Left aligned:
logo: here we want to place the logo of our company (on the 
app name: Name of the application or product

right aligned:
notification: icon "alarm-bell" as ghost button, if pressed the notification panel opens
help: icon "question" as ghost button, if pressed drop-down menu with some text icon entries
settings: icon "context-menu" as ghost button, if pressed drop-down menu with some text icon entries
user profile: icon with user initialia as ghost button, if pressed a tile with user information is hsown (and logout button)

## Minimal reproduction of the problem with instructions
It is feature request

## What is the motivation / use case for changing the behavior?
This kind of header is not implemented right now. There is already a design proposal
but somehow it is no implemented.
We need a common "application header" with the need functions as described.

![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/118828888/203343478-bf3b3ba4-96b3-420f-9c55-1999300c159d.png)

**Comment by danielbruns93** [comment]
Are there any updates on when the new header implementation will be available?
