### ISSUE TITLE
Category filter clear button styling

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#167]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Expected behavior

Button design should match the spec for input clear buttons.

**Comment by goncalosard** [comment]
@danielleroux @nuke-ellington 
I have been trying to find a solution to this issue.

Zeplin has two diferent styles for the hover depending on the theme as the following shows:

Classic Theme
![image](https://user-images.githubusercontent.com/63813420/203973780-62729457-4b05-447a-92b5-749a4a712b9a.png)

Brand Theme
![image](https://user-images.githubusercontent.com/63813420/203973842-5e91d5e7-13e5-4afd-a159-b861236c00e8.png)

And this is the current implementation no matter what the theme is:
![image](https://user-images.githubusercontent.com/63813420/203974194-2b5b6126-dc3c-4e2c-abf2-6bcf17cc0332.png)

For the intended result to happen, it need to be implemented in the "ix-icon-button", but there is already a normal state and a oval state, that are separated and invoked using props.

With the following code used in ix-icon-button toggled on a prop, i can make the perfect result happen to the clear button without disturbing the ix-icon-button component in general. But this doesnt feel like the the correct fix, please give me suggestions how to toggle the changes between the Themes.

.clear-button {
  border-radius: $variable ----> 0px or 6.25rem
  height: 25px;
  width: 25px;
  min-width: 25px;
}

![image](https://user-images.githubusercontent.com/63813420/203975957-9905eb47-f4e3-4c44-81c8-d49ba5de8605.png)
![image](https://user-images.githubusercontent.com/63813420/203976025-9eac5af4-06c2-4e33-820a-15bc4dd63679.png)

**Comment by danielleroux** [comment]
@goncalosard Have to check this, i give you feedback asap

**Comment by danielleroux** [comment]
- [ ] Fix error in icon-button 24px size of button not existing
- [ ] Add margin to clear button in expanding-search
- [ ] Check other input's with clear button

`clear` icon is really smaller then the other icons!
