### ISSUE TITLE
button in ghost state should not have border during pressed state

### ISSUE THREAD

**Issue by danielleroux** [siemens/ix#174]
## I'm submitting a...

<pre><code>
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Current implementation of button(ghost = true) should no have a border in ":active" state.

<img width="353" alt="image" src="https://user-images.githubusercontent.com/2144313/203759554-040b948e-1069-420a-91f6-23f11fb1eae8.png">

**Comment by danielleroux** [comment]
@nuke-ellington Should we do this as a part of the refactoring for #138?

**Comment by nuke-ellington** [comment]
> @nuke-ellington Should we do this as a part of the refactoring for #138?

Should be fine either way IMO (as part of 138 as well as stand alone fix).
