### ISSUE TITLE
Installation in a Project with Angular Version <14.0.0 throws Error

### ISSUE THREAD

**Issue by neunteufelflorian** [siemens/ix#188]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Installing the iX System on a Project with Angular Version 13.1.1 throws the following error:

```
Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):  
TypeError: Cannot create property 'message' on string 'C:\_data\launchpad\node_modules\@siemens\ix-angular\fesm2015\siemens-ix-angular.mjs: This application depends upon a library published using Angular version 14.2.4, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
```

## Minimal reproduction of the problem with instructions

Install as described on the iX-Website & add styles & add IxModule.forRoot() and BrowserAnimationModule to ApplicationModule, then run the project.

**Comment by danielleroux** [comment]
@nuke-ellington Maybe we need to downgrade angular compiler to at least to angular 12. (https://github.com/angular/angular/issues/46748)
