### ISSUE TITLE
Need support card style in dark theme

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#192]
## I'm submitting a requirement

<pre><code>
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
I tried to add a bootstrap card class and found that the card style is totally different from IX dark theme.

## Expected behavior
Need theme support for card component

## Minimal reproduction of the problem with instructions
```
<div class="card">
  <div class="card-body">
    This is some text within a card body.
  </div>
</div>
```

**Comment by danielleroux** [comment]
We will not directly theme bootstrap but we want to implement a design pattern showcase. In this showcase you will find a solution to implement such a card with ix.

#205
