### ISSUE TITLE
font color of echart theme not readable in dark themes

### ISSUE THREAD

**Issue by danielleroux** [siemens/ix#20]
![image](https://user-images.githubusercontent.com/2144313/194326843-59aae48d-0d7a-432d-ba18-21feb0c25947.png)

Legend text not readable in dark mode

Also check font color of axis in dark mode. seems to dark

_Originally posted by @ChristianButter in https://github.com/siemens/ix/issues/16#issuecomment-1270052690_

**Comment by silviowolf** [comment]
Hi @danielleroux, could you please double check if the eChart Theme Builder JSONs are applied correctly? The colors in the screeshot/documentation seem to be completely different from the colors in the theme files – in light and dark, Brand and Classic. 
![image](https://user-images.githubusercontent.com/115155312/211359359-39f08350-19d9-4149-b180-de967902aedb.png)  
![image](https://user-images.githubusercontent.com/115155312/211359572-be8390aa-0220-4c02-a65f-c13e75210da5.png)  
![image](https://user-images.githubusercontent.com/115155312/211360428-95adfbca-2b22-45ac-bbf2-07a2c3607b9e.png)  
![image](https://user-images.githubusercontent.com/115155312/211360571-33fea74d-2261-4202-8a78-9c6e23c3d8e0.png)
