### ISSUE TITLE
Ag-grid theme background

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#220]
### What happened?

Currently the iX ag-grid theme does set the grid background to transparent in order to deal with various background colors.
This can cause confusion and might not yield a determenistic outcome.

- [ ] <strike>Set background</strike>
- [ ] Fix broken properties e.g.: 
```
--ag-checkbox-checked-color: var(--theme-color-input--focus);
--ag-range-selection-border-color: var(--theme-color-input--focus);
```

### What type of frontend frameware are you seeing the problem on?

Angular, React, JavaScript

### Which version of iX do you use?

1.1.1

**Comment by danielleroux** [comment]
As discussed with @silviowolf background of the AGGrid stays transparent
