### ISSUE TITLE
Need support for pagination

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#234]
### Suggestion / feature request

The pagination looks very obtrusive under dark theme. Would the IX team add pagination controls in future version？

![Capture](https://user-images.githubusercontent.com/10339536/206974143-bc1dfac6-a8c8-472a-a43f-f64a1a9dece2.png)

```
<ul class="pagination">
  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
  <li class="page-item"><a class="page-link" href="#">1</a></li>
  <li class="page-item"><a class="page-link" href="#">2</a></li>
  <li class="page-item"><a class="page-link" href="#">3</a></li>
  <li class="page-item"><a class="page-link" href="#">Next</a></li>
</ul>
```

**Comment by silviowolf** [comment]
Pagination/Page will be integrated.

**Comment by silviowolf** [comment]
Preparing specs for dev
