### ISSUE TITLE
Modal backdrop static does fire event when modal is clicked

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#241]
### What happened?

Normally the modal should close when the backdrop gets clicked. Currently it seems as the modal closes when itself is clicked as well.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

1.1.2

### Code to produce this issue.

```shell
modalService
      .open({
        backdrop: 'static',
        centered: true,
        content: this.modalRef,
        scrollable: true,
        title: 'Customize columns'
      });
```

**Comment by danielleroux** [comment]
#285
