### ISSUE TITLE
Dropdown ixDropdownTrigger does not work

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#251]
### What happened?

Dropdown won't open. Also docs have a mixture of deprecated `tirgger` and current `ixDropdownTrigger` property in the examples.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

1.2.0

**Comment by danielleroux** [comment]
@nuke-ellington Can you add code to reproduce this issue? Tested with https://github.com/siemens/ix/blob/main/packages/angular-test-app/src/preview-examples/dropdown.ts and works in latest main.
