### ISSUE TITLE
The stepSelected event seems does not work in Angualr

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#254]
### What happened?

The stepSelected  event of ix-workflow-steps  seems not work in Angular
I don't know if it was my code issue or the IX issue because there is not any example in the doc

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.2.1

### Code to produce this issue.

See [https://stackblitz.com/edit/angular-qo5vdv-gdehxp?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-qo5vdv-gdehxp?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts)

**Comment by danielleroux** [comment]
@chencc1988 can you try to set clickable property to the workflow-steps

![image](https://user-images.githubusercontent.com/2144313/218808280-2187e294-b13a-4124-8e5c-6b0a1e13e7a1.png)
https://ix.siemens.io/docs/controls/workflow#props

**Comment by chencc1988** [comment]
Yes it works
