### ISSUE TITLE
unexpected behavior for disabled ix-button

### ISSUE THREAD

**Issue by SusiHorter** [siemens/ix#263]
### What happened?

The ix-button is not clickable, if the disabled property is set to 'false'.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.2.1

### Code to produce this issue.

```shell
<ix-button
        ghost
        disabled="false"
        (click)="Disabled()">
        disabled
      </ix-button>
      <ix-button
        ghost
        (click)="Enabled()">
        enabled
      </ix-button>
```

**Comment by SusiHorter** [comment]
@danielleroux is this bug resolved in iX version 1.3.0? 
Because in our implementation is the style of the button like its disabled, but the button can be clicked.

**Comment by nuke-ellington** [comment]
@SusiHorter yes this should be fixed. Can you please share your code again?

**Comment by SusiHorter** [comment]
@nuke-ellington Thank you for the fast answer.

The code is: 
`<ix-icon-button
        icon="remove-eye"
        ghost
        disabled
        placement="bottom"
        ngbTooltip="Offboard device"
        (click)="PerformActionOnSelectedDevices('offboardDevices')">
</ix-icon-button>`

But I think this is a local problem of my colleague, because I tried it myself and strangely it works.
