### ISSUE TITLE
Dropdown placement is slightly off

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#265]
### What happened?

The dropdown overlapes the trigger element slightly.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

1.2.0

### Code to produce this issue.

```shell
Reproducible in docs
```

**Comment by nuke-ellington** [comment]
@silviowolf please provide specs so that we can fix the buggy behaviour :)

**Comment by silviowolf** [comment]
Depending on the opening direction,
- the Dropdown should be placed without spacing, directly on the triggering component
- should be flush with the edge of the triggering component, except for a centered placements
Examples:  
![image](https://user-images.githubusercontent.com/115155312/216104649-5e327fc2-c441-4521-93f3-3fdf9b5e8969.png)  
![image](https://user-images.githubusercontent.com/115155312/216106780-b9c2cfd5-5e97-4784-866c-908cd1b6c21b.png)  
![image](https://user-images.githubusercontent.com/115155312/216107855-3a8e41f5-517e-4851-a127-566b9c4b9e5e.png)
