### ISSUE TITLE
Bug: `document.body` `null` causes exceptions when testing with cypress

### ISSUE THREAD

**Issue by d-led** [siemens/ix#266]
## Problem

when testing an Angular Ix app with Cypress (e2e) and hovering over the test steps, the cypress-controlled browser throws exceptions in [popover.util.ts:L37](https://github.com/siemens/ix/blob/ce5d7cb3e31327e84e02d4a017493ece90caf98e/packages/core/src/components/utils/popover.util.ts#L37) or may hang.

Full reproduction step by step in a minimal repo: https://github.com/d-led/angular-ix-cypress#cypress-e2e-documentbody-is-null-in-popoverdestroy-bug-reproduction

![Screenshot 2022-12-20 at 16 50 44](https://user-images.githubusercontent.com/1716584/208708573-b34092d3-e907-4df7-a5f2-f81fa577417b.png)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.2.1

### Code to produce this issue.

https://github.com/d-led/angular-ix-cypress

**Comment by danielleroux** [comment]
@d-led tested it with your repository, but cannot reproduce it.

https://user-images.githubusercontent.com/2144313/212014632-7791ca86-6333-4068-8141-da236128470b.mov

**Comment by danielleroux** [comment]
@d-led i think this issue is more related to [cypress ui](https://github.com/cypress-io/cypress) not to ix.

**Comment by d-led** [comment]
as a clarification: cypress mounts a DOM snapshot when hovering over a step.

One can see it as a cypress issue or a robustness issue of ix. Cypress is a major UI automation tool and it's likely that users of ix will use it. 

I've looked at the code, and specifically this event listener is set up on the `document.body`. Others, e.g. are set up on `window`. A different target or simply a null check would solve the problem in this case.

Other parts of ix seem to work fine with ix

**Comment by d-led** [comment]
Here, [fb](https://github.com/facebook/flow/issues/4783) is discussing a similar issue, where the flow compiler requires a null check. In other discussions there are e.g. proposals from the react project to use a different target

**Comment by danielleroux** [comment]
@d-led thank you for the detailed preparation 🎉. As discussed with the team we will merge #153 with 1.3.0. In this PR we removed this popover util class entirely.

**Comment by d-led** [comment]
@danielleroux superb. glad to hear!
