### ISSUE TITLE
Skeleton loader

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#268]
### Suggestion / feature request

Skeleton loaders are ubiquitous today and should be a great adition to Siemens iX.

**Comment by silviowolf** [comment]
Agreed. I am already seeing usecases in current apps where a skeleton loader could help feel loading times less disuptive.

**Comment by nuke-ellington** [comment]
As far as shapes go we should be able to mimic most of our real components (e.g. list items, tiles).
Practically this would mean mostly rectangular shapes?

**Comment by silviowolf** [comment]
UX Weekly 2023-02-16:
- include skeleton loader into respective components
- introduce a loading state (in Figma) that will show the skeleton
- expected shapes: circle, rectangle, lines

**Comment by silviowolf** [comment]
@nuke-ellington 
In UX design we would introduce a boolean property (e.g. "loading" false/true) in the regarding component (e.g. event list) to show/hide the skeleton view. Would this also match the way it would be developed?

**Comment by danielleroux** [comment]
IX-415
