### ISSUE TITLE
Profile picture picker

### ISSUE THREAD

**Issue by J-A-Hansen** [siemens/ix#276]
### Suggestion / feature request

**Suggestion / feature request**

A component for selecting profile pictures should be provided, leading to a standardized look&feel for this common functionality across all applications using iX.

We have attached a design suggestion, but we are open for other designs, if other designs are already in use.

![Profilepicture](https://user-images.githubusercontent.com/122023788/210780739-a067adee-fdba-405d-9c16-aa25b01b7f3b.png)

**Comment by silviowolf** [comment]
Just a few first UX ideas on that:  

- access to the actual image picker via an edit action
- edit workflow will happen in a modal
- user can delete an existing image
- user can add/change image via drag & drop or explicitly by an action button (will open OS file dialog)
- user can move and resize a clipping mask (shape is defined from outside)
- user can apply changes or cancel dialog

Thoughts on dev:
- property for shape of clipping mask (circle, rect, square, + rounded in % for rect and square)
- property for target size of clipping mask necessary?
- property fro placeholder? (when no image is set)
- property for min/max resolution? --> related to target size of clipping mask
- supported image formats (gif, jpg, png, bmp)?
- consider meta data for image orientation (jpg only)
- What happens with GIF animations?

Open questions:
What is the expected output of the workflow?  
- A rendered image (e.g. with circular clip) as PNG (to support transparency)?  --> further changes would be limited to the clipped rest of the image
- A clipped rectangular image?  --> almost same as above
- The original image + clipping mask dimensions? -->Target application needs to understand the output format but re-editing is always possible.
- Both depending on property?

**Comment by J-A-Hansen** [comment]
Concerning the expected output:
Presuming that profile pictures will be displayed in the same way (circular) all throughout the application, I would expect a clipped image (either square or circular). This would make usage easy, so that no further processing has to be done when displaying it in several places.
I would think that the use case of later on selecting another section from the same original image as new profile picture is very rare, so I would not need the original image + clipping mask.

**Comment by lorenzkunze** [comment]
From a workflow and UX perspective i think the following components or modules are required:
1. Profile picture picker - featuring a preview of current avatar and options to select a dummy image, initials or an already cropped image. And options to apply the selection or upload (and crop) a new picure.
2. Upload component - already available, needs to be configured to allow only the upload of supported image formats.
3. Image cropper component - preview of the uploaded image, preview of the mask for cropping (already preconfigured for the required size, shape and resolution of the image. Functionality to zoom and move the image behind the mask. Option to clear the image (back to upload) and to crop the image previewed inside  the mask. Optional (simple) edit functionality for the image (rotate, mirror, reset to original size, zoom to fit).

**Comment by silviowolf** [comment]
Will not be part of iX, in enterprise environments Identities will usually be provided by ID services which handle that.
