### ISSUE TITLE
Wrong Icons

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#293]
### What happened?

I have installed @siemens/ix-icons with version 1.0.3 (latest) within my project.

When using the icons all of them are wrong. 

Example is the glyph-chevron-right-small, it should be EA4C
![image](https://user-images.githubusercontent.com/109066516/212253773-713d0e04-6efd-4d61-a527-3db5d7679103.png)
but it is actually EA58.
The node_modules look like 
![image](https://user-images.githubusercontent.com/109066516/212253630-9de5d00e-d9c7-4e80-9926-049fc51a6dbd.png)

Which leads that there is kind of a stop symbol instead of the chevron within the breadcrumb.
![image](https://user-images.githubusercontent.com/109066516/212253881-2c0f3dd1-1226-4d0b-8a02-7f2e0d3b2235.png)

### What type of frontend frameware are you seeing the problem on?

JavaScript

### Which version of iX do you use?

1.0.3

### Code to produce this issue.

```shell
Install ix-icons with latest available version (1.0.3)
use it 
example: 
<span class="glyph glyph-18 glyph-chevron-right-small sc-ix-breadcrumb"></span>
```

**Comment by danielleroux** [comment]
@katjaKoppensteiner the :before content is autogenerated in the order to the svg list. Do you using the content code directly?

**Comment by katjaKoppensteiner** [comment]
I am not using the webcomponents, I use the class directly
![image](https://user-images.githubusercontent.com/109066516/212256838-573fe628-7f75-4bd6-af1f-ff1813a18647.png)

If I click on the source on the right side, within this project everything is bundled to one big css file which is called vendor.css - it is an Ember Project
![image](https://user-images.githubusercontent.com/109066516/212257008-461020e1-b588-47a4-a156-30f1ffb0fabb.png)

**Comment by danielleroux** [comment]
Looks fine i think. Double checked it in latest build:
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/2144313/212257457-aa8dacd7-b8e7-4ade-9f59-9b76c8914c42.png">
<img width="215" alt="image" src="https://user-images.githubusercontent.com/2144313/212257513-c59fc5cf-bd25-407f-8bce-a4bf448bfcf2.png">

Here you can checkout the demo: https://stackblitz.com/edit/angular-3vj3uz?file=src/index.html

Maybe you have to cleanup some cache?
