### ISSUE TITLE
Offer an easy way to integrate a second icon font or own icon set

### ISSUE THREAD

**Issue by silviowolf** [siemens/ix#322]
### Suggestion / feature request

Some applications need very app specific icons which will never be integrated into the ix icon font. There should be an easy way to integrate an own set of icons e.g. as second icon font without running into naming conflicts.

**Comment by nuke-ellington** [comment]
1. Clone `@siemens/ix-icons` (https://github.com/siemens/ix-icons)
2. Remove all `SVG`s in the svg/ folder and replace with your own
3. Run `yarn install && yarn build`
4. Copy the dist folder into your project’s assets folder
5. Import `assets/dist/css/ix-icons.css` in you stylesheet

**Comment by danielleroux** [comment]
Please do not forget to rename it to another project name and css output name.
