### ISSUE TITLE
Improve useability of the datepicker for range selection

### ISSUE THREAD

**Issue by philippsteinberg** [siemens/ix#324]
### Suggestion / feature request

We are currently migrating one of our projects to ix and the datepicker confused the developers and users.

When the datepicker loads the current date is preselected.
With the current behaviour all previous days are then locked because you can only select only a future second date (see screenshot)
To select a date range in the past the user has to deselect the current date first to be able to select a start date for the range that is in the past
![grafik](https://user-images.githubusercontent.com/117842757/214600043-b6d6d064-a3de-4718-aa4b-970047a5c568.png)

So my suggestion would be not to block the previous days on the range selection and just switch the from date when a previous date is selected (like in angular material https://material.angular.io/components/datepicker/overview#date-range-selection)
Or could we make at least the preselection of the current day optional so that the user don't have to preselect the current date before he can select days in the past

BR
Philipp

**Comment by silviowolf** [comment]
From UX perspective:
- expected behavior: a start date should not be preselected, the users's first click into the picker should always be the start date
- first selecting the end date and then selecting the first date is also a valid usecase and would be an appropriate way to enhance error tolerance

**Comment by silviowolf** [comment]
planned with https://agileworld.siemens.cloud/jira/browse/IX-20
