### ISSUE TITLE
Modal example does not work properly

### ISSUE THREAD

**Issue by kimokono91** [siemens/ix#326]
### What happened?

# What happened?
When I click on the "Show Modal" button for the first time, everything works fine. The dialog box opens and can be closed by clicking on one of the two buttons. When I try to open it again, the modal comes up without any content. The text and buttons that should be inside the modal appear in the background and the modal is empty. 

![ModalBug](https://user-images.githubusercontent.com/54797678/214607716-8a89b2f6-0fe3-4cba-bdac-ae28cb132f83.gif)

Bug experienced with Chrome, Chromium, Firefox and Edge.

# What type of frontend frameware are you seeing the problem on?
Vanilla JS

# Which version of iX do you use?
v1.2.1

# Code to produce this issue.
[Example code on ix.siemens.io](https://ix.siemens.io/docs/controls/modal)

**Comment by nuke-ellington** [comment]
Should have been fixed by #207. We'll have to check again.

**Comment by kimokono91** [comment]
The snippet in V1.3.0 works like a well-oiled machine. 
Thanks for that!

Maybe you could update ix.siemens.io :)

**Comment by nuke-ellington** [comment]
Updated example is live on [ix.siemens.io](https://ix.siemens.io/docs/controls/modal).
