### ISSUE TITLE
Recursive Group component

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#329]
### Suggestion / feature request

Within our project, we use `Group` component to show the structure of device system which consists of 3 levels.
It would be nice to have an option for 2nd level to be also collapsible - similarly as the whole group is. 

As a workaround, we use indentation for 3rd level to show the hierarchy, but it cannot be hidden in any way.
At this screenshot, group item called `Module 1` could be collapsible.  

![image](https://user-images.githubusercontent.com/99844553/214843526-4131e57e-08a9-4606-8b6e-ccb418660648.png)

For our project, 3 levels are ok, but maybe there could be a more universal solution. This is kind of mixture of group and tree, but tree is not suitable here.

**Comment by danielleroux** [comment]
@tomas-reznak From UX perspective it is not intended to use a hierarchy level inside the group component, as it will create ux issues (spacing, scrolling). Feel free to get in contact with @ChristianButter (MS Teams) or @silviowolf (MS Teams) to get a solution.

**Comment by tomas-reznak** [comment]
This is from "nice to have" category, I understand that implementation of this might be tricky, We will find a solution if we will be forced to do so. Thx.
