### ISSUE TITLE
Empty Group component should not be expandable

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#330]
### What happened?

When there are no group items within `Group` component, it still enables collapse/expand functionality (icon) to show subitems. 

![Animation](https://user-images.githubusercontent.com/99844553/214848987-0eacace2-34ca-4591-aa3c-ecb4f4a61400.gif)

Correct behavior: collapse/expand icon should not be displayed when there are no group items.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.2.1

### Code to produce this issue.

```shell
<IxGroup
  className={hasModules ? "" : "empty"}  // we use this currently as a workaround
  header="210.90.170.175"
  sub-header="SubHeader"
  selected={true}
>
  // no group items to show in specific cases
</IxGroup>
```

**Comment by silviowolf** [comment]
UX Weekly 2023-02-16:
- makes sense
- hide arrow when group is empty
- Figma: introduce property to hide arrow
