### ISSUE TITLE
Timpicker input is disabled

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#342]
### What happened?

The number input for the time picker are disabled because validation is not clarified rn.

### What type of frontend frameware are you seeing the problem on?

JavaScript

### Which version of iX do you use?

1.3.0

**Comment by silviowolf** [comment]
UX Weekly 2022-02-16:
- time inputs should be enabled to also type in
- Inputs should not show error states but handle invalid inputs by changing them to valid values
- input is not a number --> reset to previous valid value
- input number is > valid range --> set max valid value
- input number is < valid range --> set min valid value
