### ISSUE TITLE
Optional highlighting for "ix-menu-item"

### ISSUE THREAD

**Issue by alexkielburger** [siemens/ix#349]
### Suggestion / feature request

Add option to color "ix-menu-item" the same way, as the "About and legal information" or "Settings" are colored (change background color and add the small colored stripe at the left.).
![IX-Colored-Button](https://user-images.githubusercontent.com/124348905/216558758-30a03f0a-8929-4989-892d-6bb4ae8b0b65.PNG)

**Comment by silviowolf** [comment]
Hi @alexkielburger, I am not sure if I understand your request correct.
The ix-menu-item has a "selected" property. If set, the item will show up as you mentioned.
![image](https://user-images.githubusercontent.com/115155312/234811627-a9eb6f36-8da9-4481-bffd-94e6c46879ba.png)

Is this what you are looking for?

**Comment by alexkielburger** [comment]
Yes, that is, what I was looking for.
