### ISSUE TITLE
Click on IxMenuItem wrapped within 'More' is not propagated to the application

### ISSUE THREAD

**Issue by soundararaj-gayathri** [siemens/ix#351]
### What happened?

We are using the IxBasicNavigation with IxMenu in our React electron application. When the screen size is reduced and when the menu items gets wrapped within the 'More', then the click event on the menu item is not propagated to the application.
![image 70](https://user-images.githubusercontent.com/116714096/216569944-63598857-3d6b-47a9-9b3f-86b137229e7d.png)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.3.0

**Comment by goncalosard** [comment]
This is a problem with the current version of React. It has alot of problems with custom events. 
You can learn more here (https://custom-elements-everywhere.com/#react).

I made the following working example as a fix for this problem:
![image](https://github.com/siemens/ix/assets/63813420/9402cba8-bcf6-4a73-acb1-d025b5f0c392)
