### ISSUE TITLE
ix-tree-item properties and events not accessable 

### ISSUE THREAD

**Issue by philippsteinberg** [siemens/ix#354]
### What happened?

If you use the ix-tree item like described in the documentation the properties and events of the ix-tree-item are not accessable.
![grafik](https://user-images.githubusercontent.com/117842757/216957465-1d01b7a0-a789-480a-8150-faa98c82a9e8.png)

The ix-tree-item elements are generated out of the model during the runtime. 
So there is no easy way to bind the properties or events. In my case I want to bind the itemClick event to one of my angular methods

The only solution I found was going over the native elements every time I change the tree

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.3.0

**Comment by danielleroux** [comment]
If you want to define a custom tree item you need to define a renderItem template (https://ix.siemens.io/docs/controls/tree#custom-tree-node).

**Comment by philippsteinberg** [comment]
I have but also with the renderItem  I cannot bind any action to the ix-tree-item events itemClick and toogle
So also with the renderItem I have no idea how to register to these events

![grafik](https://user-images.githubusercontent.com/117842757/222695387-4042a1d9-42cc-46d4-8bf7-118c76746d42.png)

**Comment by danielleroux** [comment]
Ah now i know what you talking about! Unfortunately this are more internal events which will be used in parent component `ix-tree`, but dont worry we will not remove them.

I will discuess this in the Team.
