### ISSUE TITLE
Blind enhancement: Add option to show menu button in the blind header

### ISSUE THREAD

**Issue by silviowolf** [siemens/ix#358]
### Suggestion / feature request

For many usecases it could be helpful to be able to manipulate the content or the blind itself. Therefore a menu button would be helpful

**Comment by silviowolf** [comment]
Also related to #373

**Comment by silviowolf** [comment]
UX Weekly 2022-02-16:
- integrate the ability to place a button right aligned in the header of the blind

**Comment by silviowolf** [comment]
Planned in [IX-46](https://agileworld.siemens.cloud/jira/browse/IX-46)

**Comment by nuke-ellington** [comment]
#373
