### ISSUE TITLE
Make menu bar pinnable

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#359]
### Suggestion / feature request

It might be useful if menu bar could be pinnable when expanded (e.g. forced to stay expanded, if the user wants to).

Current behavior (using Map Navigation): when menu bar is expanded, it hides the content of sidebar behind, so user have to collapse it immediately after clicking on menu item to see appropriate content.

This is an example how e. g. Outlook handles this:

![Animation](https://user-images.githubusercontent.com/99844553/217220471-82da08c4-1fbe-491d-a974-1da5e78d4372.gif)

**Comment by silviowolf** [comment]
UX Weekly 2022-02-16:
- we see many usecases where this behavior would help

UX creates a design mockup to evaluate different behaviors to answer questions like:
- Is the pinning feature necessary or could the integrated layout be default?
- Are the icons the correct ones for the new behavior?
- where to place a pin icon best?
- Also consider coming mobile variants.

**Comment by silviowolf** [comment]
UX Weekly 2022-03-02
- Also consider 2nd level navigation
