### ISSUE TITLE
Navigation menu item: Colors for top and bottom items not as designed

### ISSUE THREAD

**Issue by silviowolf** [siemens/ix#363]
### What happened?

Top and bottom menu items should have different colors. Depending on the theme items look the same.  
Design:
![image](https://user-images.githubusercontent.com/115155312/217313339-84e83163-d439-416e-b3f8-0ec878ee3102.png)  

With this issue we should also remove the accent color line from the bottom items. This often leads to confusion as it looks very close to the selected main navigation item.
![image](https://user-images.githubusercontent.com/115155312/217315310-6575efc1-4bd4-4bdf-8141-b23b24280174.png)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.3.0

### Code to produce this issue.

```shell
-
```

**Comment by goncalosard** [comment]
@danielleroux @silviowolf 
"Top and bottom menu items should have different colors. Depending on the theme items look the same."
Is this color still an issue? They look diferent to me.

The following branch has the accent color line removed:  [fix/navigation-item-color](https://github.com/siemens/ix/tree/fix/navigation-item-color)

**Comment by silviowolf** [comment]
@goncalosard  
Yes it is still an issue. The items in the bottom slots should get in the selected state the background-color "theme-nav-item-secondary--background-selected". Currently they have "theme-color-1".
