### ISSUE TITLE
Missing properties for HTML-Table

### ISSUE THREAD

**Issue by neunteufelflorian** [siemens/ix#368]
### What happened?

Trying to view either the React-Example-Code or the Angular-Example-Code for either Table-Type (default, striped) results in page crash

![image](https://user-images.githubusercontent.com/119290892/217773778-aab713f8-3cda-476b-8893-b3acb2ebc6f9.png)

**Comment by danielleroux** [comment]
Fixed with fb0660c3764344e5a0f30e0b1e6e4e04f56d86a6

Will be deployed asap.
