### ISSUE TITLE
Failed to parse source map Error thrown at console when running npm start

### ISSUE THREAD

**Issue by hvg2416** [siemens/ix#372]
### What happened?

Hi. I followed the installation guidelines provided on https://ix.siemens.io/docs/installation/react to try out the Siemens IX.

I created a new react app using `npx create-react-app` command. And then installed the siemens/ix as dependency. It's working fine. But while running the `npm start` command, I noticed one error in the console. Refer attached screenshot for details.

![Screenshot 2023-02-13 at 12 05 56 AM](https://user-images.githubusercontent.com/49445823/218330336-860c9f6e-da2d-47ce-b08b-9054ad043c16.png)

I just thought to share it with the team in case this required any attention. or I may get some insight about the same.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

"@siemens/ix-react": "^1.3.0"

**Comment by danielleroux** [comment]
It's an issue in the create-react-app.

See:
https://github.com/facebook/create-react-app/discussions/11767

**Comment by hvg2416** [comment]
I see. Thank you @danielleroux  for providing the reference. 

Closing the issue.
