### ISSUE TITLE
Datepicker button/docs

### ISSUE THREAD

**Issue by nuke-ellington** [siemens/ix#384]
### Suggestion / feature request

TODOs:

- [ ] Document various buttons used to access the date picker (styleguide)
- [ ] Implement dedicated date button

![6aae580b-7fd8-4c16-827f-c0ca91b5e9f8](https://user-images.githubusercontent.com/14405078/219389862-a466f07b-efb4-476c-b14a-8b30122ad2b0.jpg)

**Comment by robert-wettstaedt** [comment]
Hello, I see this has been moved from 1.5.0 to 1.6.0 and then to 1.7.0. Is there any chance this is actually going to be released in 1.7.0? We need the datepicker button in on of our projects and if the release of that is still undetermined I need to figure out an alternative.

**Comment by robert-wettstaedt** [comment]
@danielleroux any updates on this?

**Comment by danielleroux** [comment]
Its on the track but we dont have a exact release date.

**Comment by danielleroux** [comment]
#737

**Comment by matthiashader** [comment]
Date Input will be delivered in #1318
