### ISSUE TITLE
menu item tooltip showing html for child elements

### ISSUE THREAD

**Issue by philippsteinberg** [siemens/ix#386]
### What happened?

if you provide a child component to ix-menu-item the tooltip will show the html of the child and not just the text

![grafik](https://user-images.githubusercontent.com/117842757/219581250-ac5e2d63-cc61-41de-adb9-3cdcc5906102.png)

I checked the ix code and the reason seems to be the componentDidRender method https://github.com/siemens/ix/blob/main/packages/core/src/components/menu-item/menu-item.tsx#L60

The innerHTML propery is used to extract the tooltip text. If the span contains a child element it will also use the html for the tooltip
const `newTitle = spanElement.innerHTML.replace('&amp;', '&');`

My suggestions would be to use the innerText propery instead or provide a way to override the tooltip with an additional property

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.3.0

### Code to produce this issue.

```shell
<ix-menu>
      <ix-menu-item home-tab tab-icon="home"> Home </ix-menu-item>
      <ix-menu-item tab-icon="globe">
        <a href="https://google.com">test</a>
      </ix-menu-item>
      <ix-menu-item tab-icon="star" disabled> Disabled Tab </ix-menu-item>
      <ix-menu-item tab-icon="star"> With other Icon </ix-menu-item>
      <ix-menu-item tab-icon="globe" style="display: none">
        Should not visible
      </ix-menu-item>
    </ix-menu>
```

**Comment by nuke-ellington** [comment]
Although technically possible it is not intended to have custom HTML inside of the menu items.
Per the iX styleguide only plain strings should be displayed in the navigation.
