### ISSUE TITLE
breadcrumb item does not update its label when label text changes when use ix with angular

### ISSUE THREAD

**Issue by angelina999990** [siemens/ix#387]
### What happened?

When use ix breadcrumb with angular, and change breadcrumb item while using, the label text doesn't get updated.

How to reproduce
1. ng serve to start an angular app with ix module important
2. pasted below code in a test.component.html;
3. change title to other content;
4. the breadcrumb content on the UI doesn't updated.
```html
        <ix-breadcrumb
            [ghost]="true"
            visibleItemCount="3"
            (itemClick)="handleBreadCrumbClick($event)"
        >
            <ix-breadcrumb-item
                label="Home"
            ></ix-breadcrumb-item>
            <ix-breadcrumb-item
                [label]="title"
            ></ix-breadcrumb-item>
        </ix-breadcrumb>
```

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.2.1

### Code to produce this issue.

```html
        <ix-breadcrumb
            [ghost]="true"
            visibleItemCount="3"
            (itemClick)="handleBreadCrumbClick($event)"
        >
            <ix-breadcrumb-item
                label="Home"
            ></ix-breadcrumb-item>
            <ix-breadcrumb-item
                [label]="title"
            ></ix-breadcrumb-item>
        </ix-breadcrumb>
```

```typescript
@Component({
    selector: 'test-breadcrumb',
    templateUrl: './test-breadcrumb.component.html',
    styleUrls: ['./test-breadcrumb.component.scss'],
})
export class ServiceHeaderComponent implements OnInit, OnDestroy {
    title = 'test';


    constructor(
        private _router: Router,
    ) {}

    ngOnInit(): void {
        this._router.events.pipe(filter((v) => v instanceof ActivationEnd)).subscribe((route) => {
            const { name } = (route as ActivationEnd).snapshot.data || {};

            if (name) {
                this.title = name;
            }
        });
    }
}
```

**Comment by nuke-ellington** [comment]
Appears to be a bug but as a workaround you could do something like this:

``` 
<ix-breadcrumb visibleItemCount="3">
      <ix-breadcrumb-item label="Home"></ix-breadcrumb-item>
      <ix-breadcrumb-item *ngFor="let item of items" [label]="item.label"></ix-breadcrumb-item>
</ix-breadcrumb>
```


```
items = [
    {
      label: 'title'
    }
];

ngOnInit(): void {
    this._router.events.pipe(filter((v) => v instanceof ActivationEnd)).subscribe((route) => {
        const { name } = (route as ActivationEnd).snapshot.data || {};

        if (name) {
            this.items = [
                { label: name },
        ];
    }
});
```

**Comment by angelina999990** [comment]
> Appears to be a bug but as a workaround you could do something like this:
> 
> ```
> <ix-breadcrumb visibleItemCount="3">
>       <ix-breadcrumb-item label="Home"></ix-breadcrumb-item>
>       <ix-breadcrumb-item *ngFor="let item of items" [label]="item.label"></ix-breadcrumb-item>
> </ix-breadcrumb>
> ```
> 
> ```ts
> items = [
>     {
>       label: 'title'
>     }
> ];
> 
> ngOnInit(): void {
>     this._router.events.pipe(filter((v) => v instanceof ActivationEnd)).subscribe((route) => {
>         const { name } = (route as ActivationEnd).snapshot.data || {};
> 
>         if (name) {
>             this.items = [
>                 { label: name },
>         ];
>     }
> });
> ```

Yes, I'm currently use this as a workaround
