### ISSUE TITLE
ix-dropdown-button not recognized

### ISSUE THREAD

**Issue by angelina999990** [siemens/ix#388]
### What happened?

[here](https://ix.siemens.io/docs/controls/dropdown-button) explained how to use ix dropdown button. But angular seems not recognized it while using.

version:
-  "@siemens/ix-angular": "^1.2.1",
- "@siemens/ix-icons": "^1.0.3",

![image](https://user-images.githubusercontent.com/6761706/219608989-7e940f06-6fe8-4aaf-99ec-607f87fd2f5d.png)
![image](https://user-images.githubusercontent.com/6761706/219609015-a3299502-4f33-4a6f-9b53-e8f3644301a3.png)

**Comment by nuke-ellington** [comment]
Please upgrade to Siemens iX version 1.3.0 or higher if you want to use the dropdown button since it wasn't available before that. Also note the _since 1.3.0_ badge in the docs :)
