### ISSUE TITLE
LoadingOverlay backdrop color not according Siemens brand

### ISSUE THREAD

**Issue by ThomasPoenicke** [siemens/ix#399]
### What happened?

when the loading overlay is shown, the backdrop has a different color than expected by Siemens brand

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.3.0

**Comment by silviowolf** [comment]
@ThomasPoenicke, could you please give a bit more detail like a screenshot snipped of the result of your loading overlay and what you would expect? Thanks.
