### ISSUE TITLE
Input text holder for date time pickers

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix#402]
### Suggestion / feature request

IX provides a open date time picker but normally projects use input text boxes, where on clikc would open the date picker or date time picker.

https://bootstrap-datepicker.readthedocs.io/en/latest/

**Comment by danielleroux** [comment]
Linked issue #324

**Comment by silviowolf** [comment]
Planned with https://agileworld.siemens.cloud/jira/browse/IX-19

**Comment by nuke-ellington** [comment]
Closed by #861
