### ISSUE TITLE
Input text boxes of type= number need up and down arrows too 

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix#404]
### What happened?

The input text boxes should support
->Intergers
-> Float numbers 

Please check Basic and Precision example here -  https://mdbootstrap.com/docs/standard/extended/number-inputs/

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

latest

**Comment by danielleroux** [comment]
@supreethaPavank 
we use native html `input` elements. You can already use number inputs. What is the issue here?

**Comment by supreethaPavank** [comment]
@danielleroux  - We need increment/decrement as well for both the input number fields. Does IX support this?

**Comment by nuke-ellington** [comment]
[IX-44]

**Comment by matthiashader** [comment]
Will be added by #1318
