### ISSUE TITLE
Component IxSelect displays options outside viewport

### ISSUE THREAD

**Issue by CptGeo** [siemens/ix#419]
### What happened?

When clicking on the Select field, the `ix-dropdown` component appears always under it, regardless of the position of the input.  

This leads to a problematic **UI/UX** when the Select component is located in the lower part of a page that only takes 100% of viewport height size (e.g. login page).   

Below you can see the described behavior: 

![demo](https://user-images.githubusercontent.com/25549211/222477426-9d7d71be-a9a6-4772-b7c4-29e7fe07d977.gif)

 

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.3.0

### Code to produce this issue.

```shell
// .tsx file

import "./TestPage.scss";
import { IxSelect, IxSelectItem } from "@siemens/ix-react";


export function TestPage(): JSX.Element {

	return (
		<>
			<div className="full-viewport-page">
				<div className="flex-container">
					<h1>Test page</h1>
					<footer>
						<IxSelect>
							<IxSelectItem label="Value 1" value="1"></IxSelectItem>
							<IxSelectItem label="Value 2" value="2"></IxSelectItem>
							<IxSelectItem label="Value 3" value="3"></IxSelectItem>
						</IxSelect>
					</footer>
				</div>
			</div>
		</>
	);
}
// .scss file

.full-viewport-page{
	min-height: 100vh;

	.flex-container {
		display: flex;
		flex: 1 0;
		height: 100vh;
		flex-direction: column;
		justify-content: space-between;
	}
}
```

**Comment by danielleroux** [comment]
Should be fixed with 1.4.0
