### ISSUE TITLE
HTML Table page example code leads to error

### ISSUE THREAD

**Issue by CptGeo** [siemens/ix#429]
### What happened?

I was browsing the [HTML Table](https://ix.siemens.io/docs/controls/html-grid/) page, and as soon as I clicked on `React` or `Angular` tabs to check the example code I got an error.  

The error occurs on both `Usage` and `Striped` examples.

You can see more below:  

![demo](https://user-images.githubusercontent.com/25549211/223112734-dc4d81a9-98a5-41d6-9d63-a3862de37f10.gif)

**Comment by danielleroux** [comment]
Should be fixed with latest deployment
