### ISSUE TITLE
Dropdown Items not displayed

### ISSUE THREAD

**Issue by georg-adler** [siemens/ix#433]
### What happened?

We are using the select control in one of our components. After upgrading to v1.4.0 the dropdown ist no longer opening when clicking it.
I can see that the items are present in the html. If it helps: the dropdown is placed inside a drawer.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

**Comment by danielleroux** [comment]
@georg-adler Have you some code to reproduce? And do you use editable = `true`

**Comment by georg-adler** [comment]
Can't really share the code here since it's hosted on code.siemens.com... I can try to recreate the issue in a fresh app when I have time. But since we didn't change anything but the ix-version it's hard to know what's causing it.

Only thing I saw in comparison to the docu page, is two classes that are not applied when opening the control:

erroneous component:
![image](https://user-images.githubusercontent.com/127318497/223741026-5470a6b9-ca3e-4e34-8cf1-5698f14f40d3.png)

documentation:
![image](https://user-images.githubusercontent.com/127318497/223740988-9c61e14e-2ca5-452a-a5c4-dea97b4badb3.png)

**Comment by nuke-ellington** [comment]
@georg-adler we already fixed the issue. A patch will be available later this week.

**Comment by georg-adler** [comment]
Wow, that was quick :D Thanks!
