### ISSUE TITLE
Icon position in form validation input fields

### ISSUE THREAD

**Issue by danielbruns93** [siemens/ix#440]
### Suggestion / feature request

Hey iX team,
does iX follow the principle for icon position inside Input fields/Chips/Selects like the following: 
"left aligned if icon is only an indicator and right aligned if icon is an icon-button and triggers an action"?

Group validation:
![image](https://user-images.githubusercontent.com/57394074/224315153-3de9ac72-2c75-419f-a710-4c3952f4d56c.png)
Expanding search:
![image](https://user-images.githubusercontent.com/57394074/224315946-3cd85789-612b-4766-aea8-b3f30dce8644.png)
Chip: 
![image](https://user-images.githubusercontent.com/57394074/224316124-29a161d9-69b6-438e-9eb1-bdf4ae841f69.png)
Select:
![image](https://user-images.githubusercontent.com/57394074/224316510-ec0318f7-75f6-4428-b7ad-29d9562bdaef.png)

-----

**My issue is: If applying this principle then the form validation should behave the same and not like it is current --> But for form validation I see anyway a problem if both icons will be placed right or left. Maybe there is another solution. **
![image](https://user-images.githubusercontent.com/57394074/224317110-c21177fe-ba8e-4586-8e0a-a33d28dc4fab.png)
Please correct me if I am wrong.

**Comment by silviowolf** [comment]
Hi @danielbruns93, you are right the generic principle is status/indicator icons before the text and actions at the right. And therefore the success check should actually be placed at the left. We will have a look at this.

**Comment by J-A-Hansen** [comment]
Hi @silviowolf, I agree to that success and error indicator should be in the place.

But if you place them on the left, wouldn't that lead to that the texts jumps surprisingly?
That already happens right now with the error indicator, what I do not find so nice (e.g. just try once pressing "Submit form" on https://ix.siemens.io/docs/controls/validation and then enter four letters in the last field and then remove one letter). When moving the success indicator to the left, that would even happen in success cases not only in error cases.

**Comment by silviowolf** [comment]
The overall form concept will be reworked with iX-830
