### ISSUE TITLE
Color preview

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#444]
### What happened?

The color bubbles beside the color variable names are the same.
See: https://ix.siemens.io/docs/theming/colors/

![image](https://user-images.githubusercontent.com/109066516/224979936-4f98e6cf-1b40-4f10-8998-fe84c92e636f.png)

It would be nice if these bubbles would have the color what it should have for better orientation.

**Comment by nuke-ellington** [comment]
Good catch. I appears as if this only happens if you deep-link/re-load the page. When navigating to the colors page the previews work.

**Comment by silviowolf** [comment]
Found 2 additional issues regarding the color preview:
- the color-circles should be 24x24 (currently 20x20)
- the chessboard pattern in the background is too detailed to be recognized on colors with opacity. Use this pattern image instead:  

![chessboard-pattern](https://user-images.githubusercontent.com/115155312/225863187-72cffb86-4686-4ecf-a880-f7bf97466de5.png)
