### ISSUE TITLE
ix tooltips don't disappear completely

### ISSUE THREAD

**Issue by SusiHorter** [siemens/ix#450]
### What happened?

I have multiple icons above each other and every icon has a tooltip. When I hover over one icon, the associated tooltip appears as expected. But if I hover over any icon at the hight of the tooltip before, the associated tooltip is not showing up.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

### Code to produce this issue.

```shell
<div *ngFor="let i of test">
  <div>
    <ix-icon name="info" color="color-primary" data-tooltip="tooltip"></ix-icon>
    <ix-tooltip for="[data-tooltip='tooltip']">tooltip</ix-tooltip>
  </div>
</div>
```

**Comment by SusiHorter** [comment]
This is still not working on my implementation

**Comment by danielleroux** [comment]
@SusiHorter Tested with latest version:

![tooltipissue](https://user-images.githubusercontent.com/2144313/226929449-859e7eab-064f-41aa-bc87-95b58c20396b.gif)
You can run the code by your own: https://stackblitz.com/edit/angular-hnqttb?file=src%2Fapp%2Ftooltip.html,src%2Fapp%2Ftooltip.ts
