### ISSUE TITLE
Enhanced version of date picker

### ISSUE THREAD

**Issue by besimgurbuz** [siemens/ix#460]
### Suggestion / feature request

Hi IX team,

I have a suggestion on date picker. In our team we crated an Angular library and that library has a date picker component ([project link in code.siemens.com](https://code.siemens.com/software-in-motion-tr/soul). It has dual calendar, time zone selection, quick range selections and hours selection in one card (it can be also single calendar or single date selection). It's already using by 4 different teams. The screenshot of the component;
![image](https://user-images.githubusercontent.com/33575384/226545445-24b8519a-68ff-4c3e-aeda-af315479318a.png)

I believe our date picker has a lot of good features. But I am the only contributor in that project and I think the same component can be added to IX. Lastly if you decide it's a good idea, I would love to contribute.

**Comment by danielleroux** [comment]
@besimgurbuz Our components are implemented with Stenciljs not with angular.

**Comment by besimgurbuz** [comment]
I agree, it's definitely not simple to integrate. Do you think this would be good component to have for IX @danielleroux?

**Comment by silviowolf** [comment]
Hi @besimgurbuz, thanks honestly for your offer. We have internally discussed the features of your date picker – also from an UX point of view. As we are already working on some enhancements of our component (like quick range) and some of the features of your picker don't fit to our concepts, we decided to stick to our current date picker component.
