### ISSUE TITLE
Icons for System Commands and Backup

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#472]
### Suggestion / feature request

Hi,

For the Industrial Edge Project we need Icons for System Commands. I think this is needed not only for the Industrial Edge Project and therefor I would like to request the icons from your side.
I have added some examples from google as well, for getting ideas.

Shutdown
![image](https://user-images.githubusercontent.com/109066516/228755402-c1cd0ba5-03bb-4a05-9a2f-5531fff8570e.png)

Reboot
![image](https://user-images.githubusercontent.com/109066516/228755521-735434d8-e07e-446e-9dc8-b90290cae4a4.png)

Reset
![image](https://user-images.githubusercontent.com/109066516/228755568-bc17562e-0562-453a-9503-b32943146d6d.png)

Hard Reset
![image](https://user-images.githubusercontent.com/109066516/228755663-5bbc3c1c-5f66-4265-84dd-73b31a663a82.png)
![image](https://user-images.githubusercontent.com/109066516/228755676-31e95cff-6fad-4e2a-ba8c-2ee2477dc5fe.png)

Backup
![image](https://user-images.githubusercontent.com/109066516/228754532-8ebc04f4-77a5-47a1-a5ff-2870e9899957.png)

Restore
![image](https://user-images.githubusercontent.com/109066516/228755355-2d365a67-8a7b-4b4e-adfa-da972743a480.png)

**Comment by silviowolf** [comment]
Hi @katjaKoppensteiner,  
agreed, all topics are generic and can be integrated in the iX icon library.
We do already have a "reset" icon.
![image](https://user-images.githubusercontent.com/115155312/230083255-0d62277d-39ba-4f85-8113-317e3efeff88.png).
The others will be created.  

My questions:
- What is the main difference between "reset" and "reboot"?
- Does the "hard reset" mean "reset to factory setings"?

**Comment by katjaKoppensteiner** [comment]
Hi @silviowolf 

Reset: soft reset where application related data wipes out and other settings will remain same.
Hard Reset: same as factory reset, it’s remove all the settings and data.
Reboot: just restart the device.

**Comment by silviowolf** [comment]
Following icons wil be added
![image](https://github.com/siemens/ix/assets/115155312/125ad0e5-7b36-4db3-957c-830608c2c444)
