### ISSUE TITLE
ix-select arrow navigation - visible indicator of selected option

### ISSUE THREAD

**Issue by florianprechtl** [siemens/ix#482]
### Suggestion / feature request

When the dropdown list of the ix-select box is open with its options it is already possible to navigate between the options.
The problem is that this state is **nowhere visibly indicated**. In the previous version (core-ui) there was a visible indicator.

I expect the result to be like this:
1. I click on the select box
2. The dropdown opens
3. The option sare focused
4. I can navigate between the options with my arrow keys
5. I can then submit my choice by enter

**Comment by nuke-ellington** [comment]
Will be fixed by iX 114
