### ISSUE TITLE
Theme switcher "setDefaultTheme", "getCurrentTheme" and usage with agGrid

### ISSUE THREAD

**Issue by DaveHOnCode** [siemens/ix#498]
### Suggestion / feature request

Hi there,

- [ ] I would be nice if you could set a defaultTheme (can already achieved by: `themeSwitcher.setTheme("theme-brand-dark")`)
- [ ] get the current theme as string
- [ ] get the current theme type (dark or light) as theme type
- [ ] also adapt the agGrid theme automatically by the theme switcher EDIT: It does seems like the theme already switches, but the text color does not, so thats maybe a bug?
- [ ] listen to changes of the preferred theme of the user from the operating system

Thank you so much in advance!

**Comment by danielleroux** [comment]
1. The default theme is always 'theme-classic-dark' you can set the inital(default) by adding the class to the body (https://ix.siemens.io/docs/theming/theme)
2. Good point!
3. Good point!
4. We have to check this. Your are correct the theme should switch already automaticly.
5. Good point!

I wil discuss the points with the team!
