### ISSUE TITLE
Tooltips are displayed overlapping with the icon below (AGGrid)

### ISSUE THREAD

**Issue by alexkielburger** [siemens/ix#500]
### What happened?

When using IX-Tooltips for Icons in the AGGrid, then in the first two rows the tooltips are shown below the icons. This causes the tooltips to be displyed below the icons of the row below, causing an overlap as shown in the image below.
![Tooltip_Bug](https://user-images.githubusercontent.com/124348905/235616142-cff8176b-e45b-4a79-9be2-098dfe0f4545.png)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.2

### Code to produce this issue.

```shell
<!--Example content of an AGGrid cell causing the issue. Use the index of the row (rowindex) to only have a single tooltip per row and not multipe-->
<ix-icon
      id="id-{{rowindex}}"
      name="eye"
      size="16"
>
</ix-icon>
<ix-tooltip for="#id-{{rowindex}}">Tooltip</ix-tooltip>
```

**Comment by danielleroux** [comment]
Cannot reproduce with latest 1.5.0.

![image](https://user-images.githubusercontent.com/2144313/235656502-afe1c97e-7e6f-40db-8823-f2af8e4680d4.png)
![image](https://user-images.githubusercontent.com/2144313/235656544-bf3f9df3-39ee-43ac-8a60-01d21d953a59.png)

-> https://stackblitz.com/edit/gjlgjv?file=src%2FApp.tsx

Implemented here with React but this should not change the behavior.

**Comment by danielleroux** [comment]
You can use stackblitz -> https://stackblitz.com/edit/k5zpnl?file=src%2Fapp%2Fexample-code.component.ts

Just reproduce the issue. Save and post the link.

**Comment by SusiHorter** [comment]
Hi @danielleroux,
finally I was able to reproduce the bug here: https://stackblitz.com/edit/k5zpnl-scme76?file=src%2Fapp%2Fboolean-cell-renderer%2Fboolean-cell-renderer.component.ts

**Comment by danielleroux** [comment]
> Hi @danielleroux, finally I was able to reproduce the bug here: https://stackblitz.com/edit/k5zpnl-scme76?file=src%2Fapp%2Fboolean-cell-renderer%2Fboolean-cell-renderer.component.ts

Unfortunately this is an issue regarding how ag grid angular is rendering the rows. You can avoid this by setting `suppressRowTransform: true`.

(Blue box => https://www.ag-grid.com/javascript-data-grid/row-spanning/#configuring-row-spanning)

**Comment by SusiHorter** [comment]
Okay, thank you very much. It worked.
