### ISSUE TITLE
[IxButton] Add a `loading` prop to the button

### ISSUE THREAD

**Issue by robert-wettstaedt** [siemens/ix#504]
### Suggestion / feature request

When users want to send some data to a service (eg. via a form) it makes sense to show a loading indicator of the pending request somewhere. Showing it in the submit button's state has the advantage that the user's attention is still on the button right after clicking it, making the indicator hard to miss. I suggest implementing a prop similar to [Ant Design](https://ant.design/components/button#components-button-demo-loading).

Example:
https://codesandbox.io/s/add-a-loading-prop-to-the-button-jwgysn

**Comment by silviowolf** [comment]
Hi @robert-wettstaedt, thanks for suggesting this. We discussed this in the UX team and agreeed on adding this feature to iX.

**Comment by nuke-ellington** [comment]
Feature added in #583
