### ISSUE TITLE
[IxMenu] Dynamically added menu items will be inserted into wrong DOM node

### ISSUE THREAD

**Issue by robert-wettstaedt** [siemens/ix#506]
### What happened?

After the initial render of the `IxMenu` I want to dynamically add menu items. Doing so will not insert the new menu items in the correct DOM node so the menu items are overlapping.

Steps to reproduce with the example below:

- Open the sidebar and verify that you only see the "Home" and "Example" menu items.
- Close the sidebar
- Click the "Add 1 menu item" button
- Open the sidebar and see that the new menu item got inserted into the wrong node

Interestingly, this only occurs when a menu item with the `home` prop is present. Removing the `home` prop of the "Home" menu item will result in a working example.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

1.4.2

### Code to produce this issue.

```shell
https://codesandbox.io/s/dynamically-adding-menu-items-will-be-inserted-into-wrong-dom-node-7wtvd7
```

**Comment by danielleroux** [comment]
Fill be fixed with #511
