### ISSUE TITLE
[Modal] The modal should be rendered into the existing React node tree

### ISSUE THREAD

**Issue by robert-wettstaedt** [siemens/ix#507]
### Suggestion / feature request

When I create and open a modal I would expect it to be rendered into the same React node tree where it is being called from. Instead, a new and separate React node tree is being created for the modal. This comes with many problems because now the modal is not able to access the same data as the rest of the application.

Examples:

- I want to render a link to a different page of my application in the modal. But it does not have access to the router that is used in the application so an error is thrown.
- I want to render some information that is being stored in a React context in the application tree. The modal cannot access the React context so I am unable to render the information.

<img width="440" alt="Screenshot_2023-04-27_at_11 42 04" src="https://user-images.githubusercontent.com/3035576/235884372-621462da-1a42-40e4-8d5b-988d27bf46b9.png">

Example:
https://codesandbox.io/s/the-modal-should-be-rendered-into-the-existing-react-node-tree-0lgkr9

**Comment by danielleroux** [comment]
@robert-wettstaedt sounds valid. 

Currently we create a new ReactDOM-Root for Modals (https://github.com/siemens/ix/blob/main/packages/react/src/modal/index.ts#L28). Better approche is to use Portal here.

**Comment by CagatayCanK** [comment]
Is there a workaround until this is changed?
I tried to set the ModalConfig.container but it didn't change anything.

**Comment by danielleroux** [comment]
@CagatayCanK 

Just a quick idea to pass the context via props into the modal, but iam not sure if this has some sideeffects.

```
const context = useContext(...);

showModal({
 content: <MyCustomModal {...context} />
});

```

**Comment by CagatayCanK** [comment]
> @CagatayCanK
> 
> Just a quick idea to pass the context via props into the modal, but iam not sure if this has some sideeffects.
> 
> ```
> const context = useContext(...);
> 
> showModal({
>  content: <MyCustomModal {...context} />
> });
> ```

Thanks but my issue is similar to router thing, its with the TanStack Query , it complains about : 
`No QueryClient set, use QueryClientProvider to set one`

**Comment by danielleroux** [comment]
@CagatayCanK Yes but what stops you to use the custom modal just for viewing results and make the "context" based logic inside the current react tree.

We working on a fix asap :)

**Comment by CagatayCanK** [comment]
@danielleroux 
Hey,
I tried this with 2.0.1 version but it looks like it is still outside the tree:
![image](https://github.com/siemens/ix/assets/18145716/b75a90ae-8655-4c4b-b338-05d8052c4e56)

I used the example from the documentation:

```
import { IxModalSize } from '@siemens/ix';
import { IxButton, Modal, ModalRef, showModal } from '@siemens/ix-react';
import React, { useRef } from 'react';

export default () => {
  const modalRef = useRef<ModalRef>(null);

  const open = (size: IxModalSize) => {
    showModal({
      size: size,
      content: (
        <Modal ref={modalRef}>
          <IxButton onClick={() => modalRef.current?.close(null)}>
            Modal with size {size}
          </IxButton>
        </Modal>
      ),
    });
  };

  return (
    <div className="modal-sizes-example">
      <IxButton onClick={() => open('360')}>Show modal size 360</IxButton>
    </div>
  );
};
```

**Comment by danielleroux** [comment]
Did you added the `IxApplicationContext`? (https://ix.siemens.io/docs/controls/modal#react)

**Comment by CagatayCanK** [comment]
> Did you added the `IxApplicationContext`? (https://ix.siemens.io/docs/controls/modal#react)

nope, didn't see that, adding that fixed it, thanks!
