### ISSUE TITLE
Corner radius for modals

### ISSUE THREAD

**Issue by flxlst09** [siemens/ix#509]
There is a discrepancy between the corner radius for Modals:

Figma: 4px
Implemented: 0.5rem

<img width="940" alt="modaldialog_cornerradius" src="https://user-images.githubusercontent.com/116285506/235901281-40090982-2646-478e-a29b-e5247bc7c64c.png">

**Comment by silviowolf** [comment]
Thanks, you're right. should be 0.25 rem instead.
Will be fixed.

**Comment by silviowolf** [comment]
0.5rem are coming from Bootstrap vaiables
