### ISSUE TITLE
Shadow css variable names are incorrect on this page 

### ISSUE THREAD

**Issue by negideepak** [siemens/ix#510]
### What happened?

Please refer to shadow documentation page https://ix.siemens.io/docs/theming/shadow
In this page there are shadow variable names are not correct and are not getting applied

Note: n stands for 1,2,3.....
`--theme-shadow-n`

**I found these working**
`--theme-box-shadow-lvl-n`

**Comment by danielleroux** [comment]
@negideepak We can not detect any issues regarding css shadow variables. We use them in components as well as in the documentation itself.
