### ISSUE TITLE
"Replacement Icon"

### ISSUE THREAD

**Issue by drebinge** [siemens/ix#513]
### Suggestion / feature request

Include an icon for replacing a file or data in the Industrial Icon System.

**Comment by silviowolf** [comment]
Hi @drebinge, you mean an icon for an action that replaces an element/data/file by another one, right?

**Comment by silviowolf** [comment]
Replace icon will be added:
![image](https://github.com/siemens/ix/assets/115155312/8023fa2d-8e2c-4fcb-8cb5-9eb707e08896)
