### ISSUE TITLE
feat: example playground web pages for integration with developer portal of siemens

### ISSUE THREAD

**Issue by sn0wcat** [siemens/ix#518]
### Suggestion / feature request

Could you please provide a few stackblitz examples with a set of controls which are common in industrial applications. (navigation, tab controls, etc.) which can be referred from the developer.siemens.com portal as playgrounds.

@danielleroux  as discussed, could you please also host the selection page for the demos so that we only have to create a link to the page?

**Comment by matthiashader** [comment]
[IX-997]
