### ISSUE TITLE
basic-navigation: dynamic added menu-item ignore slot property

### ISSUE THREAD

**Issue by philippsteinberg** [siemens/ix#528]
### What happened?

when I dynamicly add new menu-items with the property slot="bottom" in my angular application they are added on usual slot and not the bottom one
![nav-issue](https://github.com/siemens/ix/assets/117842757/173a9185-db8e-4fa1-aeef-59b32fc8ddc5)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.5.0

### Code to produce this issue.

```shell
https://codesandbox.io/p/sandbox/goofy-napier-7d41kt
```

**Comment by danielleroux** [comment]
@philippsteinberg Sadly this is issue which comes after the update of stencil 2 to stencil 3. We are analyzing this kind of issues.
