### ISSUE TITLE
Avatar LogIn / Logout and show whole name beside item

### ISSUE THREAD

**Issue by DaveHOnCode** [siemens/ix#529]
### Suggestion / feature request

Hi,

I'm missing the functionality of a login flow via the avatar Icon i. e.:

User is not logged in => "`user-profile`" icon => user clicks on it => login flow starts 

Also it would be nice to display a name beside the avatar, while the menu is expanded,
if The user is not logged in, it should show login or something similar

Thanks in advance!

**Comment by nuke-ellington** [comment]
@DaveHOnCode the ix-menu-avatar has two properties that top and bottom that can be used to display e.g. a user name next to the icon.
Defining a login flow is beyond the scope of the library but we could think about adding some more info on that to the docs.

Thanks for your feedback.

**Comment by DaveHOnCode** [comment]
Thanks for the properties, I was looking for something like `label` or `text`....

I agree, a login flow is out of the scope, I meant a possibility to initiate the login flow from the avatar, for example a click-event or something similar, if the user is loged out

Currently I don't even see the possibilty to customize the logut button (icon), only the text is customizable via the i18n option

In the current condition, you always assume a loged in user while using the avatar, and I don't think this is applicable for all use cases...

Thanks in advantage!

**Comment by nuke-ellington** [comment]
You can find the avatar API [here](https://ix.siemens.io/docs/controls/navigation/vertical-tabs#properties-ix-menu-avatar).
There you will also find a prop to set the image.
The absence of the login button is due to the fact that a user who is not logged in should typically not see the app at all. They should rather be forwarded to some form of login screen.
