### ISSUE TITLE
Modal animation direction

### ISSUE THREAD

**Issue by negideepak** [siemens/ix#532]
### Suggestion / feature request

Currently, when we implement ix-modals, then animation when popup loads is from top to bottom and when the popup is closing its bottom to top.

I think there must **options of changing modal animation direction** as below: 
1) **Opening**: From bottom to up, **closing**: From up to bottom
2) **Opening**: From left to right, **closing**: From right to left
3) visa-versa of 2

or if there is any way to do so in current implementation, **its not documented**

**Comment by nuke-ellington** [comment]
Hi @negideepak, thank you for your request.
Can you please give more insight about the use case that makes another direction of the animation neccessary?

**Comment by negideepak** [comment]
hi @nuke-ellington, thanks for that prompt reply

We have a use case where we are showing a **ix-button** which stays **as an overlay** and its placed **at bottom-right corner of the screen** and is going to be visible always.

Now, 

- [ ] modal should slide up from bottom when such a button is clicked (due to the fact that button is at bottom of the screen/ browser) 

- [ ] and should slide down when modal is closed by clicking cross icon of the modal

Thanks :)

**Comment by silviowolf** [comment]
Not planned in near future, but added to backlog.
REQ IX-870
