### ISSUE TITLE
Vue Form Validation library not stable

### ISSUE THREAD

**Issue by DaveHOnCode** [siemens/ix#566]
### What happened?

The library `vue-hooks-form` that is used in the example of Vue for the form validation is not stable and does not get maintenance on a regular base. I would recommending using another library, "VeeValidate" for example...

Maybe I can provide an example in course of the week, but I'm not sure about it...

**Comment by danielleroux** [comment]
Thats right vue-hooks-form is not maintenanced anymore. We decided to take the example offline. A new one is planned [IX-562].

**Comment by matthiashader** [comment]
Should be fixed with #1318 & #1239
