### ISSUE TITLE
Checkbox examples are not visible with Siemens Brand Styles

### ISSUE THREAD

**Issue by philippsteinberg** [siemens/ix#569]
### What happened?

Hi,

when you visit the checkbox component page https://ix.siemens.io/docs/controls/checkbox/
The examples are not visible with the Siemens Brand Dark and Siemens Brand light design

![grafik](https://github.com/siemens/ix/assets/117842757/75799c7d-2458-4db0-bedb-33effc8e31df)

![grafik](https://github.com/siemens/ix/assets/117842757/ac3112f2-3927-4b28-b572-7f29a69f87b3)

**Comment by danielleroux** [comment]
We are facing issues regarding stucking ci runners. Will be fixed asap as soon as GitHub schedules us a runner instance.

**Comment by danielleroux** [comment]
Should be work again!
