### ISSUE TITLE
All input elements should have the same backgroud color

### ISSUE THREAD

**Issue by philippsteinberg** [siemens/ix#570]
### What happened?

With the brand theme dark or light the radio button and checkbox have another background color than the text input and select

When we build a formular with multiple elements we have to override the style of the checkbox and radio button that it looks consistent

![grafik](https://github.com/siemens/ix/assets/117842757/54b00e5c-3a92-4afd-a986-4421a51ed9b3)
![grafik](https://github.com/siemens/ix/assets/117842757/757831f5-bfd9-4fc0-852b-3fbb3fa44159)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.6.0

**Comment by danielleroux** [comment]
According to Siemens Brand Guidelines not a bug.
