### ISSUE TITLE
Siemens iX Cypress plugin?

### ISSUE THREAD

**Issue by James-Richardson** [siemens/ix#573]
### Suggestion / feature request

We do a lot of testing with Cypress, but we find that some of our tests fail intermittently, and when they do, it's always the Siemens iX components (in particular, IxSelect and IxDropdown) that failed to function correctly.

One workaround that we've toyed with is to revert to normal selects, as these are easy to use in Cypress e.g.:

```
<select name="axis">
  <option value="x">X</option>
  <option value="y">Y</option>
  <option value="z">Z</option>
</select>
```

Which can then be manipulated in Cypress as follows:

```
  cy.get('[name=axis]').select('X');
```

When using ixSelect though, the operation becomes more fiddly. Our code to do it currently looks like this:

```
  cy.get('[name=axis]')
    .find('ix-icon.chevron')
    .click();

  cy.get('[name=axis]')
    .find('button.dropdown-item')
    .contains('X')
    .should('be.visible')
    .click();
```

And that routine is a) the result of many hours of effect (that presumably everyone who wants to test an app that uses Siemens iX in Cypress has to also go through), and b) some (but not all, strangely) tests that use this fail intermittently.

So, it would be nice if there was a Siemens iX Cypress plugin that allowed us to do something like this:

```
cy.get('[name=axis]').ixselect('X');
```
And that succeeded consistently when executed.

**Comment by danielleroux** [comment]
> We do a lot of testing with Cypress, but we find that some of our tests fail intermittently, and when they do, it's always the Siemens iX components (in particular, IxSelect and IxDropdown) that failed to function correctly.

Can you provide some reproducible demo project or more details about the issue that occurs e.g a stacktrace.
