### ISSUE TITLE
Allow styling of shadow DOM

### ISSUE THREAD

**Issue by luispoehl** [siemens/ix#584]
### Suggestion / feature request

With the current version of 1.6.x we can not style any elements anymore, because of the shadow dom.
I request to enable individual styling of elements in future versions, again.
A possible solution would be to allow the pseudo element ::part(), [as seen here. ](https://developer.mozilla.org/en-US/docs/Web/CSS/::part)

Thanks in advance.
Best regards,
Luis Pöhlmann

**Comment by danielleroux** [comment]
@luispoehl can you please give us more insight into which elements you are trying to style individually.
Our main focus as a design system is to deliver a consistant UI Design over various applications. Therefore its not encouraged to overwrite stylings of components.

**Comment by YurBerkay** [comment]
@danielleroux e.g. we wanted to adjusted the width of a button. It is not possible without using refs and js:
![image](https://github.com/siemens/ix/assets/136796191/3a281e43-9cab-4b51-8b44-a79a9327e487) in version 1.4 it is possible to adjust the stylings. We do not want to change the whole design, we only want to make minor adjustments to fit our needs.

Best regards,
Berkay Yurdagül
