### ISSUE TITLE
Angular prod build size increased drastically after migration to Siemens IX 

### ISSUE THREAD

**Issue by paresh16061990** [siemens/ix#585]
### What happened?

Earlier, we were using angular+bootstrap, which was producing almost 3~4 mb of prod build with very few files(Hardly 5 js file main, pollyfills, runtime, scripts), but after shifting to angular + Siemens IX the build size increase drastically to ~11 mb with lot of files(80-90) in prod build.
![ErrorPage](https://github.com/siemens/ix/assets/136799343/f058852a-d5e3-4695-9cc8-62dfe86d3569)

Attaching screen shot of same 

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

1.5.0

**Comment by danielleroux** [comment]
Checked with latest angular release and latest ix release we have a prod folder size of around 5 MB.
You have to considure that the prod folder size does nothing to say about the network performance of the application.

iX and Angular are doing lazy loading of vendor or resource files. In this case i analyzed this with a new application and the first load of an angular application is only around 1MB

![image](https://github.com/siemens/ix/assets/2144313/ecb918de-112e-4db4-8fd6-a448786ce028)

**Comment by paresh16061990** [comment]
but not clue what other files it generating after migration, and those all combined file size ~11mb which negatively impacting performance of application as it tends to load entire 11 mb in client browser which taking significant time if network is slower

**Comment by danielleroux** [comment]
Please provide a github project and try to reproduce the behavior

**Comment by danielleroux** [comment]
Stale issue if the, problem still existing or have to me address please create a new issue.
