### ISSUE TITLE
dropdown-menu active color not using theme variable

### ISSUE THREAD

**Issue by Tiagogv** [siemens/ix#588]
### What happened?

When using Siemens IX styles for a dropdown the active class background-color does not inherit from a theme variable and is currently fixed to #0d6efd.

### What type of frontend frameware are you seeing the problem on?

Angular, React, JavaScript, Others

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
<div class="dropdown-menu>
 <button class="dropdown-item active">
 </button>
</div>
```

**Comment by danielleroux** [comment]
Not reproducible with latest version. If the issue is still a point, please reopen this issue and adapt the description.
