### ISSUE TITLE
DatePicker/DatetimePicker not updated when date changes

### ISSUE THREAD

**Issue by PRGfx** [siemens/ix#593]
### What happened?

To use the element as a controlled component I would expect it to change with the input values.
The element will receive an updated `from` prop and I can query the updated `from` property of the `DatetimePicker` custom element (as well as the underlying `DatePicker`) for example through the browser console, but the component will not be rerendered, it seems (in that sense it applies to JS only as well, I think).

My use-case at hand is textfield as alternative input mode to the date-time-picker.

https://stackblitz.com/edit/bdvzaq?file=src%2Fdatetimepicker.tsx Link for the example code in this issue

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

1.6.0

### Code to produce this issue.

```shell
import { IxDatetimePicker } from '@siemens/ix-react';
import { IxDatetimePickerCustomEvent } from '@siemens/ix';
import React from 'react';

const lpad = (n: number): string => `0${n}`.slice(-2);
const formatDate = (date: Date): string | undefined => {
  if (!date) return undefined;

  return [
    date.getFullYear().toString(),
    lpad(date.getMonth() + 1),
    lpad(date.getDate()),
  ].join('-');
};

const datePickerDelimiter = '|';

export default () => {
  const [value, setValue] = React.useState(new Date());

  const resetDate = () => {
    setValue(new Date());
  };

  const handleDone = (e: IxDatetimePickerCustomEvent<string>) => {
    const dateParts = e.detail.split(datePickerDelimiter);
    const datePart = dateParts[0];
    const timePart = dateParts.pop();

    if (!datePart || !timePart) {
      return;
    }

    const selectedDate = new Date(`${datePart} ${timePart}`);
    setValue(selectedDate);
  };

  return (
    <div>
      <button onClick={resetDate}>Reset date</button>
      {value.toLocaleString()}
      <IxDatetimePicker
        from={formatDate(value)}
        dateFormat="yyyy-LL-dd"
        range={false}
        eventDelimiter={datePickerDelimiter}
        onDone={handleDone}
      />
    </div>
  );
};
```

**Comment by nuke-ellington** [comment]
We are currently re-implementing the date and time picker components (#737 ).
The new components will have the desired behavior.
