### ISSUE TITLE
Add lable for "ix-menu-about" inside menu

### ISSUE THREAD

**Issue by marvingreeven** [siemens/ix#595]
### Suggestion / feature request

Right now the property "label" at the "[ix-menu-about](https://ix.siemens.io/docs/controls/navigation/about-and-legal#properties-ix-menu-about)" item just sets the label at the top.
The label inside the menu is not affected.

![tempsnip](https://github.com/siemens/ix/assets/109358527/9c68f4bd-4b44-4289-9644-f1372c87c112)
![image](https://github.com/siemens/ix/assets/109358527/c9138fe2-5746-4c63-b398-87ee3cfb7d0b)

**Comment by danielleroux** [comment]
@marvingreeven Currently you have to provide the about item label inside the ix-menu

```html
<ix-menu i18nLegal="{{ '~086e3 About and Legal Information' | translate }}">
        <ix-menu-about>
          <ix-menu-about-item label="Tab 1">Content 1</ix-menu-about-item>
          <ix-menu-about-item label="Tab 2">Content 2</ix-menu-about-item>
        </ix-menu-about>
</ix-menu>
```
