### ISSUE TITLE
Burger icon not displayed in header

### ISSUE THREAD

**Issue by mohitmutha** [siemens/ix#606]
### What happened?

I have added the below code
```
<IxBasicNavigation>
  <div className="placeholder-logo" slot="logo"></div>
  <IxMenu ref={ref}>
    <IxMenuAbout>
      <IxMenuAboutItem label="Tab 1">Content 1</IxMenuAboutItem>
      <IxMenuAboutItem label="Tab 2">Content 2</IxMenuAboutItem>
    </IxMenuAbout>
  </IxMenu>
</IxBasicNavigation>
```

As per the documentation I should see the burger icon for expanding the menu in the header
![image](https://github.com/siemens/ix/assets/5111605/8b1ca7fe-19a2-421e-a0e7-893b26ce8da4)

However what I see is 
![image](https://github.com/siemens/ix/assets/5111605/60568674-1857-4eea-adf7-3a65da126349)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

latest

### Code to produce this issue.

```shell
<IxBasicNavigation>
  <div className="placeholder-logo" slot="logo"></div>
  <IxMenu ref={ref}>
    <IxMenuAbout>
      <IxMenuAboutItem label="Tab 1">Content 1</IxMenuAboutItem>
      <IxMenuAboutItem label="Tab 2">Content 2</IxMenuAboutItem>
    </IxMenuAbout>
  </IxMenu>
</IxBasicNavigation>
```

**Comment by danielleroux** [comment]
@mohitmutha Its depends on your sceen size. Make the browser window smaller and you will see that the menu will be inside the header
