### ISSUE TITLE
[IxTree] Allow custom item height

### ISSUE THREAD

**Issue by james-williams-siemens** [siemens/ix#616]
### Suggestion / feature request

IxTree item height is currently [fixed to 32px](https://github.com/siemens/ix/blob/b6404093904e265a35459a7cf518911763c21939/packages/core/src/components/tree/tree.tsx#L120)  sometimes we would like it to be smaller (in particular 24px) so the tree takes up less space and requires less scrolling, is it possible the item height could be specified via a property?

**Comment by silviowolf** [comment]
Hi @james-williams-siemens, thanks for your suggestion. I can understand that requirment, but beside the less scrolling a smaller item height has also some other side effects we need to consider. We will therefore discuss this internally.

**Comment by silviowolf** [comment]
Will not be available in near future but added as requirement to backlog.
REQ iX-888
