### ISSUE TITLE
Components flexibility

### ISSUE THREAD

**Issue by damien-balthazard-ext-siemens** [siemens/ix#619]
### Suggestion / feature request

We want to implement the components as part of a touch interface. 
It is an internal Siemens application using the Brandville theme. 
We noticed the lack of flexibility of the components and this is very limiting for us because of the override of the css classes. 
For example, we would like to be able to enlarge the size of the buttons, this being too small in the case of the touch screens we have. 

Have you planned anything to improve this ? 
If not, can you integrate size management in the components, or allow to use the classes provided by bootstrap ? 
Continuing the previous example, being able to use ```btn-lg``` to make the button bigger.

**Comment by nuke-ellington** [comment]
@damien-balthazard-ext-siemens Thank you for reaching out. Since this is a very interessing topic I would like to set up a call where you can share more details about your use case and requirements. Feel free to send an invite or share you contact info with me :)

**Comment by danielleroux** [comment]
Stale
