### ISSUE TITLE
[IxToggle] Add ControlValueAccessor for Angular Forms Support.

### ISSUE THREAD

**Issue by WanielDeiss** [siemens/ix#627]
### Suggestion / feature request

Hey,
we'd like to use the ix-toggle component in Angular with the ReactiveForms, but we're getting an error.
"NG01203: No value accessor for form control with name: 'toggle'."

Our example form:
```html
<form [formGroup]="exampleForm">
  <ix-toggle formControlName="toggle" />
</form>
```

```typescript
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  exampleForm = this.fb.group({
    toggle: [false],
  });
  constructor(private fb: FormBuilder) {
    this.exampleForm.valueChanges.subscribe((val) => {
      console.log('exampleForm valueChanges', val);
    });
  }
}
```

Here is a Stackblitz with a toggle component and the ControlValueAccessor implementation.

https://stackblitz.com/edit/angular-szsw3k?file=src%2Fapp%2Fswitch%2Fswitch.component.ts

**Comment by danielleroux** [comment]
🚢 in v2
