### ISSUE TITLE
Order of card element items

### ISSUE THREAD

**Issue by danielbruns93** [siemens/ix#629]
### Suggestion / feature request

We would like to follow the order of the Brandville card element: 
1. Card headline
2. Subheadline
3. KPI
4. Card link
- all of this items should be able to show or hide

It would be a great benefit for many of our projects if this order can be set directly via the component properties.

**Comment by danielleroux** [comment]
The current released and documentated cards (Push/Action Card) are based on the `ix-card` which gives more flexibility to create specific cards. 
These `ix-cards` are already part of the library (#542) but not released in the documentation yet. This will introduced in the upcoming releases.

**Comment by nuke-ellington** [comment]
Cards where officially released with iX 1.6.0
