### ISSUE TITLE
Form validation while typing

### ISSUE THREAD

**Issue by danielbruns93** [siemens/ix#633]
### Suggestion / feature request

We would love to have "form validation while typing". 

There are several scenarios where such a validation is necessary. This would be our prioritization:

1.	Required input fields: There are specific input fields that are mandatory for successful completion of the form. By adding form validation while typing inside the field, we could ensure that users fill out these fields before submitting the form.

2.	Risk of invalid input: In some input fields, there is a risk of users entering invalid data. By implementing validation rules, we could ensure that only valid data is accepted, thereby avoiding errors.

3.	Dependencies between input fields: In certain forms, input fields may depend on each other. By using form validation, we could ensure that these dependencies are handled correctly (e.g. the user added the post-code of Hamburg in "Post code" field, directly after that shout "Hamburg" be added in the field "City") and the form receives consistent data.

I propose that form validation occur as fields are entered to provide immediate feedback to users and improve usability.

Many thanks :)

**Comment by danielbruns93** [comment]
Are there any news for this issue? :)

**Comment by danielleroux** [comment]
Form validation during typing dependes on you application logic. You can validate a form, by change,blur,submit, etc. Dependens on your logic.

e.g react with react-form-hooks: https://codesandbox.io/s/react-hook-form-validation-onblur-onchange-pnq16?file=/src/index.js

The component can handle `is-valid` or `is-invalid` class also the input state itself `:valid` / `:invalid`

**Comment by nuke-ellington** [comment]
Duplicate #981
