### ISSUE TITLE
Angular Test App Improvements

### ISSUE THREAD

**Issue by WanielDeiss** [siemens/ix#639]
### Suggestion / feature request

Hello everyone,
the angular-test-app is currently on Angular 14, and Angular 16 introduced the [Standalone Components](https://angular.io/guide/standalone-components). This allows us to reduce the size of [app.module.ts](https://github.com/siemens/ix/blob/main/packages/angular-test-app/src/app/app.module.ts) and make it more transparent which modules are now necessary for these Ix components.
Additionally, I wanted to ask if it's possible to create an index page with all the components/pages in the test application. This way, we wouldn't have to search for the path in [app-routing.module.ts](https://github.com/siemens/ix/blob/main/packages/angular-test-app/src/app/app-routing.module.ts).
I would be happy to take care of it and submit it as a pull request, unless there are any objections.

**Comment by danielleroux** [comment]
We didn't know that someone is using the test apps for a component search based on the configured routes. We are never then less planned to change how this test apps are generated. Currently its completly manual work (for the examples itself and also for the routing entry).

Our idea for future developementsteps was to generate the routing entries based on the existing examples.

If you wanted to generate a index site, do you want to create in once static or dynamic based on existing routes/examples.

**Comment by danielleroux** [comment]
Stale issue. If the issue is still a point, please reopen this issue and adapt the description.
