### ISSUE TITLE
ix-basic-navigation: Not including the nested menu throws an error and breaks the style.

### ISSUE THREAD

**Issue by intuiquest** [siemens/ix#644]
### What happened?

When a user is not signed in, we aim to keep the header visible and dynamically hide the menu.

<img width="359" alt="image" src="https://github.com/siemens/ix/assets/140149189/7812fcab-f9be-4ae0-bf1c-2cd4439c3f79">

In version 1.6.3, dynamically hiding the menu via ngIf:
- does not adjust margins properly
- throws some errors on click.

<img width="825" alt="image" src="https://github.com/siemens/ix/assets/140149189/bf33a254-e22c-4415-9c8f-dba2a59cecaa">

Here's the current CSS workaround I'm using:

<img width="547" alt="image" src="https://github.com/siemens/ix/assets/140149189/64e8ae37-eb9c-495b-8811-35baac2fb287">

Ideally, the ix-basic-navigation component should dynamically adapt both styling and mouse events based on the presence of the nested menu.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.6.3

**Comment by danielleroux** [comment]
Fixed with #592
