### ISSUE TITLE
<ix-tabs>selected property only works on the first time

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#645]
### What happened?

I have a form are not submitted in a tab,  and I wish the user can not navigate to the other tabs before they submit this form.
I made three examples but all of them can not work as expected.
The selected property only works on the content part but not works on the tabs except the first time. I hope the selected tab and content should always keep the same index.
![tabs](https://github.com/siemens/ix/assets/10339536/ad93e1e5-9de1-460b-af83-240f8c99bf4c)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-testpage',
  template: `
    <div class="example">
      <ix-tabs [selected]="selectedTab">
        <ix-tab-item (click)="changeTab(0)">Tab 1</ix-tab-item>
        <ix-tab-item (click)="changeTab(1)">Tab 2</ix-tab-item>
        <ix-tab-item (click)="changeTab(2)">Tab 3</ix-tab-item>
      </ix-tabs>
      <div *ngIf="selectedTab === 0">Content Tab 1</div>
      <div *ngIf="selectedTab === 1">Content Tab 2</div>
      <div *ngIf="selectedTab === 2">Content Tab 3</div>
    </div>
  `,
  styles: [],
})
export class TestpageComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {}

  selectedTab = 1;

  changeTab(tabIndex: number) {
    this.selectedTab = tabIndex;
    this.selectedTab = 1;
  }
}


----------------------------------------------
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-testpage',
  template: `
    <div class="m-5">
      <ix-tabs [selected]="selectedTab">
        <ix-tab-item (click)="changeTab(0)" [selected]="selectedTab == 0"
          >Tab 1</ix-tab-item
        >
        <ix-tab-item (click)="changeTab(1)" [selected]="selectedTab == 1"
          >Tab 2</ix-tab-item
        >
        <ix-tab-item (click)="changeTab(2)" [selected]="selectedTab == 2"
          >Tab 3</ix-tab-item
        >
      </ix-tabs>
      <div *ngIf="selectedTab === 0">Content Tab 1</div>
      <div *ngIf="selectedTab === 1">Content Tab 2</div>
      <div *ngIf="selectedTab === 2">Content Tab 3</div>
    </div>
  `,
  styles: [],
})
export class TestpageComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {}

  selectedTab = 1;

  changeTab(tabIndex: number) {
    this.selectedTab = tabIndex;
    this.selectedTab = 1;
  }
}


-----------------------------------------------
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-testpage',
  template: `
    <div class="m-5">
      <ix-tabs>
        <ix-tab-item (click)="changeTab(0)" [selected]="selectedTab == 0"
          >Tab 1</ix-tab-item
        >
        <ix-tab-item (click)="changeTab(1)" [selected]="selectedTab == 1"
          >Tab 2</ix-tab-item
        >
        <ix-tab-item (click)="changeTab(2)" [selected]="selectedTab == 2"
          >Tab 3</ix-tab-item
        >
      </ix-tabs>
      <div *ngIf="selectedTab === 0">Content Tab 1</div>
      <div *ngIf="selectedTab === 1">Content Tab 2</div>
      <div *ngIf="selectedTab === 2">Content Tab 3</div>
    </div>
  `,
  styles: [],
})
export class TestpageComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {}

  selectedTab = 1;

  changeTab(tabIndex: number) {
    this.selectedTab = tabIndex;
    this.selectedTab = 1;
  }
}
```

**Comment by chencc1988** [comment]
Another Issue is about the disabled property.  The data bindings are not really correctly works.  Please notice on the underline below the tab.  The behavior are different between disabled and [disabled ]
![disabled](https://github.com/siemens/ix/assets/10339536/635fb3a7-3c93-4ef6-a7ea-e3e977dea4de)


```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-testpage',
  template: `
    <div class="m-5">
      <ix-tabs>
        <ix-tab-item (click)="changeTab(0)" disabled
          ><ix-icon name="success"></ix-icon
        ></ix-tab-item>
        <ix-tab-item (click)="changeTab(1)"
          ><ix-icon name="success"></ix-icon
        ></ix-tab-item>
        <ix-tab-item (click)="changeTab(2)" disabled
          ><ix-icon name="success"></ix-icon
        ></ix-tab-item>
      </ix-tabs>
      <div *ngIf="selectedTab === 0">Content Tab 1</div>
      <div *ngIf="selectedTab === 1">Content Tab 2</div>
      <div *ngIf="selectedTab === 2">Content Tab 3</div>
    </div>
    <div class="m-5">
      <ix-tabs>
        <ix-tab-item (click)="changeTab(0)" [disabled]="selectedTab != 0"
          ><ix-icon name="success"></ix-icon
        ></ix-tab-item>
        <ix-tab-item (click)="changeTab(1)" [disabled]="selectedTab != 1"
          ><ix-icon name="success"></ix-icon
        ></ix-tab-item>
        <ix-tab-item (click)="changeTab(2)" [disabled]="selectedTab != 2"
          ><ix-icon name="success"></ix-icon
        ></ix-tab-item>
      </ix-tabs>
      <div *ngIf="selectedTab === 0">Content Tab 1</div>
      <div *ngIf="selectedTab === 1">Content Tab 2</div>
      <div *ngIf="selectedTab === 2">Content Tab 3</div>
    </div>
  `,
  styles: [],
})
export class TestpageComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {}

  selectedTab = 1;

  changeTab(tabIndex: number) {
    this.selectedTab = tabIndex;
    this.selectedTab = 1;
  }
}

```

**Comment by nuke-ellington** [comment]
To me it looks like this line will always select the same tab:

`    this.selectedTab = 1;
`

**Comment by goncalosard** [comment]
@danielleroux @nuke-ellington @chencc1988  Tested the examples given. To me everything looks correct.
It is obvious with code example given that when the user changes tab, the content stays the same:

  changeTab(tabIndex: number) {
    this.selectedTab = tabIndex;
    this.selectedTab = 1; <--- this line makes the content always be the same.
  }

That line should be removed by the user, because it is not the correct way.
If the user wants as it was said "I wish the user can not navigate to the other tabs before they submit this form", then tabs should be disabled until the user submits the form.


For the second problem. I also tested the given examples and I do not get any problem. Disabled tabs work corretcly, and when clicked or hovered nothing happens.

**Comment by chencc1988** [comment]
Sorry, I have to say that disable the other tabs does not cover all use cases. Because the disabled tab means the user should not click it.  Sometimes we should make the user notice that all tabs are available otherwise they will think they do not have the access rights to enter this tab.
I will post more information to show my use case tomorrow.
@goncalosard

**Comment by chencc1988** [comment]
In my use case, the tabs can be created by users to show user defined dashboards. Users modify their dashboards to their needs, and the changes are recorded in the state machine for undo and redo operations.

When users switch to another dashboard, they may not realize that the current dashboard has not been saved. Jumping directly to a different dashboard may result in the loss of previous dashboard editing status. So we need to pop up a dialog to remind the user that they need to save or discard the changes. After completing the operation, users can leave the tab.

If you make a change during the editing of a dashboard, all other tabs become disabled, and when you undo the change, the other dashboards return to the available state. This will look a little funny



![dashboard1](https://github.com/siemens/ix/assets/10339536/3768b90d-8b0a-40c9-9f7c-02c6a1340e2a)

**Comment by danielleroux** [comment]
@chencc1988 That's correct especial your use case cannot be handled with current implementation of the tabs. 

We can implement something like that:

```tsx
        <ix-tabs
          onSelectedChange={(event) => {
            event.preventDefault();
            console.log(event);
          }}
        >
          <ix-tab-item onTabClick={(event) => event.preventDefault()}>
            Item 1
          </ix-tab-item>
          <ix-tab-item>Item 2</ix-tab-item>
          <ix-tab-item>Item 3</ix-tab-item>
        </ix-tabs>
        <div style={{ marginTop: '2rem', background: '#ff0000aa' }}>
          {this.tabIndex}
        </div>
```

You can then "preventDefault" the `tabClick` or `selectedChange` event, which stops the tabs to change the tab.

**Comment by chencc1988** [comment]
@danielleroux
I think it is because the Angular change detection issue. I made an example to show that. The workaround is to change the tab asynchronously in click call back function
https://stackblitz.com/edit/angular-pr2h46-vtnzne?file=src%2Fapp%2Fexample.component.ts

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
  <div class="example">
  <ix-tabs [selected]="selectedTab">
    <ix-tab-item (click)="changeTab(0)">Tab 1</ix-tab-item>
    <ix-tab-item (click)="changeTab(1)">Tab 2</ix-tab-item>
    <ix-tab-item (click)="changeTab(2)">Tab 3</ix-tab-item>
  </ix-tabs>
  <div *ngIf="selectedTab === 0">Content Tab 1</div>
  <div *ngIf="selectedTab === 1">Content Tab 2</div>
  <div *ngIf="selectedTab === 2">Content Tab 3</div>
</div>
  `,
})
export default class Blind {
  constructor() {}
  ngOnInit(): void {}

  selectedTab = 1;

  changeTab(tabIndex: number) {
    //this line won't lock tab to index 1
    //this.selectedTab = 1;

    // following lines lock tab to index 1
    this.selectedTab = tabIndex;
    setTimeout(() => (this.selectedTab = 1), 0);
  }
}
```
I think it is not the issue of IX itself.  You can close the issue if you think the workaround is acceptable

**Comment by danielleroux** [comment]
> @chencc1988 That's correct especial your use case cannot be handled with current implementation of the tabs.
> 
> We can implement something like that:
> 
> ```tsx
>         <ix-tabs
>           onSelectedChange={(event) => {
>             event.preventDefault();
>             console.log(event);
>           }}
>         >
>           <ix-tab-item onTabClick={(event) => event.preventDefault()}>
>             Item 1
>           </ix-tab-item>
>           <ix-tab-item>Item 2</ix-tab-item>
>           <ix-tab-item>Item 3</ix-tab-item>
>         </ix-tabs>
>         <div style={{ marginTop: '2rem', background: '#ff0000aa' }}>
>           {this.tabIndex}
>         </div>
> ```
> 
> You can then "preventDefault" the `tabClick` or `selectedChange` event, which stops the tabs to change the tab.

We implemented an additional tab-click event this can be prevented. In this case no navigation will happen.
