### ISSUE TITLE
<ix-tabs> need remove icon on tabs

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#649]
### Suggestion / feature request

In our project, we need to create tabs and remove tabs dynamically. However now the IX does not provide a solution

**Comment by nuke-ellington** [comment]
Thank you for the feedback @chencc1988. Can you please clarify what you are trying to achieve? Do you want to set tabs dynamically or show/hide icons inside of tabs?

**Comment by chencc1988** [comment]
My idea is very similar to the demo of [this one](https://junaidqadir.com/backyard/bootstrap_add_rmove_tabs/). I believe that after watching this demo, you will feel my thoughts directly.

**Comment by nuke-ellington** [comment]
Here is some example code to guide you:

```
<ix-tab-item>
  <span>
    Tab name
    <ix-icon-button  ghost size="12" icon="close"></ix-icon-button>
  </div>
</ix-tab-item>
```
