### ISSUE TITLE
Industrial icon for electrical energy

### ISSUE THREAD

**Issue by drebinge** [siemens/ix#653]
### Suggestion / feature request

Please add an industrial icon for electrical energy to Siemens iX

**Comment by silviowolf** [comment]
Hi @drebinge, icon in backlog.

**Comment by silviowolf** [comment]
will be added with next icon-font release
name:
electrical-energy(-filled)

**Comment by drebinge** [comment]
Hi Silvio,

Would you already send me a preview of the electrical energy icon? I am just writing a user story where need this icon (UI is part of my user stories)?

With best regards,
Konrad Drebinger

Siemens AG
Digital Industries
Process Automation
Product Owner and Scrum Master
DI PA SW PRM 2
Siemenspromenade 3
91058 Erlangen, Germany
Software for Process Industries<https://www.siemens.com/global/en/products/automation/topic-areas/process-industries/software-for-process-industries.html>
Phone: +49 (9131) 17-32758
Fax.: +49 (18) 6878
Mobile: +49 (173) 6578336
***@***.***
www.siemens.com<about:blankwww.siemens.com>
[Logo]
Siemens Aktiengesellschaft: Chairman of the Supervisory Board: Jim Hagemann Snabe; Managing Board: Roland Busch, Chairman, President and Chief Executive Officer; Cedrik Neike, Matthias Rebellius, Ralf P. Thomas, Judith Wiese; Registered offices: Berlin and Munich, Germany; Commercial registries: Berlin-Charlottenburg, HRB 12300, Munich, HRB 6684; WEEE-Reg.-No. DE 23691322


Von: Silvio Wolf ***@***.***>
Datum: Donnerstag, 17. August 2023 um 17:46
An: siemens/ix ***@***.***>
Cc: Drebinger, Konrad (DI PA SW PRM 2) ***@***.***>, Mention ***@***.***>
Betreff: Re: [siemens/ix] Industrial icon for electrical energy (Issue #653)

will be added with next icon-font release
name:
electrical-energy(-filled)

**Comment by silviowolf** [comment]
Hi @drebinge, sorry, I was on vacation. Icon is release meanwhile.
