### ISSUE TITLE
Icons for Maintenance task start and end

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix#654]
### Suggestion / feature request

We have icon which show on going maintenance task. In Water APPs we need a way to show when a job started and ended and it would be reflected on a graph.
Could we please have 2 icons which demonstrate maintenance (Jobs) start and Job end like a spanner with tick mark ?

**Comment by silviowolf** [comment]
Hi @supreethaPavank,

would these icon pairs do the job?
![image](https://github.com/siemens/ix/assets/115155312/b9480760-fd71-4081-bdea-b9759860f853)

**Comment by nuke-ellington** [comment]
Closed due to inactivity
