### ISSUE TITLE
Application-name would be disappeared in Vue.

### ISSUE THREAD

**Issue by joejoeyu** [siemens/ix#658]
### What happened?

Application-name just show in first time which is set. After refreshing Browser it is disappeared. I try this in React, is ok.
![image](https://github.com/siemens/ix/assets/64621306/2709c052-c8ed-4805-890b-576c763c0082)

### What type of frontend frameware are you seeing the problem on?

Others

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
<script setup lang="ts">
import { IxBasicNavigation, IxMenu, IxMenuItem } from '@siemens/ix-vue';
</script>

<template>
  <IxBasicNavigation application-name="1231aa3">
    <div className="placeholder-logo" slot="logo"></div>
    <IxMenu>
      <IxMenuItem>Item 1</IxMenuItem>
      <IxMenuItem>Item 2</IxMenuItem>
    </IxMenu>
  </IxBasicNavigation>
</template>
```

**Comment by danielleroux** [comment]
Fixed with latest version.
