### ISSUE TITLE
Event emitters are not visible in angular tempates

### ISSUE THREAD

**Issue by Tyrrx** [siemens/ix#666]
### What happened?

I tried to use the `valueChange` event of the `IxExpandingSearch` component but I cannot access the event from the template as the component definition does not implement the interface `IxExpandingSearch`, which defines the event emitter.
The only way to access the event emitters seems to be by referencing the element using `@ViewChild`, which that's not very beautiful and produces a huge overhead.

It seems like that this is a general issue.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

1.6.3

### Code to produce this issue.

```shell
<ix-expanding-search
  placeholder="Search..."
  icon="search"
  (valueChange)="console.log($event)"
></ix-expanding-search>
```

**Comment by danielleroux** [comment]
Cannot reproduce the issue. Checkout the stackblitz: https://stackblitz.com/edit/q11jpy?file=src%2Fapp%2Fexpanding-search.ts

**Comment by Tyrrx** [comment]
Yea, the template compiler will allow it but as soon as you use the actual type in the `test` function, the compiler will fail because the type is not known in the template.

Try the following method:
```ts
test(event: CustomEvent<string>) {
    alert(JSON.stringify(event.detail));
  }
```
Or see:
[https://stackblitz.com/edit/q11jpy-t2vvvz?file=src%2Fapp%2Fexpanding-search.ts](https://stackblitz.com/edit/q11jpy-t2vvvz?file=src%2Fapp%2Fexpanding-search.ts)

**Comment by danielleroux** [comment]
Thats aspected system behavior of stenciljs and `angular-output-target`. Checkout https://github.com/ionic-team/stencil-ds-output-targets/issues/219

**Comment by Tyrrx** [comment]
Well, I think its out of this scope then, thanks :)
