### ISSUE TITLE
Feature request: In ix-category-filter, add support to make the operator optional

### ISSUE THREAD

**Issue by hiteshkotharinn** [siemens/ix#667]
### Suggestion / feature request

In the current implementation of ix-category-filter, there is no provision to **hide the operator**.

![image](https://github.com/siemens/ix/assets/49521132/4e74630b-4e1a-429e-9187-0c784ec382a9)

![image](https://github.com/siemens/ix/assets/49521132/274a6a73-3418-4d16-8a60-90b8c434b62f)

**Comment by Jayesh26** [comment]
@nuke-ellington any update on this ?
