### ISSUE TITLE
Need icons for signature validity.

### ISSUE THREAD

**Issue by sojukrishna** [siemens/ix#668]
### Suggestion / feature request

Suggestion / feature request
We need below icons in Siemens iX for showing the validity of electronic signatures

1. Valid Signature

![image](https://github.com/siemens/ix/assets/3873393/322256e8-f0b9-49b6-9ed4-b9969460f88a)

2. Invalid Signature (Inverse of Valid)

Please let us know if it cannot be provided from iX and should be done from our application.

**Comment by silviowolf** [comment]
Hi @sojukrishna, the proposed icon is visually very close to the existing "success" and "error" icon .
![image](https://github.com/siemens/ix/assets/115155312/b9dcfa05-1277-42b8-9fce-6c4de04b5cff)
Anything against using these icons?

**Comment by silviowolf** [comment]
> @silviowolf this was set as `planned`. What is the status?

Done with latest release.
![image](https://github.com/siemens/ix/assets/115155312/fd9ce15e-a0b7-4fd9-838a-b2c7dba18c35)
