### ISSUE TITLE
Alignment problem in ix-tree with limited width

### ISSUE THREAD

**Issue by Heino-S** [siemens/ix#681]
### What happened?

Using an ix-tree control within an area/window with limited width (in our case in an as-split-area) and long node names disturbs the alignment of the tree nodes. See red marked tree nodes in the picture enclosed (left part: enough space; right part: limited width).
![ix-tree-alignment](https://github.com/siemens/ix/assets/116162884/11afec6e-8fef-4f63-847a-e6bcf565ecc9)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
<as-split direction="horizontal">
    <as-split-area [size]="20">
      <ix-tree [model]="treeData.treeModel"
               [root]="treeData.rootNodeId"
               [renderItem]="treeItem"
               (contextChange)="onContextChange($event)">
      </ix-tree>
    </as-split-area>
    <as-split-area [size]="80">
       Something else is shown here
    </as-split-area>
</as-split>

<ng-template #treeItem let-item>
  <div class="d-flex align-items-center">
    <ix-icon [name]="item.icon" size="16" class="me-2"></ix-icon>
    {{ item.name }}
  </div>
</ng-template>
```

**Comment by matthiashader** [comment]
Should be fixed with #1428
