### ISSUE TITLE
define color for icons in ix-dropdown-button

### ISSUE THREAD

**Issue by Heino-S** [siemens/ix#682]
### Suggestion / feature request

until Siemens version 1.4  an "alarm" icon in an ix-dropdown-button control was displayed in red color.
In the newest version 1.6.3 the same icon is displayed in "inherit" color (white or black) but unfortunately there is no standard to set the icon's color to another value (at least I did not find any). But it would be nice to have a red alarm again ....

**Comment by silviowolf** [comment]
Hi @Heino-S, to avoid contrast issue the icons will be displayed in the respective contrast color depending on the background.
What is your usecase behind using the alarm color for icons? Is it to mark critical actions?

**Comment by nuke-ellington** [comment]
Closed due to inactivity
