### ISSUE TITLE
[IxSelect] Bad interoperability with react-hook-form

### ISSUE THREAD

**Issue by robert-wettstaedt** [siemens/ix#691]
### What happened?

[As per the docs](https://ix.siemens.io/version-dev/docs/controls/validation) your recommended way to validate forms is to use [react-hook-form](https://react-hook-form.com/). Unfortunately, you do not provide examples how to integrate iX' custom form components with that library. After trying to integrate `IxSelect` with the form validation, I have found two main problems:

1. The class `form-control`

In order for bootstrap to show the validation status of a form element, it requires the use of the `form-control` class. However, adding that class to `IxSelect` will draw a border around the component that looks terrible (see "iX Select" in the example):

<img width="243" alt="Screenshot 2023-08-15 at 08 49 11" src="https://github.com/siemens/ix/assets/3035576/aa001ed5-253f-457f-9dc3-4a0dceffb778">

I could of course remove the `form-control` class, but then the form element's errors are not going to be displayed (see "iX Select without form-control" in the example).

2. Standard `onChange` vs non-standard `onItemSelectionChange` event

Per default, `react-hook-form`'s [register](https://react-hook-form.com/docs/useform/register) function expects an `onChange` event. The `IxSelect` not only uses a different naming convention for the event, but also uses a non-standard way of attaching the event data to the event object by setting it to `event.detail`. This requires a bit of data transformation to be compatible with `react-hook-form`:

```tsx
const { register } = useForm()
const api = register("select")

return (
  <form>
    <IxSelect
      id="select"
      onItemSelectionChange={(event) => 
        api.onChange({
          target: {
            name: "select",
             value: event.detail
           }
         })
       }
       {...api}
      />
  </form>
)
```

Personally, I would prefer if all form elements adhere to the standard naming convention for props, such as `onChange` and `value` instead of some arbitrary names. If that is not possible at the very least, please provide some good examples in your doc on how to integrate your components with your recommended form validation.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
https://codesandbox.io/s/ixselect-bad-interoperability-with-react-hook-form-ft3slv
```

**Comment by fakhir** [comment]
I also faced these same problems when using IxSelect with react-hook-form. One suggestion for the same code you've mentioned above would be to embed IxSelect within the react-hook-form's Controller element, which gives better integration with "value" and defaults, though it's not ideal like you mention:

```
  <Controller
    name="appType"
    control={control}
    rules={{ required: true }}
    render={({ field: {name, onChange, onBlur, value, ref} }) => (
      <IxSelect id="inputAppType" name={name} onItemSelectionChange={(data) => onChange(data.detail[0])} selectedIndices={value} onBlur={onBlur}>
        ...
      </IxSelect>
    )}
  />
```

**Comment by danielleroux** [comment]
How @fakhir descibe is the way how to integrate web components inside react-form-hooks.

As soon as the stencil team merged the following pr https://github.com/ionic-team/stencil/pull/4784 we can start to work also to enable native web components support of our components.

**Comment by danielleroux** [comment]
[IX-561]

**Comment by Aiderlei** [comment]
Is there any update in march 2024? I am having the same Issues with Angular and Select. 

![image_720](https://github.com/siemens/ix/assets/105216602/6466ddde-d3ec-4b54-ab4c-23ba7f2d3272)

![image_720](https://github.com/siemens/ix/assets/105216602/8dd12c92-592a-487a-b298-ef1a2d7bd690)
