### ISSUE TITLE
Date time picker language support

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#698]
### What happened?

It's not described that the date time picker takes the locale or browser language. In our project we have to support up to 7 languages (eg.: Mandarin). 
It would be nice if those languages could be controlled by the application which is implementing the date time picker.

Additionally not always monday is the starting day of the week. In some countries it's sunday.
https://www.calendarr.com/united-states/first-day-of-the-week/#:~:text=Monday%20is%20the%20first%20day,start%20the%20week%20on%20Sunday.

If the date time picker is already able to do this, please add it to the documentation.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

**Comment by danielleroux** [comment]
Will be part of 2.1.0
