### ISSUE TITLE
Dropdown positioning

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#699]
### What happened?

The dropdown from iX automatically detects the screen end on left or right. Means it opens automatically to the left, if it is on the right end of the screen. This does not work from bottom or top. If it is at the bottom of the screen the dropdown is out of the 
"monitor".
The dropdown should automatically open to the top at this point. Same for top positioning -> it should get opened to the bottom.

![image](https://github.com/siemens/ix/assets/109066516/9c83edfe-22e7-48c0-8fe7-185a4ddd4353)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

**Comment by danielleroux** [comment]
Already fixed with #694 

![droppos](https://github.com/siemens/ix/assets/2144313/2c3f910d-2c8e-4277-b362-8069d4b983c2)
