### ISSUE TITLE
Scrollable body for modals

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#701]
### What happened?

The modal size is currently growing if you put more content in it.

We have the issue that we have so much content because of displaying a dynamic list or of static content.
We need a flag where we are able to control a "scrollable body"

Example scrollable:
![image](https://github.com/siemens/ix/assets/109066516/2c86b0ed-9191-49f8-b50a-0f7b59837f73)

example static:
![image](https://github.com/siemens/ix/assets/109066516/5481fe08-efdf-45da-b8e5-2cc73b8033da)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

**Comment by matthiashader** [comment]
Internal ref [IX-861]
