### ISSUE TITLE
DateTimePicker showSeconds, showMinutes and showHour properties don't work

### ISSUE THREAD

**Issue by neunteufelflorian** [siemens/ix#702]
### What happened?

Setting either of the above named properties to false does not hide them from the UI? 🤔 

Also the inputs are readonly/disabled by default

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v.1.4.0

### Code to produce this issue.

```shell
<ix-datetime-picker
      *ngIf="showDateTimePicker"
      [range]="false"
      [dateFormat]="'dd.MM.yyyy'"
      [timeFormat]="'HH:mm'"
      [from]="fromDate"
      [maxDate]="maxDate"
      [minDate]="minDate"
      (done)="finishDateSelection()"
      (dateChange)="setDate($event)"
      (timeChange)="setTime($event)"
    ></ix-datetime-picker>
```

**Comment by matthiashader** [comment]
Fixed with #990
