### ISSUE TITLE
DateTimePicker selecting Minutes/Hours/Seconds above maximum does not set the field to 0

### ISSUE THREAD

**Issue by neunteufelflorian** [siemens/ix#703]
### What happened?

![image](https://github.com/siemens/ix/assets/119290892/3c4a25c0-89bc-4021-966c-7f1721c07015)

Increasing the Minutes from 59 to 60 via the Button above the minutes does not set the field to 0 as shown in the Demo, but instead it stays at 59.

The same is happening for hours (23) and seconds (59)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

**Comment by goncalosard** [comment]
@danielleroux @nuke-ellington Tested in the current version and this is no longer happening. It works correctly, it goes from 59 to 0 currently.
