### ISSUE TITLE
echart is not working with webcomponent (lit)

### ISSUE THREAD

**Issue by kcmyprojects** [siemens/ix#705]
### What happened?

echart siemensIX component ( https://ix.siemens.io/docs/controls/charts/) **is not working** when used with webcomponent lit.
no error and no output when tried in stackblitz.

Also as of now we can see one type of echart, Bar in siemensIX.
Is there any plan of providing siemensIX components of **other types of echart too** ?

### What type of frontend frameware are you seeing the problem on?

Others

### Which version of iX do you use?

1.6.3

### Code to produce this issue.

```shell
example project has been created in stackblitz using lit webcomponent.
https://stackblitz.com/edit/hzcmgg-yd6jl9?file=src%2Fmyechart.js,package.json,src%2Findex.html
```

**Comment by danielleroux** [comment]
We do only provide a theme for echarts. No echarts support in general if you have problems regarding the theme please reopen the ticket.

**Comment by h4de5** [comment]
@kcmyprojects your link misses several things: echart was not imported, but initialized twice, and querySelector from document does not work with shadowDom.

working example:
https://stackblitz.com/edit/hzcmgg-jchyud?file=src%2Fmyechart.js,package.json,src%2Fmain.js
