### ISSUE TITLE
Gridstack not working with lit web component

### ISSUE THREAD

**Issue by ytcodes** [siemens/ix#706]
### What happened?

Gridstack (https://gridstackjs.com/) is not working in a lit component when placed in nested web component. I have tried disabling shadow dom of all the parent components of gridstack component. By doing this, the styling of entire application will be distorted. Along with this, the styling of gridstack will also not be applied.

### What type of frontend frameware are you seeing the problem on?

Others

### Which version of iX do you use?

1.6.3

**Comment by danielleroux** [comment]
Maybe better contact the guys of gridstackjs not us
