### ISSUE TITLE
Icon for app and app installation

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#709]
### Suggestion / feature request

in my project I need an icon for Applications (i know there is already the one with the 9 dots, but this is used for navigating to the launchpad) and for App installation.

There is one central page available where the user sees all available apps. He is also able to install an app to a device.

eg.:
![image](https://github.com/siemens/ix/assets/109066516/c6cd6ba7-7cf2-4c55-8308-7554ef313ec3)
and this one with an "download arrow" for the installation (just a thought)

**Comment by silviowolf** [comment]
@katjaKoppensteiner, requested icons are available now.
@robert-wettstaedt, using custom icons will be introduced soon, documentation and guidelines are in work.
