### ISSUE TITLE
[IxMenuItem] Allow rendering of custom icons

### ISSUE THREAD

**Issue by robert-wettstaedt** [siemens/ix#711]
### Suggestion / feature request

There are a lot of feature requests to add icons to the industrial icon pack.

- https://github.com/siemens/ix/issues/535
- https://github.com/siemens/ix/issues/709
- https://github.com/siemens/ix/issues/654
- https://github.com/siemens/ix/issues/668
- https://github.com/siemens/ix/issues/653
- https://github.com/siemens/ix/issues/493
- https://github.com/siemens/ix/issues/472

Even more can be found in the [repo of the icons package](https://github.com/siemens/ix-icons/issues?q=is%3Aissue).

I think some of them could be avoided if there was a possibility to render custom icons in iX. Right now, I believe the navigation is the only place where there is no workaround for this. 

So I suggest adding a slot with the name `icon` that will be rendered instead of the default `IxIcon`, such as:

```tsx
<IxBasicNavigation>
  <IxMenu>
    <ixMenuItem> 
      <slot name="icon">
        <svg><path d="..."/></svg>
      </slot>
      
      Item 1
    </IxMenuItem>
  </IxMenu>
</IxBasicNavigation>
```

**Comment by danielleroux** [comment]
Thanks for your idea! 
We already talked alot about this topic. We planning to provide a functionality to use custom **SVG** inside our components. This will be part of the upcoming 2.0.0 release.

**Comment by robert-wettstaedt** [comment]
Sounds good! Is there anything that can be tested in the current 2.0.0 beta already?

**Comment by danielleroux** [comment]
Not in the latest beta. My plan is to release a new beta mid/end of next week. I hope until then we can a least provide the functionality for custom svg icons but without a documentation.
