### ISSUE TITLE
The ix select remains editable. editable attribute does not seem to be working.

### ISSUE THREAD

**Issue by Aditi27011996** [siemens/ix#720]
### What happened?

For the control- Select, editable does not seem to be working for the angular code.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

1.6.3

### Code to produce this issue.

```shell
<ix-select [selectedIndices]="selectedIndices">
      <ix-select-item label="Item 1" value="1"></ix-select-item>
      <ix-select-item label="Item 2" value="2"></ix-select-item>
      <ix-select-item label="Item 3" value="3"></ix-select-item>
      <ix-select-item label="Item 4" value="4"></ix-select-item>
    </ix-select>
```

**Comment by danielleroux** [comment]
Works fine on my side see stackblitz -> https://stackblitz.com/edit/qqeb8b?file=src%2Fapp%2Fselect-editable.ts

**Comment by Aditi27011996** [comment]
Thanks for the inputs!
