### ISSUE TITLE
Dropdown button content does not stick to the anchor

### ISSUE THREAD

**Issue by mohitmutha** [siemens/ix#727]
### What happened?

Steps to replicate
- Add a drop down button to the page 
- open the button content 
- Scroll the page
- The button content moves and does not stick to the anchor

OK
![image](https://github.com/siemens/ix/assets/5111605/7c15100f-9506-4201-8496-f03d8a572eef)

Not OK
<img width="368" alt="image" src="https://github.com/siemens/ix/assets/5111605/5d54c561-7e31-4580-a85a-389f786353c8">

Demo:
https://stackblitz.com/edit/ev9kxj?file=src%2Ftoast-position.tsx

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
https://stackblitz.com/edit/ev9kxj?file=src%2Ftoast-position.tsx
```

**Comment by goncalosard** [comment]
@danielleroux @nuke-ellington Tested this, could not replicate it. Dropdown does not move when the page is scrolled down. End result of test is the correct result.
