### ISSUE TITLE
Icon for hub connection status

### ISSUE THREAD

**Issue by angelinazhang9999990** [siemens/ix#728]
### Suggestion / feature request

In my project, I have 3 status which indicates the connection status between Industrial Edge management & Hub, they are: 
+ connected
+ partially connected 
+ disconnected

now I'm using those 2 represent connected & disconnected
![image](https://github.com/siemens/ix/assets/143497108/5960f89f-4e1b-4dd2-a20b-4baff16c7be9)

but I still need an icon to represent [partially connected].

for example something like below:  (just a thought)

![image](https://github.com/siemens/ix/assets/143497108/af325e81-595d-4305-a40e-2fc019f85f46)

![image](https://github.com/siemens/ix/assets/143497108/9cb34ca3-31aa-49a6-9ce6-01b2cade5e7a)

**Comment by silviowolf** [comment]
Hi @angelinazhang9999990, what means "partially connected" in your usecase? Connected with issues or similar?

**Comment by angelinazhang9999990** [comment]
> Hi @angelinazhang9999990, what means "partially connected" in your usecase? Connected with issues or similar?

there are serval remote destinations to connect to .
If  all destinations are reachable, it is connected.
if only some of destinations are reachable, it is partially connected.
if all destinations are NOT reachable, it is disconnected

**Comment by angelinazhang9999990** [comment]
@silviowolf
