### ISSUE TITLE
Icons for pumps, valves and tanks and zones

### ISSUE THREAD

**Issue by drebinge** [siemens/ix#729]
### Suggestion / feature request

In water networks we have tanks, tank farmes, valves, pumps and zones We need to have icons for these process technology components. Very likely, we would not be the only ones that would welcome such icons. At the moment we are using the following icons (see attached file) which are not in the industrial icon collection of Siemens iX. For the mentioned icons I suggest to use icons that are very close to the corresponding P&ID symbols. 

![Uploading Non Siemens IX icons.png…]()

**Comment by silviowolf** [comment]
Hi @drebinge, we have a collection of the most common P&ID symbols but they are not part of the in-app icon set due to their different context, usage and style. I will get in contact with you with more details.

**Comment by nuke-ellington** [comment]
@silviowolf what is the status of this issue?

**Comment by silviowolf** [comment]
> @silviowolf what is the status of this issue?

Can be closed.
