### ISSUE TITLE
Dynamic tabs do not work when number of tabs is varied

### ISSUE THREAD

**Issue by mohitmutha** [siemens/ix#730]
### What happened?

We are trying to render tabs dynamically. So if there is a certain selection then number of tabs is 3 and then when the selection changes the number of tabs is 2. 

When the number of tabs increases or remains the same things work fine. But when the number of tabs is reduced we get a error
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
Code to replicate
https://stackblitz.com/edit/c23ewv?file=src%2Ftabs.tsx

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
https://stackblitz.com/edit/c23ewv?file=src%2Ftabs.tsx
```

**Comment by danielleroux** [comment]
Fixed in #594 will be part of 2.0.0 release
