### ISSUE TITLE
CSS differences of ix-icons in productive and dev build due to webpack optimization

### ISSUE THREAD

**Issue by hendrikhelmer** [siemens/ix#731]
### What happened?

I am working on a docusaurus project and make use of ix-icons. When using the ix-icon tag inside an mdx-file and specifiying the size inside the tag (e.g. size = "16") this works fine for dev build. But when building the project for productive, webpack optimizes the css files and bundels them. In my case the .glyth-16 class gets bundeled with the h6 tag and therefore shiftet upwards inside the bundled css file. Due to the upshift the .glyph-16 class is not able to overwrite the font-size from the original .glypth class and therefore i can not set the font-size properly.

One possible solution that worked for my build is to define the size classes like .glyph-16 as nested classes like:
ix-icon > .glyph-16

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.4.1

### Code to produce this issue.

```shell
Make use of the ix-icon tag with size="16" inside a mdx-file of a docusaurus project where the h6 tag is defined with a font-size of 1rem (same as font-size from .glyph-16). Webpack should bundle the classes in productive build and the font-size should not be set accordingly to size 16.
```

**Comment by danielleroux** [comment]
Please provide a repository to reproduce. You can take one of the Stackblitz Demo -> https://docusaurus.io/docs/playground

**Comment by hendrikhelmer** [comment]
This issue depended on an older version and is resolved in the current version.
