### ISSUE TITLE
IxValidationTooltip logs errors on console after hide

### ISSUE THREAD

**Issue by soundararaj-gayathri** [siemens/ix#734]
### Suggestion / feature request

When we show a validation tooltip and then hide it errors are logged to the console.
Here is a working demo of the error
https://codesandbox.io/s/strange-bird-5l87js?file=/src/App.tsx

The app console and also test logs are flooded with these errors. It makes it very hard for us to debug any actual errors on the app.

**Comment by danielleroux** [comment]
Please use correct issue template next time.
![image](https://github.com/siemens/ix/assets/2144313/f5a8e622-6d20-43e2-a9a2-d36bfa5379cc)

Fixed in #671. Shipped in 2.0.0 release
