### ISSUE TITLE
[IxSelect] Support for Angular Forms 

### ISSUE THREAD

**Issue by Tiagogv** [siemens/ix#736]
### Suggestion / feature request

The IxSelectComponent on Angular should work natively with either with Template Driven or Reactive Forms.

As an example for Template Driven form:
```html
<ix-select [(ngModel)]="value" name="select-control">
  <ix-select-option value="1" label="Option 1"/>
  <ix-select-option value="2" label="Option 2"/>
</ix-select>
```

and Reactive form:
```html
<ix-select [formControl]="form">
  <ix-select-option value="1" label="Option 1"/>
  <ix-select-option value="2" label="Option 2"/>
</ix-select>
```

For this an implementation of a directive using the ControlValueAccessor interface should be created.
Happy to create PR for this.

**Comment by danielleroux** [comment]
Shoulds good. But keep in mind we are using the stencil-out-targets, this provides the posibility to generate valueAccessors out of the webcomponents https://stenciljs.com/docs/angular#valueaccessorconfigs
