### ISSUE TITLE
Tooltip visibility

### ISSUE THREAD

**Issue by Prymosoft** [siemens/ix#740]
### What happened?

In certain cases the tooltip does not shown correctly, because if near the side of the view it overflows and only half of it is visible. In addition if there is an 'icon' or 'pill' near the tooltip, the tooltip is behind and not on top, so also not clearly visible. (this can be fixed if you are not using visibility attribute but toggle display, to not be rendered in the DOM when not hovered in my opinion.) 
![image](https://github.com/siemens/ix/assets/140390986/8a7608ad-8d6f-400d-9faf-27ca86efa1fe)
![image](https://github.com/siemens/ix/assets/140390986/a4ab72db-9c3f-400a-b2cd-5d6836c00b54)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.6.3

**Comment by danielleroux** [comment]
Please provide code to reproduce use stackblitz https://stackblitz.com/run?file=src%2Fapp%2Ftooltip.html or a GitHub project

**Comment by Prymosoft** [comment]
Hi!

I created a github repo for this issue. I cannot reproduce that error when tooltip slides behind icon but issue when it is not fully visible near the sides
https://github.com/Prymosoft/ix-tooltip-error

Best,

Martin

**Comment by nuke-ellington** [comment]
@Prymosoft just out of curiosity: how do you manage to show two tooltips at once?
