### ISSUE TITLE
IxGroupItem component does not reflect "selected" attribute value

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#747]
### What happened?

There is a strange behavior when trying to set `selected` attribute within **IxGroupItem** component. It seems that the component is showing the "selected" bar (on the left side of item) by its own inner rules, not reflecting the current value of the attribute.

E.g. when `selected` attribute is always set to `true`, this kind of behavior appears:

![animation-group-item](https://github.com/siemens/ix/assets/99844553/1dfa0107-6aa5-4aaa-bcfc-7d30cd57f21f)

Currently, it is not possible to change the behavior of how items are selected (even when the item is marked as selected and user clicks on it, it is marked as unselected again and so on).

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
// simplified code
import { useNavigate, useParams } from "react-router-dom";

export function Sidebar() {
  const navigate = useNavigate();

  function handleClick(url) {
    navigate(url);
  }

  return (
    <IxGroup header="Item 1" subheader="Secondary text">
      <IxGroupItem selected={true} text="Item 1" onClick={handleClick.bind(null, url)} />  
      <IxGroupItem selected={true} text="Item 2" onClick={handleClick.bind(null, url2)} />
      // and so on (for loop is used in real code)
    </IxGroup>
  );
}
```

**Comment by silviowolf** [comment]
Hi @tomas-reznak, the componentn basically works as expeceted. It is not intended to have multiple items selected.
