### ISSUE TITLE
Add icon "check-small"

### ISSUE THREAD

**Issue by flxlst09** [siemens/ix#759]
### Suggestion / feature request

In the Figma Asset library the icon "check-small" exists but cannot be found in the iX implementation.

https://www.figma.com/file/4XZ13qHYNyx4zgYFMWMSR5/iX-Assets?type=design&node-id=212-4071&mode=design&t=edP78DvyCvbp5soo-4

**Comment by silviowolf** [comment]
Hi @flxlst09, thanks for the hint, is indeed missing. Will be added asap. On this ocsasion I will change the name to just "check" since "check-small" is completely misleading. It is the largest check in the library :)
