### ISSUE TITLE
Wrong Icons are Showing on the Screen

### ISSUE THREAD

**Issue by yagizhanNY** [siemens/ix#768]
## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

I installed a new version of `siemens-ix-icon` package in my React app. The icons are wrong on the screen. When I downgrade the package, it's fixed.

![image](https://github.com/siemens/ix-icons/assets/41087670/c7995d91-1732-430c-920e-aebaeb06f1ba)

**Comment by danielleroux** [comment]
@yagizhanNY I moved the issue into the ix repository because the ix-icons works standalone but noch with the latest 1.6.3 of ix.

**Comment by yagizhanNY** [comment]
Okay, thanks for the information. @danielleroux

**Comment by danielleroux** [comment]
Regarding a bundle issue its solved with the latest 2.0.1 release of the library in combination with ix-icons 2.0.0
