### ISSUE TITLE
Custom width property for modals

### ISSUE THREAD

**Issue by CagatayCanK** [siemens/ix#769]
### Suggestion / feature request

Suggestion / feature request

Allow custom size for modal, especially width.

We are trying to show a lot of data and form on a modal but Modal size: 'xl' is not enough to fit everything, especially width wise.
I tried to manually change css of the modal content class but it feels hacky and media queries overwrites it anyway.

Is it possible to add width property like the one on the Flip? Maybe allow percentage or vw on top of REM?

**Comment by danielleroux** [comment]
With the next release we want to support the following sizes:

```
- `360`
- `480`
- `600`
- `720`
- `840`
- `full-width` - Use the maximal size of the screen width
```

A complete custom modal width is not planned.

**Comment by CagatayCanK** [comment]
Is it possible to also have max width/height so it will automatically resize itself depending on the content?
Like Chakra UI [modal ](https://chakra-ui.com/docs/components/modal/usage) does [it](https://stackoverflow.com/questions/70040397/how-to-make-custom-sized-modal-in-chakra-ui)

**Comment by danielleroux** [comment]
We will implement also fullscreen modal with responsive widths/heights. Will be part of release 2.0.0

**Comment by danielleroux** [comment]
🚢 in 2.0.1
