### ISSUE TITLE
Enable manipulating ix-icons with external css files

### ISSUE THREAD

**Issue by hendrikhelmer** [siemens/ix#771]
### Suggestion / feature request

We are working with the Ix-Icons in a docusaurus react project and would like to be able to manipulate the appearence of these with normal CSS files to our needs. Since the ix-icons are styled inside the Shadow-DOM this is currently not possible and styling them with javascript is not our preferred way.
We are using the Ix-Icons both as React-Components and as web components.
Maybe the following is a solution: https://developer.mozilla.org/en-US/docs/Web/CSS/::part

**Comment by danielleroux** [comment]
What are you "manipulate" at the icons?

**Comment by hendrikhelmer** [comment]
For example our current usecase would be to increase the size of the icon to 64px since the "size" property only supports a size up to 32px.

**Comment by danielleroux** [comment]
This is already possible with the latest version 2.0.1
