### ISSUE TITLE
Dark mode bug for Drop Down & Filter combos

### ISSUE THREAD

**Issue by mpmberlin** [siemens/ix#78]
-->

## I'm submitting a...

<pre><code>
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

When using dark mode the combo Drop box & Filter is shown in light mode

## Expected behavior

Should be shown in dark mode

**Comment by mpmberlin** [comment]
![Screenshot 2022-10-19 at 10 04 52](https://user-images.githubusercontent.com/39371147/196698172-c97d4e29-2590-4a10-99ce-cc1e6f4793a8.png)

**Comment by danielleroux** [comment]
Looks like this is not an iX component. It looks more like ng-select (https://github.com/ng-select/ng-select)
