### ISSUE TITLE
How to support custom icons in Map navigation overlay?

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix#790]
### What happened?

I am trying to include a custom icon of a Manhole/CSO which is not part of IX library on map nav overlay but looks like it supports only IX icons.

 

 <ix-map-navigation-overlay

        *ngIf="showOverlay"

        name="Custom overlay title"

        icon="IX-ICON-NAME"

        slot="overlay"

        (closeClick)="showOverlay = false"

      ></ix-map-navigation-overlay>

 

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
In the fork below, I'm trying to include font awesome icon as an example. Is there any work around?

[https://stackblitz.com/edit/xnfrdi?file=src%2Findex.html,src...](https://stackblitz.com/edit/xnfrdi?file=src%2Findex.html,src%2Fapp%2Fmap-navigation-overlay.ts)
```

**Comment by danielleroux** [comment]
Checkout https://ix.siemens.io/docs/icon-library/icons you will find a guide how to create custom svg icons and on the code section how to use them.

🚢 in 2.0.0

**Comment by danielleroux** [comment]
If the issue is still a point, please reopen this issue and adapt the description.
