### ISSUE TITLE
ix-icon-button tooltip show the name of the icon and not the content of the title field

### ISSUE THREAD

**Issue by viktorhajer** [siemens/ix#795]
### What happened?

It seems the issue depends on the icon and the disabled attribute. For example if the icon button is disabled then the title is correct or if I use the "play" icon, it is working fine. But the title of other icons like "open-external" is not correct if the button is not disabled. 

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.1

### Code to produce this issue.

```shell
<!-- open-external title is displayed-->
<ix-icon-button icon="open-external" variant="Primary" ghost [disabled]="false" title="Test">

<!-- test title is displayed-->
<ix-icon-button icon="open-external" variant="Primary" ghost [disabled]="true" title="Test">
```

**Comment by danielleroux** [comment]
Will be fixed with issue #800. Will close this issue.

**Comment by TDaniel-evo** [comment]
Hi! It was not fixed with #800. I checked with version 2.0.3 and the name of the icon is still visible as tooltip.

**Comment by viktorhajer** [comment]
I can still repro the issue in v2.0.3.

**Comment by danielleroux** [comment]
😮‍💨 #839 didnt get it with the first try. Issue here is the `ix-icon`-component has its own title property depending on the icon loaded, but in case of an embedded usecase like `ix-button` and `ix-icon-button`.
