### ISSUE TITLE
iX dropdown trigger does not work with ID

### ISSUE THREAD

**Issue by katjaKoppensteiner** [siemens/ix#796]
### What happened?

i am using Angular and I am having a list of items. Each item has its own dropdown:

```<div *ngFor="let device of deviceListView$ | async">
  <device-card [device]="device" (deviceCardActionClicked)="onCardClick(device)">
    <div slot="cardItem-actions">
        <ix-icon-button
          [id]="device.id"
          icon="more-menu"
          variant="Primary"
          ghost
          data-test-id="dropDownButton"
        ></ix-icon-button>
        <ix-dropdown [trigger]="device.id">
          <ix-dropdown-item label="Item 1"></ix-dropdown-item>
          <ix-dropdown-item label="Item 2"></ix-dropdown-item>
          <ix-dropdown-item label="Item 3"></ix-dropdown-item>
        </ix-dropdown>
    </div>
  </device-card>
</div>
```

Triggering with ID doesn't work because 
![image](https://github.com/siemens/ix/assets/109066516/9e2d08ef-2f62-40a8-a9a5-486c5503a867)
see: https://stackoverflow.com/questions/37270787/uncaught-syntaxerror-failed-to-execute-queryselector-on-document

instead if I add some letters in front:
```<div *ngFor="let device of deviceListView$ | async">
      <device-card [device]="device" (deviceCardActionClicked)="onCardClick(device)">
        <div slot="cardItem-actions">
          <ix-icon-button
            id="dropdown-{{ device.id }}"
            icon="more-menu"
            variant="Primary"
            ghost
            data-test-id="dropDownButton"
          ></ix-icon-button>
          <ix-dropdown trigger="dropdown-{{ device.id }}">
            <ix-dropdown-item label="Item 1"></ix-dropdown-item>
            <ix-dropdown-item label="Item 2"></ix-dropdown-item>
            <ix-dropdown-item label="Item 3"></ix-dropdown-item>
          </ix-dropdown>
        </div>
      </device-card>
    </div>
```

everything works as expected.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

### Code to produce this issue.

```shell
see above
```

**Comment by danielleroux** [comment]
Yes you already pointed to the correct SO Thread with a link to the html spec: https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute

If you want to change something in the html standard you have to rise an issue here: https://github.com/whatwg/html/issues
