### ISSUE TITLE
Checkbox input is not displayed without label

### ISSUE THREAD

**Issue by viktorhajer** [siemens/ix#802]
### What happened?

It is mandatory to have label next to the checkbox in order to display it. 

Workaround: it can be empty (but inconvenient to use). 

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.1

### Code to produce this issue.

```shell
<!-- Checkbox is displayed-->
<div>
  <input type="checkbox" /><label></label>
</div>

<!-- Not displayed-->
<div>
  <input type="checkbox" />
</div>
```

**Comment by danielleroux** [comment]
[IX-838]

**Comment by andreas-mucha** [comment]
Any timeline on this issue? This is currently an obstacle for an application using JSONforms that we are building.
