### ISSUE TITLE
Position of Dropdown menu with placement bottom-start/end covers bottom part of the button

### ISSUE THREAD

**Issue by sonjaZeh** [siemens/ix#812]
### What happened?

The dropdown menu is covering parts of the underlaying button. We would expect the menu to be located under the button - as "placement="buttom-end" suggests. 

![image](https://github.com/siemens/ix/assets/147053075/e2db3784-fb2a-4ef9-9ae8-0d18a416e0a5)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.4.0

### Code to produce this issue.

```shell
<ix-dropdown placement="bottom-start">
```

**Comment by danielleroux** [comment]
Cannot reproduce with latest version
