### ISSUE TITLE
Tooltip: visual issue on first use

### ISSUE THREAD

**Issue by JulianEvi** [siemens/ix#823]
### What happened?

Whenever a tooltip is shown for the first time, it appears at the top left corner of the window before jumping to the correct position.

This can also be reproduced on the documentation page of the tooltips:
Open the example in a full window and hover over one of the buttons.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.1

### Code to produce this issue.

```shell
// Can be observed on the documentation page. Happens on every tooltip implementation.
```

**Comment by tomas-reznak** [comment]
We observe the same behavior when using iX with React (iX ver. 1.6.3, React ver. 18.2.0).

**Comment by ridvandmrc** [comment]
Position was calculating after visible so I updated the order. please follow the [PR.](https://github.com/siemens/ix/pull/1036)
