### ISSUE TITLE
Select: Selecting items with arrow key does not work with multiple selects on one page

### ISSUE THREAD

**Issue by JulianEvi** [siemens/ix#824]
### What happened?

If a page contains more than one select and the arrow down key is used to select an item, one of two things happen.

In case that the page contains two selects: The other select opens
In case that the page contains more than two selects: All selects open for a brief moment and directly close again.

This behaviour can be reproduced on the documentation page by copying the select component multiple times with the developer tools.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.1

### Code to produce this issue.

```shell
// Happens on all select implementations.
```

**Comment by matthiashader** [comment]
![2023-11-20-14-20-18-_online-video-cutter com_](https://github.com/siemens/ix/assets/144090716/0be26331-fd7d-4b27-b826-9d11a8770ad2)
Could you provide the code to reproduce this, on the latest version on the documentatio i cant reproduce it.

**Comment by matthiashader** [comment]
Cant be reproduced, if this still occurs, please create a new issue.
