### ISSUE TITLE
Blind group and disabled blinds

### ISSUE THREAD

**Issue by JulianEvi** [siemens/ix#825]
### Suggestion / feature request

We often use multiple blinds in a single location. Therefore, I created a blind group that arranges multiple blinds and also offers the option to only have one of the blinds open at a time. It would be nice to have a native implementation for this.
Moreover, our previous implementation of accordions offered the option to disable accordions. This is a feature that we would also appreciate to have back.

**Comment by silviowolf** [comment]
Hi @JulianEvi, we will discuss the group behavior in our next UX meeting.
When would you set a blind to disabled?
What is the expected behavior of a disabled Blind (no expanding? look disabled?)?

**Comment by matthiashader** [comment]
We will close this issue, if you still have the requirement for this component, don't hesitate to open a new issue.
