### ISSUE TITLE
Dropdown-button: closeBehavior

### ISSUE THREAD

**Issue by JulianEvi** [siemens/ix#827]
### Suggestion / feature request

The dropdown component provides the ability to modify the close behavior and the default behavior is to close on inside and outside clicks. However, the dropdown-button component does not offer this option and the default behavior is to only close on outside clicks.
We make use of the dropdown-button component and require the dropdown to also close on inside clicks. Would it be possible to replicate the functionality from the dropdown component?

**Comment by danielleroux** [comment]
Planned with [IX-563]
