### ISSUE TITLE
ix-upload button without drop zone

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#828]
### Suggestion / feature request

We would like to use a file input without the drop zone. Only the button.

**Comment by danielleroux** [comment]
@TDaniel-evo could you provide us your usecase behind the request?

**Comment by TDaniel-evo** [comment]
@danielleroux I would like to include an upload button in a message bar. With the dropzone the message bar becomes too tall and has a clumsy look because the icon and the text are in offset.
![image](https://github.com/siemens/ix/assets/144789952/3fc77644-6677-49ed-87fa-f876a9e883e8)

**Comment by danielleroux** [comment]
I understand but in this case you dont want the ix-upload you want a `<input type="file">` styled as ix button, because the ix-upload offers more functionality which requires the dropzone.

**Comment by TDaniel-evo** [comment]
Ok, thank you. I will try your suggestion.

**Comment by danielleroux** [comment]
I will close the issue here if this is still a problem please create a new issue.
