### ISSUE TITLE
Editable select is not opening when selecting it

### ISSUE THREAD

**Issue by SusiHorter** [siemens/ix#832]
### What happened?

**Steps to reproduce:**

- open https://ix.siemens.io/docs/controls/select#editable
- click on the ix-select
- delete the text
- enter "2"
- the dropdown is not opening 
- -> open the dropdown by the button on the right side
- the list is not filtered: 
![image](https://github.com/siemens/ix/assets/63737780/767d59b7-5db1-4c84-b799-755d67512f9b)

- if the dropdown is open before editing the text, the list got filtered as expected:
![image](https://github.com/siemens/ix/assets/63737780/5a92a840-dd1f-4243-af3d-f359a078f7d8)

**Expected behavior:**

- dropdown-list opens when clicking on the ix-select (e.g. enabled by a property)
- filtering works if the list is opened with the button

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.0

### Code to produce this issue.

```shell
https://ix.siemens.io/docs/controls/select#editable
```

**Comment by matthiashader** [comment]
Is fixed.
