### ISSUE TITLE
Not possible to change the title of the about menu

### ISSUE THREAD

**Issue by viktorhajer** [siemens/ix#835]
### What happened?

It is always 'About & legal information' in the menu, so it is not possible to localize. 

![image](https://github.com/siemens/ix/assets/13874324/bb8576e6-1eb0-490a-8e02-8cef7a989fc3)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.1

### Code to produce this issue.

```shell
<ix-basic-navigation>
  <ix-menu>
    <ix-menu-about [label]="'Test'">
      <ix-menu-about-item [label]="'Item 1'"></ix-menu-about-item>
      <ix-menu-about-item [label]="'Item 2'"></ix-menu-about-item>
    </ix-menu-about>
  </ix-menu>
</ix-basic-navigation>
```

**Comment by viktorhajer** [comment]
It is true for the settings menu as well.

**Comment by danielleroux** [comment]
You have to set the label for the About and Settings on the `ix-menu` component. 

- i18nLegal
- i18nSettings
(More [here](https://ix.siemens.io/docs/controls/navigation/vertical-tabs#props))

**Comment by viktorhajer** [comment]
Thx, working fine. :-)
