### ISSUE TITLE
Input padding keeps increasing after deleting input text

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#837]
### What happened?

I have a text input with icon (https://ix.siemens.io/docs/controls/input#with-icon). This input is part of a form and there is form validation on in. If I enter text in the input and delete it with backspace then the values of background-position-x and padding-left are increasing on the input:
![image](https://github.com/siemens/ix/assets/144789952/f4fc1e71-c166-471a-b8b2-3f05dcb8c9f7)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

2.0.1

### Code to produce this issue.

```shell
...
<div class="form-group">
      <label for="iemPassword" class="form-label">
        {{ "iemLoginPasswordLabel" | translate }}
      </label>

      <ix-input-group>
        <input
          id="iemPassword"
          formControlName="iemPassword"
          placeholder="Enter text here"
          type="password"
          (keydown.enter)="onConfirm()"
          appCustomValidator
        />
        <span slot="input-end">
          <ix-icon
            name="eye"
            size="16"
            (click)="toggleIemPasswordInputType($event)"
          ></ix-icon>
        </span>
        <div
          *ngIf="loginForm.controls.iemPassword.errors?.required"
          class="invalid-feedback"
        >
          {{ "iemLoginPasswordFormErrorRequired" | translate }}
        </div>
      </ix-input-group>
    </div>
...
```

**Comment by danielleroux** [comment]
Cannot reproduce with latest version: https://stackblitz.com/edit/ne22aj?file=src%2Fapp%2Fvalidation.ts

🚢 in [2.0.3](https://github.com/siemens/ix/releases/tag/v2.0.3) (#803)

**Comment by TDaniel-evo** [comment]
Thank you! I checked with 2.0.3 and the padding does not increases but it's too small now:
![image](https://github.com/siemens/ix/assets/144789952/fb7377bc-1266-4838-8bbb-3d2887389d12)

It is also visible in your stackblitz:
![image](https://github.com/siemens/ix/assets/144789952/9fddbb84-94a8-444e-9647-54775b0a1ba7)

**Comment by danielleroux** [comment]
Yep! 😵‍💫 Already found the problem.
