### ISSUE TITLE
Map navigation not migrated

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix#84]
Please update map navigation as it is missed out from the documentation

**Comment by supreethaPavank** [comment]
The tree component- It should highlight on hover but is not currently

**Comment by danielleroux** [comment]
Duplicated issue https://github.com/siemens/ix/issues/65

**Comment by supreethaPavank** [comment]
@danielleroux  - I have also included another issue tree view not getting highlighted

**Comment by danielleroux** [comment]
@supreethaPavank  please open separate issues for the problems. Add try to fillout the predefined issue template
