### ISSUE TITLE
Title for Toggle component

### ISSUE THREAD

**Issue by viktorhajer** [siemens/ix#841]
### Suggestion / feature request

It would be helpful to have title property for the Toggle component so it would be easier to create label to the left side. 

![image](https://github.com/siemens/ix/assets/13874324/a1eb885f-353b-4b55-b89b-985808dfe92e)

**Comment by silviowolf** [comment]
Hi @viktorhajer, a label on the left side sounds easy but is quite tricky from a design system’s point of view. The label length has impact on the x-position of the toggle and in a form layout with multiple rows with toggles you would get a mess of a layout. Furthermore, your label/title requirement is valid for all types of nput contols (radiobutton, checkbox, input, select, ...) not only for the toggle. Therefore, we are currently working on a generic approach to align labels to components in general.

So it will be possible to place labels left from components in future. But this will not be a property of the respective component but most likely a property of a layouting component that will take care of the alignment of label and component.

**Comment by viktorhajer** [comment]
Hello! Yes, that totally make sense. Thank you, I gonna close this FR.
