### ISSUE TITLE
Input looks glitchy when used with icon

### ISSUE THREAD

**Issue by ridvandmrc** [siemens/ix#847]
### What happened?

I try to use `<ix-input-group>`  because I want to use the component  with `<ix-icon>`. Then,
when refresh the page or first opening of the page it looks glitchy
![error](https://github.com/siemens/ix/assets/15720132/612c303c-11da-403f-b414-a15555ea5b4b)

After typing something to input, It looks normal like:
![error2](https://github.com/siemens/ix/assets/15720132/b5021cf6-2d22-42d8-ba18-b4e2b463a4a4)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.1

### Code to produce this issue.

```shell
<section class="login-card">
    <form class="needs-validation m-2">
        <ix-input-group>
            <input placeholder="yours@example.com" type="text" />
            <span slot="input-start"><ix-icon name="user-profile" size="20"></ix-icon></span>
        </ix-input-group>

        <ix-input-group>
            <input placeholder="your password" type="password" />
            <span slot="input-start"><ix-icon name="lock" size="20"></ix-icon></span>
            <span slot="input-end"><ix-icon name="eye" size="20"></ix-icon></span>
        </ix-input-group>
        <div class="login-buttons">
            <ix-button class="m-1" variant="primary">Log In</ix-button>
            <a href="#">
                <ix-icon name="question" size="16"></ix-icon> Don't Remember your password
            </a>
        </div>
    </form>
</section>
```

**Comment by danielleroux** [comment]
Please try to update to the latest version. This issue should be fixed. There is another one in combination with validation.

**Comment by ridvandmrc** [comment]
Hi @danielleroux ,
It looks good, many Thans :)
