### ISSUE TITLE
Modal: not possible to disable close function by clicking on ESC

### ISSUE THREAD

**Issue by viktorhajer** [siemens/ix#848]
### What happened?

I tried to set the `keyboard ` config to false, but I can still use ESC button to close the modal if I click on that.

User experience: 
1. Open the modal window
2. Press ESC -> nothing happens (as expected)
3. Click on the dialog(!!!) then press ESC -> modal is closed

Note: I couldn't find description about the `keyboard` config in the documentation, so it is just an assumption that this is how it should work. 

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.3

### Code to produce this issue.

```shell
this.modalService.open({
 content: DialogComponent, keyboard: false
});
```

**Comment by maheshchandra10** [comment]
Try this:

```
this.modalService.open({
   content: DialogComponent,
   disableClose: true
});
```

**disableClose** will not allow **ESC** to close the dialog _(whether you've clicked on the dialog or not)_, and it also won't allow the dialog to close when **clicking on the backdrop**.


If you want to allow the dialog to close when **clicked on the backdrop**, but do not want to close the dialog on **ESC** press, try this inside the constructor of DialogComponent:

```
dialogRef.disableClose = true;
dialogRef.backdropClick().subscribe(_ => {
  dialogRef.close();
});
```


I should've created a PR for this, but the application is giving error in my local when I try to run it.

**Comment by viktorhajer** [comment]
@maheshchandra10 
I don't find this `disableClose` field in the documentation, and also in the ModalConfig class. 
I've got build error when I tried to use it: 

![image](https://github.com/siemens/ix/assets/13874324/a491dbb1-2210-4fc0-9689-e0ede4e7e269)

Note: maybe you checked the documentation of the angular material dialog...

**Comment by viktorhajer** [comment]
This is still an issue in 2.0.4. Any update?
