### ISSUE TITLE
event-list hover effect has been missed out

### ISSUE THREAD

**Issue by supreethaPavank** [siemens/ix#85]
## I'm submitting a...

<pre><code>
[ x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

On hover, of the treelist and event list nothing happens.

## Expected behavior

On hover, a grey color background should appear

## What is the motivation / use case for changing the behavior?

It is not obvious to the user, what is being hovered. Also, this was working fine in the previous version

**Comment by danielleroux** [comment]
@supreethaPavank what do you mean with treelist? This one https://ix.siemens.io/docs/controls/tree ?

**Comment by supreethaPavank** [comment]
@danielleroux  - Yes

**Comment by danielleroux** [comment]
@supreethaPavank this is already fixed with next release -> https://github.com/siemens/ix/issues/65

**Comment by supreethaPavank** [comment]
Then I better check with you guys once before i create more issues :-)

**Comment by danielleroux** [comment]
No its fine here just use the search function:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/2144313/197186694-055331b3-5c72-4236-b668-a9c261d645c2.png">

**Comment by danielleroux** [comment]
But for event-list the mouse states are missing i will create an issue for that.

**Comment by danielleroux** [comment]
https://github.com/siemens/ix/issues/86
