### ISSUE TITLE
Request to add an extra option to show days with the Time picker

### ISSUE THREAD

**Issue by ashutoshKashyap97** [siemens/ix#853]
### Suggestion / feature request

![image](https://github.com/siemens/ix/assets/100841631/6dc96e84-57c1-4a60-b59e-a547f83454a8)

Hello Team,
We wanted to add a days option along with the time picker as shown in the screenshot. As per IX documentation we could only implement the time picker for 24hrs. Can you please add an option or enhancement for this use case. Please suggest us any work around if there is one.

**Comment by nuke-ellington** [comment]
Hi @ashutoshKashyap97, can you please tell us more about the use case behind this issue? We would like to understand the requirements better before we make a descision on this topic. Thank you

**Comment by suraj-k-siemens** [comment]
Hi @nuke-ellington 

We have a requirement to chose a Time Duration from the UI, for instance 
1. 8 hours (A typical Shift Duration in an Assembly line)
2. Two Days 
3. 36 Hours 
4. 120 Minutes  

while designing our UX; a close-fit to this requirement was to utilize the already available time picker, So we had thought it would be nice to configure / extend the existing time picker from IX to make it look this the below image 
![time picker](https://github.com/siemens/ix/assets/156159167/1b7e3bd6-0f1e-4a91-a636-0005dc0d3600)
But the time picker only allows us to chose a duration lesser than 24 hrs 

What we need is to chose a duration ranging from Minutes to Few Days. 
Seconds are not relevant to us, so it would also be helpful if we could disable the Seconds part or set it always to 00

**Comment by nuke-ellington** [comment]
Settings days is out of scope for a time picker component since it is limited to 24 hours. If you really want to utilize it regardless please consider the [`date time picker`](https://ix.siemens.io/docs/controls/date-time-picker) instead.
