### ISSUE TITLE
Angular change detection cycle runs multiple times - ix-select

### ISSUE THREAD

**Issue by RatikantS** [siemens/ix#862]
### What happened?

We have table where few of columns (cells) are using ix-components like ix-select (and ix-switch, ix-tooltip etc.). When we click ix-select component in one of the cell, it is triggering "Angular change detection" so many times (I found exactly same number as table rows in this case)

Code Snippet:

```
<table>
   <tr *ngFor="let param of gridData; trackBy: candidateTrackBy">
      <td>
         <ix-toggle [checked]="param.candidateValueEnabled" [textOff]="'No'" [textOn]="'Yes'"
         [disabled]="param.candidateValueEnabled==='Disabled'"></ix-toggle>
      </td>
      <td>
         <input class="form-control" defaultValue="Some example text" placeholder="Enter text here" type="text"
            [value]="param.candidate" />
      </td>
      <td>
         <ix-select  name="ix-select-control" [(ngModel)]="param.selectValue">
         <ix-select-item label="Item 1" value="1"></ix-select-item>
         <ix-select-item label="Item 2" value="2"></ix-select-item>
         <ix-select-item label="Item 3" value="3"></ix-select-item>
         <ix-select-item label="Item 4" value="4"></ix-select-item>
         </ix-select>
      </td>
      <td>
         <em [class]="param.status === 'Ok' ? 'glyph glyph-success' : 'glyph glyph-minus'"
            style="color: green; margin-right: 5px;"></em>{{param.status}}
      </td>
   </tr>
</table>
```

![image](https://github.com/siemens/ix/assets/148453101/72ae4454-1395-40fa-980a-7c3085562f67)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v1.6.2

### Code to produce this issue.

```shell
Added.
```

**Comment by danielleroux** [comment]
@RatikantS 

ix-switch ✅ ix-tooltip ✅ but want to you mean with ix-switch?

**Comment by RatikantS** [comment]
@danielleroux 
Ah please read ix-switch as ix-toggle..

**Comment by danielleroux** [comment]
@RatikantS  beta version for testing -> https://github.com/siemens/ix/releases/tag/v2.1.0-beta.0 please give us feedback.

**Comment by RatikantS** [comment]
Its better now, but still I see Angular Change Detection cycle runs multiple times - can it be improved further? PFA for ix-tab and ix-select:

![image](https://github.com/siemens/ix/assets/148453101/df34a030-d6c5-4093-baa0-04dc20a99774)
![image](https://github.com/siemens/ix/assets/148453101/709eb3cd-11f1-40b6-99e1-a65ce92392ee)

**Comment by RatikantS** [comment]
any plan for 2.1.0 release date?

**Comment by RatikantS** [comment]
@danielleroux
any release date for this?

**Comment by danielleroux** [comment]
https://github.com/siemens/ix/pull/855 is already 🚢 with 2.0.4

**Comment by RatikantS** [comment]
Thank you!!
