### ISSUE TITLE
Alert color for modal primary button

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#863]
### Suggestion / feature request

We would like to use the modal for confirmation of delete on the UI. It would be nice to have an option to set the primary button color to red to emphasize the delete action.
Example:
![image](https://github.com/siemens/ix/assets/144789952/1933a770-c9e7-4f19-9126-91a9ac222b62)

**Comment by danielleroux** [comment]
Internal tracked [IX-364]

**Comment by matthiashader** [comment]
Closed by #1277
