### ISSUE TITLE
Display incorrect title when hover on navigation menu item

### ISSUE THREAD

**Issue by angelinazhang9999990** [siemens/ix#884]
### What happened?

I'm using navigation menu as sidebar. While hovering on collapsed menu item, its title displayed as same as the icon name. However the expected title should be same as menu item's inner text.

Go to [ix official document](https://ix.siemens.io/docs/controls/navigation/vertical-tabs) can also see the issue.

As the screenshots show, the title should be 'Normal Tab' instead of 'globe'

![image](https://github.com/siemens/ix/assets/143497108/5e4d9fbd-abd2-4cf6-be4d-879ec88ad4ae)

![image](https://github.com/siemens/ix/assets/143497108/6196bb2f-e646-4549-b2a7-9ec6edbd1fed)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.3

### Code to produce this issue.

```shell
import { Component } from '@angular/core';

@Component({
  selector: 'app-example',
  template: `
    <ix-menu>
      <ix-menu-item home tab-icon="home"> Home </ix-menu-item>
      <ix-menu-item icon="globe"> Normal Tab </ix-menu-item>
      <ix-menu-item icon="star" disabled> Disabled Tab </ix-menu-item>
      <ix-menu-item icon="star"> With other Icon </ix-menu-item>
    </ix-menu>
  `,
})
export default class VerticalTabs {}
```

**Comment by matthiashader** [comment]
https://github.com/siemens/ix/pull/887 solves this issue
