### ISSUE TITLE
ix-icon-button title is not displayed in disabled state

### ISSUE THREAD

**Issue by Pappszii** [siemens/ix#899]
### What happened?

While hovering on a disabled button, the title is not displayed.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.1.0-beta.0

### Code to produce this issue.

```shell
https://stackblitz.com/edit/xnfrdi-lgwwve?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css
```

**Comment by nuke-ellington** [comment]
This is the expected behavior not a bug.

**Comment by viktorhajer** [comment]
The disabled HTML button can have title, this is an unexpected behaviour and an issue - so please reopen it. Also could you link the documentation where do you describe this strange behaviour (this is a deviation from normal behavior so it should be documented)? 

Sometimes the title field is used to provide additional information about the reason of the disabled state - therefore it is elemental for us.

**Comment by viktorhajer** [comment]
Are there any plan to fix it in the near future?

**Comment by viktorhajer** [comment]
Note: the easiest way to fix it to set the `pointer-events: auto; ` CSS property on the disabled buttons.

**Comment by silviowolf** [comment]
Hi @viktorhajer, Disabled means in iX "no interaction possible". Therefore, no focus, no hover, no tooltip. Same behavior like in Bootstrap, Google Material Angular or MUI. You could wrap the disabled button into a div an use the title attribute there.
