### ISSUE TITLE
provide Sketch template for login screen

### ISSUE THREAD

**Issue by silviowolf** [siemens/ix#90]
- [x] Create Sketch template for light theme
- [x] Create Sketch template for dark theme

**Comment by danielleroux** [comment]
@silviowolf Do we get any feedback here or can we close this issue?

**Comment by silviowolf** [comment]
Login Screen templates are specified in Zeplin now, https://zpl.io/p1QYmlo and following.

**Comment by nuke-ellington** [comment]
Will not be implemented since it does not make sense in the context of the current IAM setup.
