### ISSUE TITLE
IxIconButton within IxBlind doesn't consider assigned color property

### ISSUE THREAD

**Issue by pernozzoli** [siemens/ix#911]
### What happened?

Color is not assigned properly to an IxIconButton within IxBlind

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
<IxBlind
  icon="folder-outline"
  label="Some text" >
  <IxIconButton ghost color="#00cccc" slot="header-actions" icon="open-external" onClick={ () => alert("Icon button clicked") } /> 
  Some detailed text
</IxBlind>
```

**Comment by nuke-ellington** [comment]
This is not related to an icon button nested inside of a blind.
The color property of the `ix-icon-button` only accepts the predefined color names provided by iX (e.g. `color-primary`).
You can find a full list of supported colors [here](https://ix.siemens.io/docs/theming/colors).
