### ISSUE TITLE
Full page loading spinner

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#912]
### Suggestion / feature request

We are migrating from the User Experience Toolkit (previously mindsphere design system) and we used to have a full page busy indicator (spinner) with a backdrop that is covering the whole page.  Example: https://design.mindsphere.io/preview/busy-indicator-ext.html

We would like to use something similar with the ix spinner. Of course we could implement it for ourselves but it would be nice to have it out of the box.

**Comment by silviowolf** [comment]
Hi @TDaniel-evo, we have something like that but in the modal component, a laoding modal that can be used for a full screen busy indicator.
https://ix.siemens.io/docs/controls/modal/#loading
Would this match your usecase?

**Comment by TDaniel-evo** [comment]
Thank you, it looks like something we could use. I will try it out.

**Comment by danielleroux** [comment]
I will close this issue, if there is still a open topic, please create a new issue.
