### ISSUE TITLE
iX-docs color search/filter

### ISSUE THREAD

**Issue by thatsBruno** [siemens/ix#917]
### Suggestion / feature request

Hi, I'm currently using iX in my project, replacing features, components and even colours! 
I wanted to suggest the ability to search for the hex color code in the [docs](https://ix.siemens.io/docs/theming/colors/), currently you can only filter by the iX variable name, and searching by the color hex would agilize the process of replacement it by a lot, thanks!

**Comment by nuke-ellington** [comment]
Thank you for your feedback. I think the main reason why hex values are not searchable is that changing the theme resets the color values which would affect the search results.
Can you not simply use the browser search to look up hex values?
