### ISSUE TITLE
iX colors docs only appear after searching for a color and going back.

### ISSUE THREAD

**Issue by thatsBruno** [siemens/ix#918]
### What happened?

Hello, when opening this [page](https://ix.siemens.io/docs/theming/colors/), iX color docs, the colors don't show initially, they only appear after searching for a color and going back.
_Tested on Edge(119.0.2151.58) and Firefox Developer(120.0b9)._

![ix-color-bug](https://github.com/siemens/ix/assets/28793603/ac91a6d5-7d07-405b-a6f6-573c3568b22e)

**Comment by nuke-ellington** [comment]
Tracked by [IX-617]

**Comment by flxlst09** [comment]
Fixed with latest deployment
