### ISSUE TITLE
VueJS: IX vue-test-app DateDropdown and DateDropdownUserRange Component Build Errors

### ISSUE THREAD

**Issue by memtech3** [siemens/ix#921]
### What happened?

VueJS `vue-test-app` package has the following errors that prevent build:
DateDropDownUserRange component from PreviewExamples requires `dayjs` package. Package is not specified in package.json. Installing `dayjs` resolves error.

Additionally, VueJS throws the following error for DateDropdown component: `Uncaught SyntaxError: ambiguous indirect export: IxDateDropdown`

Siemens IX Vue 2.04, Siemens IX 2.04, Vue 3.3.4

### What type of frontend frameware are you seeing the problem on?

Others

### Which version of iX do you use?

2.04

### Code to produce this issue.

```shell
Link to commit used:
https://github.com/siemens/ix/tree/316d01c9e2acde68b664a0b78a287a0730463f45/packages/vue-test-app
```

**Comment by danielleroux** [comment]
The dayjs dependency will be resolved via the dependency to `@siemens/ix`. The `vue-test-app` is part of the monorepo if you just install the dependency the test-app the component are not able to resolve its dependencies correclty.

**Comment by memtech3** [comment]
Are you saying that if I open the vue-test-app folder and run npm install, it is expected that dayjs will not be installed?

**Comment by danielleroux** [comment]
If you using the latest main you have to do install the complete mono repository. If you want to use the vue-test-app for the mantioned version you have to checkout the correct git tag e.g `v2.0.4`.

**Comment by memtech3** [comment]
I think this needs to be better documented. I also still feel like the dependency should be specified in the vue-test-app even in the monorepo so that it is easier to use the test app as a reference when creating your own ix based app

**Comment by danielleroux** [comment]
Will be handled we enhanced contributing guidelines. (#931)
