### ISSUE TITLE
Working title attribute on disabled elements

### ISSUE THREAD

**Issue by TDaniel-evo** [siemens/ix#924]
### Suggestion / feature request

In many cases we would like to display title on disabled elements to provide additional information to the user.
We can "trick" the elements to have title by wrapping them in a div but this leads to confusion and chaos in the HTML.

**Comment by nuke-ellington** [comment]
@jg0815 - What is your opinion regarding this topic? I could not find any WCAG recommendation but the vanilla HTML elements display the title even when disabled.

**Comment by nuke-ellington** [comment]
Disabled components will not display tooltips for the whole design system. The reasoning for this can be found in the discussion here #899

**Comment by TDaniel-evo** [comment]
![image](https://github.com/siemens/ix/assets/144789952/a2bf3d72-e3b3-43cc-9f83-558280c9b4d3)
