### ISSUE TITLE
user-check icon counterpart

### ISSUE THREAD

**Issue by raul3m** [siemens/ix#927]
### Suggestion / feature request

The icon user-check which is the user with a "check" mark, should have a counterpart, maybe something like the user icon with a cross(x) or something similar that represents no user-check

![image](https://github.com/siemens/ix/assets/46755481/97b17974-f207-4493-a222-bed3763045c7)

**Comment by nuke-ellington** [comment]
Will be handled via siemens/ix-icons#50
