### ISSUE TITLE
ix-menu-avatar-item doesnt load whole text.

### ISSUE THREAD

**Issue by davidmathew** [siemens/ix#934]
### What happened?

The avatar-item strings are shortened. Is there any way to increase the width of the menu?
![avatar-item](https://github.com/siemens/ix/assets/3677816/45ffe2f3-6ce8-43af-82f7-90312110389f)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
<ix-menu enableToggleTheme="true" showAbout="true">
    <ix-menu-avatar initials="JD" top="David Mathew Jones">
      <ix-menu-avatar-item label="Testbench" icon="plant-user-filled"></ix-menu-avatar-item>
      <ix-menu-avatar-item label="Profile" icon="user-profile"> </ix-menu-avatar-item>
    </ix-menu-avatar>
</ix-menu>
```

**Comment by jul-lam** [comment]
To change the width of the ix-menu-avatar-items following steps can be made:

**Option A:** Change all instances.

1. Add the following content to one of your css files. To which one depends on the needed scope (global, component).

```css
ix-menu-avatar * {
  width: 10rem;
}
``` 

**Option B:** Change specific instances.

1. Add a new class to the ix-menu-avatar instances which items should be adapted. The class could for example be named "extended-item-width".

```html
<ix-menu enableToggleTheme="true" showAbout="true">
  <ix-menu-avatar initials="JD" top="David Mathew Jones" class="extended-item-width">
    <ix-menu-avatar-item label="Testbench" icon="plant-user-filled"></ix-menu-avatar-item>
    <ix-menu-avatar-item label="Profile" icon="user-profile"> </ix-menu-avatar-item>
  </ix-menu-avatar>
</ix-menu>
``` 

2. Add the following content to one of your css files. To which one depends on the needed scope (global, component).

```css
ix-menu-avatar.extended-width * {
  width: 10rem;
}
```

**Comment by jul-lam** [comment]
Please refer to [Git-Issue 957](https://github.com/siemens/ix/issues/957) for the solution to the bug. The solution provided above is only a temporary workaround.
