### ISSUE TITLE
toggle theme doesn't switch between brand light and dark theme properly

### ISSUE THREAD

**Issue by davidmathew** [siemens/ix#935]
### What happened?

I’m using the siemens AG theme in styles.css as follows.

@import ‘[@siemens](https://community.siemens.com/u/siemens)/ix/dist/siemens-ix/siemens-ix.css’
@import ‘[@siemens](https://community.siemens.com/u/siemens)/ix-brand-theme/dist/ix-brand-theme/ix-brand-theme.css’

On loading it shows the siemens brand dark theme but when i click on toggle theme it switches between classic light and dark.

How to resolve this?

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
<ix-menu enableToggleTheme="true">
</ix-menu>
```

**Comment by jul-lam** [comment]
Please make sure the theme is correctly set in the body element of your application. For example:

```html
<body class="theme-brand-light">
    ...
</body>
``` 

If this is not the case the theme-switcher in the background will default to the classic themes. The video below shows the correct execution of the theme toggle.

https://github.com/siemens/ix/assets/151610373/cba0d2a6-becd-4b44-bc7d-67ea436744cc

**Comment by davidmathew** [comment]
Thanks @jul-lam
