### ISSUE TITLE
Modal 'centered' and 'animation' config options are broken in Ix 2.0

### ISSUE THREAD

**Issue by charlesp-siemens** [siemens/ix#943]
### What happened?

**The modal `centered=true` issue** is quite a major issue and is preventing us from migrating to Ix 2.0. 

When opening a modal with centered=true, the modal actually appears at the bottom of the page. This seems to be because `centered=true` applies a `top:50%` CSS rule to the modal, meaning the top of the modal will start half way down the view height. With any with sufficient height to the content in the modal, it's appearing all the way off the bottom of the screen, creating a scroll bar where the user can scroll below the page, outside of the NavigationBar even. 

You can see in the below screenshot the modal has created a scrollbar which i've had to scroll down to out of the regular view height in order to see the whole modal.

![image](https://github.com/siemens/ix/assets/151835310/91d4e349-0625-4426-a9a1-eccbcafd0ed8)

It seems to me the implementation of the `'align-center'` class should not use `top:50%` and instead use `margin: auto 0px`, to automatically center the dialog element. I would also suggest removing the translateY() from the elements transform style when centered=true, as this is doesn't look right when the dialog is centered. Please correct me if I'm misunderstanding something.

___

Secondly, **the `animation=false` config option** is also being ignored, and an animation is appearing every time the modal is shown, whereas before (we were using Ix 1.6.3), the modal would appear without animation when this flag was used.

Appreciate the help.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

2.0.3

### Code to produce this issue.

```shell
https://stackblitz.com/edit/f3pxvs?file=src%2Fmodal.tsx
```

**Comment by jul-lam** [comment]
The issue is related to the application context. Please add ```<IxApplicationContext>``` as described in the [documentation](https://ix.siemens.io/docs/controls/modal#react) to resolve this issue.
