### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'removeEventListener') at ValidationTooltip.call

### ISSUE THREAD

**Issue by charlesp-siemens** [siemens/ix#944]
### What happened?

All jest tests that involve interacting with a field utilizing an IxValidationTooltip are failing with the error quoted below. This has been happening for us since Ix 1.6.x but it didn't fail the tests, it would just clog up the console (which was difficult to work around in itself). Now (hundreds of) tests are failing and we haven't been able to find a solution on our end.

> TypeError: Cannot read properties of null (reading 'removeEventListener')
>     at ValidationTooltip.call (C:\Users\z004asyt\workspace\greactions\node_modules\@siemens\ix\components\src\components\validation-tooltip\validation-tooltip.tsx:190:22)
>     at ValidationTooltip.disconnectedCallback (C:\Users\z004asyt\workspace\greactions\node_modules\@stencil\core\internal\client\index.js:2586:46)
>     at ValidationTooltip.invokeTheCallbackFunction (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\generated\Function.js:23:26)
>     at invokeCEReactions (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\helpers\custom-elements.js:188:31)
>     at ceReactionsPostSteps (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\helpers\custom-elements.js:54:3)
>     at HTMLFormElement.removeChild (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\living\generated\Node.js:452:9)
>     at removeChild (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:11099:18)
>     at commitDeletionEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24028:15)
>     at recursivelyTraverseDeletionEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:23989:5)
>     at commitDeletionEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24118:9)
>     at commitDeletionEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:23976:5)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24259:9)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24576:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24293:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24346:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24293:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24576:9)
>     at recursivelyTraverseMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24273:7)
>     at commitMutationEffectsOnFiber (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24432:9)
>     at commitMutationEffects (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:24243:3)
>     at commitRootImpl (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26810:5)
>     at commitRoot (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26682:5)
>     at callback (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:26117:3)
>     at callback (C:\Users\z004asyt\workspace\greactions\node_modules\react-dom\cjs\react-dom.development.js:12042:22)
>     at flushActQueue (C:\Users\z004asyt\workspace\greactions\node_modules\react\cjs\react.development.js:2667:24)
>     at actImplementation (C:\Users\z004asyt\workspace\greactions\node_modules\react\cjs\react.development.js:2582:11)
>     at C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\act-compat.js:63:25
>     at Object.eventWrapper (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:78:27)
>     at Object.wrapEvent (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\event\wrapEvent.js:8:28)
>     at Object.call (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\event\dispatchEvent.js:47:22)
>     at Object.dispatchUIEvent (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\event\dispatchEvent.js:24:26)
>     at Mouse.up (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\system\pointer\mouse.js:91:30)
>     at PointerHost.release (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\system\pointer\index.js:74:28)
>     at pointerAction (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\pointer\index.js:62:47)
>     at runNextTicks (node:internal/process/task_queues:60:5)
>     at processTimers (node:internal/timers:511:9)
>     at Object.pointer (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\user-event\dist\cjs\pointer\index.js:35:9)
>     at Object.asyncWrapper (C:\Users\z004asyt\workspace\greactions\node_modules\@testing-library\react\dist\pure.js:71:14)
>     at C:\Users\z004asyt\workspace\greactions\src\components\experiments\tests\ImportExperiments.test.tsx:130:9

Thanks

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
Any jest test that utilizes an Ix input field inside an IxValidationTooltip.
```

**Comment by jul-lam** [comment]
The error message you provided could not be replicated. However, I was able to reproduce the error message from issue #945. After implementing the proposed solution, no errors were detected in my tests. I recommend trying again after the next release, including this fix. If the errors continue, please open a new issue related to this one and provide specific test examples that are causing the error.

**Comment by jul-lam** [comment]
After further tests I was able to reproduce the provided error message. I will adapt the branch and PR to include the necessary fix.
