### ISSUE TITLE
Jest test failure since Ix 2.0.4: TypeError: this.dialog.showModal is not a function

### ISSUE THREAD

**Issue by charlesp-siemens** [siemens/ix#946]
### What happened?

Since updating to Ix 2.0.4, whenever we call showModal in our jest tests, this error is given and the test fails. Below is the returned error (quite unspecific). 

> TypeError: this.dialog.showModal is not a function
>     at C:\Users\z004asyt\workspace\greactions\node_modules\@siemens\ix\components\src\components\modal\modal.tsx:145:34
>     at Timeout.task [as _onTimeout] (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\browser\Window.js:516:19)
>     at listOnTimeout (node:internal/timers:573:17)
>     at processTimers (node:internal/timers:514:7)

We are also getting a similar error in similar tests that involve launching a modal:

> TypeError: Cannot read properties of null (reading 'showModal')
>     at C:\Users\z004asyt\workspace\greactions\node_modules\@siemens\ix\components\src\components\modal\modal.tsx:145:34
>     at Timeout.task [as _onTimeout] (C:\Users\z004asyt\workspace\greactions\node_modules\jsdom\lib\jsdom\browser\Window.js:516:19)
>     at listOnTimeout (node:internal/timers:573:17)
>     at processTimers (node:internal/timers:514:7)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

2.0.4

### Code to produce this issue.

```shell
Any jest test which invokes a method such as:

const modal = await showModal({
      title: 'Example title,
      content: <div></div>,
      centered: true,
      animation: false,
    });
```

**Comment by jul-lam** [comment]
Can't reproduce the issue. I set up a simple React Test App using Gatsby. The `index.jsx` file looks as follows:

```jsx
import "../styles/styles.css"

import {
  IxApplicationContext,
  IxButton,
  IxModalContent,
  IxModalFooter,
  IxModalHeader,
  Modal,
  showModal,
} from '@siemens/ix-react';
import React, { useRef } from 'react';

function CustomModal() {
  const modalRef = useRef(null);

  const close = () => {
    modalRef.current?.close('close payload!');
  };
  const dismiss = () => {
    modalRef.current?.dismiss('dismiss payload');
  };

  return (
    <Modal ref={modalRef}>
      <IxModalHeader onCloseClick={() => dismiss()}>
        Example Title
      </IxModalHeader>
      <IxModalContent>Content</IxModalContent>
      <IxModalFooter>
        <IxButton outline onClick={() => dismiss()}>
          Cancel
        </IxButton>
        <IxButton onClick={() => close()}>OK</IxButton>
      </IxModalFooter>
    </Modal>
  );
}

const IndexPage = () => {
  async function show() {
    await showModal({
      content: <CustomModal />,
      centered: true,
      animation: false
    });
  }

  return (
    <IxApplicationContext>
      <IxButton onClick={show}>Modal</IxButton>
    </IxApplicationContext>
  );
}

export default IndexPage

export const Head = () => <title>Index Page</title>
```

Using Jest, I created an example test file:

```js 
import React from "react"
import { render, act } from "@testing-library/react"

import Index from "../index"

describe(`Index`, () => {
  it(`contains element`, () => {
    const { getByText } = render(<Index />)

    const button = getByText(`Modal`)

    act(() => {
      button.click()
    });
  })
})
``` 

Please make sure you are using the showModal as intended. If the issue persists, don't hesitate to open a new issue linked to this one with further information about your setup.

Here is the React Test App:
[my-gatsby-site.zip](https://github.com/siemens/ix/files/13584804/my-gatsby-site.zip)
