### ISSUE TITLE
Check-boxes are not align with each other in tree component

### ISSUE THREAD

**Issue by mtcetin9** [siemens/ix#950]
### What happened?

We're trying to implement tree that each item has check-box like the first picture below. However, since there is no check-box property of tree component(figma offers checkbox option for the tree component), we have tried to implement checkbox in the renderItem() function of the component. As a result, check-boxes of child items cannot align with the parent ones. So, is there any way to align check-boxes? 
![image](https://github.com/siemens/ix/assets/151855087/9393b3d7-4f31-48d6-b0a1-b884aa0bd012)
![misaligned](https://github.com/siemens/ix/assets/151855087/c814a9a2-5b94-45c4-83d9-f3277a7857a2)
![image](https://github.com/siemens/ix/assets/151855087/e7197b6c-a2bb-46cc-b9b8-8594cdc07d51)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
-
```

**Comment by silviowolf** [comment]
Hi @mtcetin9, there are currently internal alignment actiivites ongoing. One of the latest alignments is regarding the tree. We will change the positions of checkboxes from a very left alignment to an alginment left from the item (following the indent of the item). See screeshot of the classic dark theme.
We will change this in our Figma file soon. Implementing it this way is possible with the current tree components. The only difference to your screenshot is the checkbox will be placed right from the expand/collapse icon. 
![image](https://github.com/siemens/ix/assets/115155312/3927f329-774b-4832-bab8-8db5fc6fb1dd)
