### ISSUE TITLE
ix-pill & ix-basic-navigation -> Ix-Pill label is not displayed

### ISSUE THREAD

**Issue by Johanneslueke** [siemens/ix#954]
### What happened?

Hi iX-Team, I believe i found a bug. If the iX-pill is used on the iX-BasicNavigation header where the  App title is placed, the label text of the iX-Pill is invisible but the tooltip tells us the content of the pill.

![image 520293926](https://github.com/siemens/ix/assets/3592317/6a25b105-8bc6-4a26-acad-e11cf48c379d)

My Expectation is that the pill always and anywhere displays its label text

MRE: https://stackblitz.com/~/github.com/Johanneslueke/ix-pill_on_basic-navigation_label_not_displayed_
[package (1).json](https://github.com/siemens/ix/files/13484833/package.1.json)
[package-lock (3).json](https://github.com/siemens/ix/files/13484834/package-lock.3.json)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
import { AfterViewInit, Component, ViewChild, inject } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms'; 

@Component({
  selector: 'app-root', 
  template: `
  <ix-basic-navigation
  data-testid="crsp-main-navigation"
  hideHeader="false"
  breakpoints="sm|md"
>
  <div  slot="logo">some fance Titel <ix-pill variant="alarm" icon="disconnected"> Test </ix-pill></div>
  <ix-menu>
    <ix-menu-item tabIcon="home"> Home </ix-menu-item>
  </ix-menu>
  <ix-pill icon="disconnected"> Expect label to be readable </ix-pill>
   
</ix-basic-navigation>
 
  `,
})
export class AppComponent {
  
}
```

**Comment by nuke-ellington** [comment]
The logo slot is reserved for, well, logos. Placing custom components in there is neither supported nor encouraged. If you really need to place custom content inside of the header you will be able to do that with the updated app frame that will be released pretty soon.

**Comment by Johanneslueke** [comment]
Evenso, the pill should have worked in my eyes. But great to hear that something is in the making. Do have perhaps an approximate ETA for the next release?

**Comment by nuke-ellington** [comment]
This will be released within the next two months.

**Comment by hanneslueke** [comment]
Hello, 
any updated estimates regarding a release date for the updated app frame?

**Comment by nuke-ellington** [comment]
Hello @hanneslueke should be available within the next two weeks.
