### ISSUE TITLE
Message Bar is still active even after dismissed by clicking on close button

### ISSUE THREAD

**Issue by yuvraj88** [siemens/ix#972]
### What happened?

When you click on close button in message bar it hides as it intended to be, but if you click on the empty space where the close button was there in message bar you can see message bar toggles.
Steps to reproduce
1. Close message bar on clicking on X icon.
2. message bar hides.
3. Hover it where X icon was previously there.
4. it will show message bar and hides like toggling.

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.0

### Code to produce this issue.

```shell
https://stackblitz.com/run?file=src%2Fapp%2Fmessage-bar.ts
```

**Comment by nuke-ellington** [comment]
The message bar will not remove itself from the DOM. You will have to take care of that by yourself.
It only provides the fade out animation for convenience so that it does not have to be implemented over and over again.
