### ISSUE TITLE
Radio button does not align with text

### ISSUE THREAD

**Issue by manoloB111** [siemens/ix#973]
### What happened?

Trying to make a row of radio buttons but the text does not align with the button.
![radio-button](https://github.com/siemens/ix/assets/72673307/58a556f0-4722-4fba-814c-f851753233fa)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.3

### Code to produce this issue.

```shell
<input checked id="checkbox_1_1" name="group_1" type="radio" />
    <label for="checkbox_1_1"> Checked </label>

    <input id="checkbox_1_2" name="group_1" type="radio" />
    <label for="checkbox_1_2"> Normal </label>

    <input disabled id="checkbox_1_3" name="group_1" type="radio" />
    <label for="checkbox_1_3"> Disabled </label>
```

**Comment by nuke-ellington** [comment]
I cannot reporduce this behaviour. Are you sure there is no local styling in place that causes this effect?

**Comment by manoloB111** [comment]
I found the problem, the global font-size was messing the alignment of the radio
