### ISSUE TITLE
<ix-dropdown> Insufficient display width

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#974]
### What happened?

I need to display a web page on the IPC touchscreen, which doesn't have the same resolution as a laptop. the dropdown control only displays three letters when it is displayed, which is too few to let the user know what it stands for, is it possible to set the width of the dropdown wider?
![image](https://github.com/siemens/ix/assets/10339536/8d9520b1-f7a8-43de-b151-39e61260baa6)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
Set the browser to 800*600
```

**Comment by nuke-ellington** [comment]
I cannot reproduce this behavior.
Are you sure there is no local styling responsible for this issue (e.g. `ix-dropdown` with fixed `width`)?

<img width="886" alt="Screenshot 2023-12-07 at 10 43 05" src="https://github.com/siemens/ix/assets/14405078/701eb6ac-8c41-449b-bb6a-49a3dff96698">

**Comment by chencc1988** [comment]
@nuke-ellington  
No. I did not set any style sheet 

Could you try the following link to see if the drop down on your PC displays the same to mine?

https://stackblitz.com/edit/jcp216?file=src%2Fapp%2Fdropdown.ts

![image](https://github.com/siemens/ix/assets/10339536/66578467-45d2-428a-9474-48de23636095)
