### ISSUE TITLE
<ix-dropdown>Javascipt and HTML are in the wrong place

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#975]
### What happened?

Javascipt's code appears in HTML's Tab, and HTML appears in Javascipt's Tab

![image](https://github.com/siemens/ix/assets/10339536/63743a8e-3b3c-4a00-91a0-ab9cdfce0981)
![image](https://github.com/siemens/ix/assets/10339536/bbe9e6cd-4a6d-42b1-b8bb-8e99a05d7af7)

**Comment by nuke-ellington** [comment]
Fix via #929
