### ISSUE TITLE
<ix-menu-item> The icon name is displayed when you mouse over the menu icon.

### ISSUE THREAD

**Issue by chencc1988** [siemens/ix#976]
### What happened?

The icon name is displayed when you mouse over the <ix-menu-item> icon. For example, moving over `<ix-menu-settings>` displays the cogwheel, which can be confusing for users.
![Animation](https://github.com/siemens/ix/assets/10339536/02bd4ad1-1c94-4f05-a5b6-ca0b47754142)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/vb8qfn?file=src%2Fapp%2Fbasic-navigation.ts
```

**Comment by nuke-ellington** [comment]
Fixed in #887
