### ISSUE TITLE
update Angular to v17

### ISSUE THREAD

**Issue by AGreat1** [siemens/ix#977]
### Suggestion / feature request

Current `@siemens/ix-angular` package is at Angular 13. Can we please have it updated to 17?

Can we please have regular updates of the framework in the future?

**Comment by danielleroux** [comment]
The peerDependency is `>=13` (see https://github.com/siemens/ix/blob/main/packages/angular/package.json#L22)

**Comment by nuke-ellington** [comment]
Which iX version are you running?

**Comment by AGreat1** [comment]
2.04

**Comment by nuke-ellington** [comment]
Cannot reproduce this issue. Pleaes make sure to set the basic navigation height to fill the available space (e.g. `height: 100vh`). Otherwise it will not be displayed properly.
