### ISSUE TITLE
The ability to disable browser autoComplete for IxSelect components

### ISSUE THREAD

**Issue by charlesp-siemens** [siemens/ix#979]
### Suggestion / feature request

Hi, currently there is no way of disabling browser-based autocomplete in IxSelect components (as pictured below).
![image](https://github.com/siemens/ix/assets/151835310/24f5153e-e9f4-4058-aea2-567ff7af506f)

I believe the only required implementation would be to expose a property on IxSelect (such as `autoComplete: boolean`), and pass it through to the input element that IxSelect makes use of to display the selected value.

Thanks!

**Comment by nuke-ellington** [comment]
Also relevant for ix-category-filter
