### ISSUE TITLE
No selected tab indicator

### ISSUE THREAD

**Issue by robert-wettstaedt** [siemens/ix#982]
### What happened?

Selected tabs do not show a visual indicator of being selected. The `selected` class gets applied, but no styling is linked to the class. 

Rounded tabs have an indicator.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
https://ix.siemens.io/docs/controls/tabs
```

**Comment by nuke-ellington** [comment]
The line below the selected tab's label will change it's color.
This can be seen in the documentation:
<img width="257" alt="Screenshot 2023-12-07 at 16 38 34" src="https://github.com/siemens/ix/assets/14405078/9d700b77-75ba-4ad0-a01c-2bc19c4eae90">

If this is not working for you please let us know.

**Comment by robert-wettstaedt** [comment]
@nuke-ellington 
looking at the current [tabs docs page](https://ix.siemens.io/docs/controls/tabs) this line does not appear for me anymore, in fact there is no indication at all.

<img width="662" alt="Screenshot 2023-12-08 at 10 13 23" src="https://github.com/siemens/ix/assets/3035576/328ed4c8-460c-41ed-95cd-6b18e8baefc2">

I just checked different browsers and can confirm it works in Chrome, Firefox and Safari. But not in Firefox Developer Edition. Because of that, this might very well be just a bug in that particular browser version. In that case I think we can close this issue.

**Comment by nuke-ellington** [comment]
Thank you for taking the time to investigate further. I will close this. Feel free to re-open if you observe this in an officially released user agent.

**Comment by philipphutterer** [comment]
@nuke-ellington Please re-open this issue, as it is now in fact observable in the latest official firefox releases.
