### ISSUE TITLE
Disabled buttons could have corresponding cursor	

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#984]
### Suggestion / feature request

In some applications, disabled state of buttons (or similar UI elements) is more clearly identified by changing the cursor pointer to "not-allowed" (https://developer.mozilla.org/en-US/docs/Web/CSS/cursor).

The screenshot shows current vs. possible improved behavior:

![disabled-cursor-not-allowed](https://github.com/siemens/ix/assets/99844553/48e7e840-abdf-4e23-91bc-a9629f5e9cb9)

I am inserting a request here for consideration, because in the previous version of our application we had this behavior and because of using iX shadow-dom elements it cannot be easily improved by us.

**Comment by nuke-ellington** [comment]
@tomas-reznak thank you for the request. The usage of the not-allowed cursor for disabled elemens is currently not inline with the design system and will therefor not be implemented.
