### ISSUE TITLE
ix-event-list creates shadow-root with ul element which has unwanted, immutable margin-top of 14px

### ISSUE THREAD

**Issue by varta5** [siemens/ix#986]
### What happened?

Hello!

When I create an **ix-event-list** element, it contains a **margin-top** which _I cannot alter_ in the CSS file of the component. Can you please suggest how to manipulate this margin-top or better _set it to 0 (zero)_ in IX's code?

As per dev tools the margin-top of **ul** element under **#shadow-root** is set to _14px_, however it is not shown on which level it is set.

### Example code

`example.component.html`
```
<div class="example-container">
  <ul class="not-shadow-list">
    <li>List Item One</li>
    <li>List Item Two</li>
  </ul>
</div>

<div class="example-container">
  <ix-event-list id="event-list" item-height="L" animated="false">
    <li>List Item Three</li>
    <li>List Item Four</li>
  </ix-event-list>
</div>
```

`example.component.scss`
```
.example-container {
  margin: 30px;
  border: 5px solid red;
  padding: 0;
  width: 400px;
  height: 100px;
}
```

### Screenshots

Rendered view:

![example01](https://github.com/siemens/ix/assets/97350993/0d5092e6-db56-4e1c-9114-9bf86305d183)

The **ul** element _added myself does not have_ a margin-top:

![example02](https://github.com/siemens/ix/assets/97350993/7855b27a-d5ff-492b-94cc-806116d908ca)

But the **ul** in the _shadow-root_ of the **ix-event-list** element _has one_ and I cannot find why:

![example03](https://github.com/siemens/ix/assets/97350993/bd429847-4934-4255-bcbc-acc791e65135)

Please advise or fix the margin-top in IX. Thank you in advance!

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.3

### Code to produce this issue.

```shell
example.component.html:

<div class="example-container">
  <ul class="not-shadow-list">
    <li>List Item One</li>
    <li>List Item Two</li>
  </ul>
</div>

<div class="example-container">
  <ix-event-list id="event-list" item-height="L" animated="false">
    <li>List Item Three</li>
    <li>List Item Four</li>
  </ix-event-list>
</div>
```

example.component.scss
```
.example-container {
  margin: 30px;
  border: 5px solid red;
  padding: 0;
  width: 400px;
  height: 100px;
}
```
```

**Comment by nuke-ellington** [comment]
Hello @varta5, the `ix-event-list` only supports nested `ix-event-list-items`. E.g.:

```
<ix-event-list>
  <ix-event-list-item>Text 1</ix-event-list-item>
  <ix-event-list-item>Text 2</ix-event-list-item>
</ix-event-list>
```

Placing arbitray mark-up inside of the component can lead to unexpected results and will most likely not be inline with the design system.
