### ISSUE TITLE
Avatar title/name

### ISSUE THREAD

**Issue by thatsBruno** [siemens/ix#991]
### Suggestion / feature request

I'm have currently the navigation-menu implemented in a project together with the iX avatar, however I noticed that there's no flexibility to introduced the users name next to the avatar when the sidebar is open.
Is there any future plans to add this feature?

![image](https://github.com/siemens/ix/assets/28793603/fb8eb7cd-cc91-482a-b8ac-11ea51ca5f7a)

**Comment by nuke-ellington** [comment]
Actually there is. Please use the `top` and `bottom` properties of `ix-menu-avatar` to display the name.
