### ISSUE TITLE
ix-event-list creates shadow-root with ul which has unwanted, immutable margin-top of 14px

### ISSUE THREAD

**Issue by varta5** [siemens/ix#994]
### What happened?

Hello!

When I create an **ix-event-list** element, it contains a **margin-top** which _I cannot alter_ in the CSS file of the component. Can you please suggest how to manipulate this margin-top or better _set it to 0 (zero)_ in IX's code?

As per dev tools the margin-top of **ul** element under **#shadow-root** is set to _14px_, however it is not shown on which level it is set.

### Example code

`example.component.html`
```
<div class="example-container">
  <ul class="not-shadow-list">
    <li>List Item One</li>
    <li>List Item Two</li>
  </ul>
</div>

<div class="example-container">
  <ix-event-list id="event-list" item-height="L" animated="false">
  </ix-event-list>
</div>

<div class="example-container">
  <ix-event-list id="event-list" item-height="L" animated="false">
    <ix-event-list-item>Text 1</ix-event-list-item>
    <ix-event-list-item>Text 2</ix-event-list-item>
  </ix-event-list>
</div>
```

`example.component.scss`
```
.example-container {
  margin: 30px;
  border: 5px solid red;
  padding: 0;
  width: 400px;
  height: 100px;
}
```

### Screenshots

Rendered view:

![example11](https://github.com/siemens/ix/assets/97350993/38c2a773-983c-4484-9f01-71d5b01cc866)

The **ul** element _added myself does not have_ a margin-top:

![example12](https://github.com/siemens/ix/assets/97350993/e3ba60e4-abda-484e-a03b-f661346c541e)

But the **ul** in the _shadow-root_ of the **ix-event-list** element _has one_ and I cannot find why:

![example13](https://github.com/siemens/ix/assets/97350993/8fc89dda-ac0d-46ee-bbc0-0e2820c6fbdd)

![example14](https://github.com/siemens/ix/assets/97350993/c7e37d09-c74d-47b6-ab48-ff4715b95a8f)

Please advise or fix the margin-top in IX. Thank you in advance!

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.3

### Code to produce this issue.

```shell
<div class="example-container">
  <ul class="not-shadow-list">
    <li>List Item One</li>
    <li>List Item Two</li>
  </ul>
</div>

<div class="example-container">
  <ix-event-list id="event-list" item-height="L" animated="false">
  </ix-event-list>
</div>

<div class="example-container">
  <ix-event-list id="event-list" item-height="L" animated="false">
    <ix-event-list-item>Text 1</ix-event-list-item>
    <ix-event-list-item>Text 2</ix-event-list-item>
  </ix-event-list>
</div>
```

**Comment by nuke-ellington** [comment]
The `margin-top` comes from the default user agent stylesheet. We will provide a fix for it.

**Comment by nuke-ellington** [comment]
@varta5 will be released in January
