### ISSUE TITLE
Hover over on chevron of link button shows hover over with name of item

### ISSUE THREAD

**Issue by AnnaGrahl** [siemens/ix#995]
### What happened?

We use the new link buttons. 
When you hover over the chevron icon, there is a hover over with the text "chevron-right-small". If you hover over the text, the link shows up correctly

![image](https://github.com/siemens/ix/assets/153725916/f4ba16f6-8b69-4b71-bebf-e13dff7b6cdd)

### What type of frontend frameware are you seeing the problem on?

Angular

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
<ix-link-button
   url="https://new.siemens.com/global/en/general/legal.html"
   target="_blank">
       Siemens Corporate Information
</ix-link-button>
```

**Comment by nuke-ellington** [comment]
Will be fixed via siemens/ix-icons#49
