### ISSUE TITLE
IX Brand theme: theme-brand-light is not getting applied when body has existing classes and switch from default to light

### ISSUE THREAD

**Issue by MonikaPoola** [siemens/ix#998]
### What happened?

I have sample projected created with lit and Vite using ix brand theme.

Our requirement is to get the theme from local storage, if key is not available it should switch to our app default value "theme-brand-light".

The theme switching is working fine when we do not have any classes in the body.

Observed that in ix-brand-theme.css **body:not([class^=theme-]** which is creating the issue since our appliation will always have additional classes.

Note: Its working fine with theme-classic light as it has body:not([class*=theme-])

![image](https://github.com/siemens/ix/assets/31481501/79bc8dd6-b640-4021-ac49-e62845eb03c4)

### What type of frontend frameware are you seeing the problem on?

Others

### Which version of iX do you use?

v2.0.0

### Code to produce this issue.

```shell
https://github.com/MonikaPoola/vite-project.git
```

**Comment by nuke-ellington** [comment]
Duplicate issue, will be tracked via #888
