### ISSUE TITLE
IxWorkFlowStep icon  is not visible

### ISSUE THREAD

**Issue by Ooner** [siemens/ix#999]
### What happened?

When I try to render basic Workflow component with a few steps like https://ix.siemens.io/docs/controls/workflow react sample the workflowsteps icon is not being rendered.

![workflowsteps](https://github.com/siemens/ix/assets/23223914/3f8c38b2-e751-4d90-982c-f9ac8bbf5a37)

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v2.0.4

### Code to produce this issue.

```shell
https://stackblitz.com/edit/ezsxkp?file=src%2Fworkflow.tsx
```

**Comment by ridvandmrc** [comment]
I think, this is related ix-icon component that is an another library. I think loadIconContent should be called in other lifecycle **componentDidLoad**()

should be used:
![image](https://github.com/siemens/ix/assets/15720132/2421bd2d-4198-4346-859e-1b1cde85bcad)

instead

![image](https://github.com/siemens/ix/assets/15720132/680b5b76-c088-4934-aca9-750efaff6abc)

**Comment by matthiashader** [comment]
Internal ref [IX-882]

**Comment by muratayik** [comment]
Any progress about this issue? We are still having the issue

ix version : 2.1.1
ix-icons-version: 2.1.0

Reproducable at https://stackblitz.com/edit/ezsxkp-hr6ua9

**Comment by matthiashader** [comment]
Hello @muratayik - currently this issue is internally tracked and prioritised - sorry for the circumstances
